### ISSUE TITLE
Variable string expansion are based on Groovy instead of Scala

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#11]
I am not familiar with all the flavours of JVM based languages yet, but I noticed that I received errors when using Scala syntax for transition conditions, FileSource arguments, or inputFiles/outputFiles strings. This is a bit confusing and unexpected given that the OpenMOLE script language is Scala. For example, the following failed because of the missing empty braces:

```scala
val f = Val[File]
val e = ExplorationTask(f in SelectFileDomain(new File("."), "input.txt"))
val t = EmptyTask()
val c1 = StrainerCapsule(t)
val c2 = StrainerCapsule(t)
val ex = e -< c1 -- ((c2 hook ToStringHook()) when "f.exists") start
```

Here's the error output of failing to execute the condition ```f.exists``` using the Groovy runtime. After changing the condition to ```f.exists()```, it works fine.

```
SEVERE: Error in Transition from emptyTask0 to Slot hash 761665356 of emptyTask1
org.openmole.core.exception.UserBadDataError: Script execution error !
The script was:
f.exists
It has raised the exception:
 | groovy.lang.MissingPropertyException: No such property: exists for class: java.io.File
 | 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:51)
 | 	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
 | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:293)
 | 	at script.Script1.run(Script1.groovy:2)
 | 	at org.openmole.core.tools.script.GroovyProxy.executeUnsynchronized(GroovyProxy.scala:71)
 | 	at org.openmole.core.tools.script.GroovyProxy.execute(GroovyProxy.scala:66)
 | 	at org.openmole.core.workflow.tools.GroovyContextAdapter$class.execute(GroovyContextAdapter.scala:24)
 | 	at org.openmole.core.workflow.transition.Condition$$anon$2$$anon$1.execute(Condition.scala:40)
 | 	at org.openmole.core.workflow.transition.Condition$$anon$2.evaluate(Condition.scala:41)
 | 	at org.openmole.core.workflow.transition.Transition.isConditionTrue(Transition.scala:93)
 | 	at org.openmole.core.workflow.transition.Transition.perform(Transition.scala:85)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:144)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:144)
 | 	at scala.collection.immutable.List.foreach(List.scala:381)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply$mcV$sp(SubMoleExecution.scala:144)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:144)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:144)
 | 	at org.openmole.core.tools.service.LockUtil$LockDecorator.apply(LockUtil.scala:29)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:143)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:256)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$stateChanged$2(SubMoleExecution.scala:216)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
 | 	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
 | 	at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:89)
 | 	at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:93)
 | 	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:100)
 | 	at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
 | 	at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
 | 	at scala.collection.immutable.List.foreach(List.scala:381)
 | 	at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
 | 	at java.lang.Thread.run(Thread.java:745)
	at org.openmole.core.tools.script.GroovyProxy.executeUnsynchronized(GroovyProxy.scala:78)
	at org.openmole.core.tools.script.GroovyProxy.execute(GroovyProxy.scala:66)
	at org.openmole.core.workflow.tools.GroovyContextAdapter$class.execute(GroovyContextAdapter.scala:24)
	at org.openmole.core.workflow.transition.Condition$$anon$2$$anon$1.execute(Condition.scala:40)
	at org.openmole.core.workflow.transition.Condition$$anon$2.evaluate(Condition.scala:41)
	at org.openmole.core.workflow.transition.Transition.isConditionTrue(Transition.scala:93)
	at org.openmole.core.workflow.transition.Transition.perform(Transition.scala:85)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:144)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:144)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply$mcV$sp(SubMoleExecution.scala:144)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:144)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:144)
	at org.openmole.core.tools.service.LockUtil$LockDecorator.apply(LockUtil.scala:29)
	at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:143)
	at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:256)
	at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$stateChanged$2(SubMoleExecution.scala:216)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
	at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:89)
	at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:93)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:100)
	at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
	at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by romainreuillon** [comment]
For historical reasons some code snipet in OpenMOLE are in groovy. We likely will migrate them to scala in the future.

**Comment by schuhschuh** [comment]
I wouldn't just close this issue. It was less of a question but a criticism. It is pretty surprising at first when a condition with valid Scala syntax written within a Scala script doesn't compile. As long as Groovy is used under the hood, I would at least document this as part of the description of the conditional task execution.

**Comment by romainreuillon** [comment]
It some point I'll check the feasibility of migrating the code strings to scala.

**Comment by romainreuillon** [comment]
All code string in OpenMOLE have been migrated from groovy to scala.

**Comment by schuhschuh** [comment]
These changes introduced other problems. See #60 and PR #61.
