### ISSUE TITLE
External imports not imported

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#123]
When the script is compiled (either from Play in the GUI or load in the console), external imports are not resolved.

In the console, a workaround is to import separately prior to the load("workflow.oms").

Minimal non-working example and fix:

**kldiv.oms**

```scala
import sys.process._

// workflow construction

...

/// Subjects exploration ///
val InitDir = "/vol/vipdata/data/HCP100/inits/25"
val initlist = (s"ls ${InitDir}" !!) split("\n") toList

```

**Loading in the console:**

```bash
OpenMOLE>val wf = load("kldiv.oms")
<console>:166: error: value !! is not a member of String
       val initlist = (s"ls ${InitDir}" !!) split("\n") toList
                                        ^
<console>:175: error: type mismatch;
 found   : maxflowClass.this.init.type (with underlying type org.openmole.core.workflow.data.Prototype[String])
 required: ?{def in: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method prototypeFactorDecorator in trait SamplingPackage of type [T](p: org.openmole.core.workflow.data.Prototype[T])AnyRef{def in[D <: org.openmole.core.workflow.domain.Domain[T]](d: D): org.openmole.core.workflow.sampling.Factor[T,D]}
 and method prototypeCollectionConverter in package collection of type [T](p: org.openmole.core.workflow.data.Prototype[T])AnyRef{def in(i: Iterable[T]): org.openmole.core.workflow.sampling.Factor[T,org.openmole.plugin.domain.collection.IterableDomain[T]]; def in(p2: org.openmole.core.workflow.data.Prototype[Array[T]]): org.openmole.core.workflow.sampling.Factor[T,org.openmole.plugin.domain.collection.VariableDomain[T]]}
 are possible conversion functions from maxflowClass.this.init.type to ?{def in: ?}
             (init in initlist.take(25))
              ^
javax.script.ScriptException: compile-time error
  at scala.tools.nsc.interpreter.IMain.compiled(IMain.scala:600)
  at scala.tools.nsc.interpreter.IMain.eval(IMain.scala:1066)
  at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
  at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:1060)
  at org.openmole.core.console.ScalaREPL.compile(ScalaREPL.scala:90)
  at org.openmole.console.Project.compile(Project.scala:64)
  at org.openmole.console.Project.compile(Project.scala:58)
  at org.openmole.console.Command.loadAny(Command.scala:115)
  at org.openmole.console.Command.load(Command.scala:124)
  ... 46 elided
```

**Manual import fix:**

```bash
OpenMOLE>import sys.process._
import sys.process._
OpenMOLE>val wf = load("kldiv.oms")
warning: there were 24 feature warnings; re-run with -feature for details
ls: cannot access /vol/vipdata/data/HCP100/inits/25: No such file or directory
java.lang.RuntimeException: Nonzero exit value: 2
...
```

*(runs but can't find the file)*

**Comment by romainreuillon** [comment]
This file works:

```scala
import sys.process._

/// Subjects exploration ///
val InitDir = "/tmp"
val initlist = (s"ls ${InitDir}".!!) split("\n") toList

EmptyTask()
```

**Comment by romainreuillon** [comment]
:) "ls: cannot access /vol/vipdata/data/HCP100/inits/25: No such file or directory" does't look like an bug from OpenMOLE.

**Comment by romainreuillon** [comment]
I have read the stuff to quickly this is actually when it works...

**Comment by romainreuillon** [comment]
In console mode:
```
OpenMOLE>load("/tmp/test.oms")
warning: there were two feature warnings; re-run with -feature for details
res0: org.openmole.core.workflow.puzzle.Puzzle = Puzzle(slot@108034745:EmptyTask@1036138670,List(EmptyTask@1036138670),List(),List(),List(),List(),Map(),Map())
OpenMOLE>import sys.process._
import sys.process._
OpenMOLE>
OpenMOLE>/// Subjects exploration ///
OpenMOLE>val InitDir = "/tmp"
InitDir: String = /tmp
OpenMOLE>val initlist = (s"ls ${InitDir}".!!) split("\n") toList
warning: there was one feature warning; re-run with -feature for details
initlist: List[String] = List(config-err-CQR3uJ, gpg-aoXwkc, hsperfdata_reuillon, iconcache-CATFtr, jetty-localhost-46447-webapp-_-any-, orbit-reuillon, scalajs-library_2.11-0.6.52038405207401737101.jar, systemd-private-bde3f7377f0c4403a16da49204b0ae9d-colord.service-q98EM4, systemd-private-bde3f7377f0c4403a16da49204b0ae9d-rtkit-daemon.service-5Rjfip, systemd-private-bde3f7377f0c4403a16da49204b0ae9d-systemd-timesyncd.service-3uGZAu, test.oms, unity_support_test.0)
OpenMOLE>
OpenMOLE>EmptyTask()
res2: org.openmole.core.workflow.builder.TaskBuilder{def toTask: org.openmole.core.workflow.task.EmptyTask with this.Built} = org.openmole.core.workflow.task.EmptyTask$$anon$2@104b145b
OpenMOLE>
```

**Comment by jopasserat** [comment]
I've just re-tested with 2 fresh installs from the website (v5 and v6) and both of them spit the same error message on my machine:

```bash
OpenMOLE>load("toto.oms")
<console>:166: error: value !! is not a member of String
       val initlist = (s"ls ${InitDir}" !!) split("\n") toList
                                        ^
```

(with toto.oms your minimal code with the `EmptyTask`

**Comment by romainreuillon** [comment]
The content of my test.oms is:
```scala
import sys.process._

/// Subjects exploration ///
val InitDir = "/tmp"
val initlist = (s"ls ${InitDir}".!!) split("\n") toList

EmptyTask()
```
Could you test with that?

**Comment by jopasserat** [comment]
That's what i've used with OM5 and OM6

**Comment by jopasserat** [comment]
Not a real bug: due to another OM script in the same folder
