### ISSUE TITLE
Skip does not strain outputs of task

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#15]
When using the new ```Skip``` pattern, I get a "formal validation failed" error on the following task because it says that none of its inputs are defined as outputs of the preceding ```Skip```. Removing the ```Skip``` and just leaving the task with condition (i.e., ```Skip(t, "cond")``` --> ```(t, "cond")```) works. Thus, this really seems to be an issue of the ```Skip```. Possibly the same problem might occur with the new ```Switch```.

OpenMOLE script:
```scala
import java.io.File
import com.andreasschuh.repeat._

// Configuration file used by tasks upon execution
val configFile = GlobalSettings().configFile

// Environment on which to execute commands
val parEnv = Environment.short
val symLnk = Environment.symLnk

// Constants
val imgCsv = Constants.imgCsv
val imgDir = Constants.imgIDir
val imgPre = Constants.imgPre
val imgSuf = Constants.imgSuf
val segDir = Constants.segIDir
val segPre = Constants.segPre
val segSuf = Constants.segSuf
val dofDir = Path.join(Constants.dofDir, getOrElse(args, 0, "affine"))
val subDir = dofDir.getName
val dofSuf = Constants.dofSuf
val outDir = Constants.segODir
val logDir = Constants.logDir
val logSuf = Constants.logSuf

val outSegPath  = Path.join(outDir, subDir, "${srcId}-${tgtId}" + segSuf).getAbsolutePath
val diceCsvPath = Path.join(outDir, subDir, "dice.csv").getAbsolutePath
val jaccCsvPath = Path.join(outDir, subDir, "jaccard.csv").getAbsolutePath

// Variables
val tgtId   = Val[Int]    // ID of target image
val srcId   = Val[Int]    // ID of source image
val tgtSeg  = Val[File]   // Target segmentation
val srcSeg  = Val[File]   // Source segmentation
val outDof  = Val[File]   // Transformation from target to source
val outSeg  = Val[File]   // Transformed source segmentation
val diceCsv = Val[File]   // CSV file with Dice coefficients for each transformation
val diceRow = Val[String] // Comma-separated Dice coefficients for each ROI of one segmentation
val jaccCsv = Val[File]   // CSV file with overlap measures for each transformation
val jaccRow = Val[String] // Comma-separated Jaccard indices for each ROI of one segmentation

// Exploration task which iterates the image IDs and file paths
val tgtIdSampling = CSVSampling(imgCsv) set (columns += ("ID", tgtId))
val srcIdSampling = CSVSampling(imgCsv) set (columns += ("ID", srcId))
val sampling = {
  (tgtIdSampling x srcIdSampling).filter("tgtId != srcId") x
  (tgtSeg in SelectFileDomain(segDir, segPre + "${tgtId}" + segSuf)) x
  (srcSeg in SelectFileDomain(segDir, segPre + "${srcId}" + segSuf)) x
  (outDof in SelectFileDomain(dofDir, "${tgtId},${srcId}" + dofSuf))
}

val forEachDof = ExplorationTask(sampling)

// Transform source segmentation
val warpBegin = EmptyTask() set (
    inputs  += (tgtId, tgtSeg, srcId, srcSeg, outDof),
    outputs += (tgtId, tgtSeg, srcId, srcSeg, outDof, outSeg)
  ) source FileSource(outSegPath, outSeg)

val _warpTask = ScalaTask(
  s"""
    | GlobalSettings.setConfigDir(workDir)
    |
    | val tgt    = new java.io.File(workDir, "$segPre" + tgtId + "$segSuf")
    | val src    = new java.io.File(workDir, "$segPre" + srcId + "$segSuf")
    | val dof    = new java.io.File(workDir, tgtId + "," + srcId + "$dofSuf")
    | val outSeg = new java.io.File(workDir, "$segPre" + srcId + "-" + tgtId + "$segSuf")
    |
    | IRTK.transform(src, outSeg, dofin = dof, interpolation = "NN", target = Some(tgt), matchInputType = true)
  """.stripMargin)

configFile match {
  case Some(file) => _warpTask.addResource(file)
  case None =>
}

val warpTask = _warpTask set (
    imports     += "com.andreasschuh.repeat._",
    usedClasses += (GlobalSettings.getClass, IRTK.getClass),
    inputs      += (tgtId, srcId),
    inputFiles  += (tgtSeg, segPre + "${tgtId}" + segSuf, symLnk),
    inputFiles  += (srcSeg, segPre + "${srcId}" + segSuf, symLnk),
    inputFiles  += (outDof, "${tgtId},${srcId}" + dofSuf, symLnk),
    outputFiles += (segPre + "${srcId}-${tgtId}" + segSuf, outSeg),
    outputs     += (tgtId, tgtSeg, srcId, srcSeg)
  ) hook CopyFileHook(outSeg, outSegPath) on parEnv

val warpSeg = warpBegin -- Skip(warpTask, "outSeg.lastModified() >= outDof.lastModified()")
//val warpSeg = warpBegin -- (warpTask, "outSeg.lastModified() >= outDof.lastModified()")

// Compute overlap measures
val calculateOverlap = ScalaTask(
  s"""
    | GlobalSettings.setConfigDir(workDir)
    |
    | val segA    = new java.io.File(workDir, "$segPre" + tgtId + "$segSuf")
    | val segB    = new java.io.File(workDir, "$segPre" + srcId + "-" + tgtId + "$segSuf")
    | val regions = Measure.regions
    |
    | val overlap = Measure.overlap(segA, segB)
    | val dice    = Measure.dice(overlap)
    | val jaccard = Measure.jaccard(overlap)
    |
    | val diceRow = tgtId + "," + srcId + "," + regions.map(region => dice   (region)).mkString(",")
    | val jaccRow = tgtId + "," + srcId + "," + regions.map(region => jaccard(region)).mkString(",")
  """.stripMargin) set (
    imports     += "com.andreasschuh.repeat._",
    usedClasses += (GlobalSettings.getClass, Measure.getClass),
    inputs      += (tgtId, srcId),
    inputFiles  += (tgtSeg, segPre + "${tgtId}" + segSuf),
    inputFiles  += (outSeg, segPre + "${srcId}-${tgtId}" + segSuf),
    outputs     += (diceRow, jaccRow)
  ) on parEnv

// Write overlap to CSV file, one for each measure
val writeToCsv = ScalaTask(
  """
    | GlobalSettings.setConfigDir(workDir)
    |
    | val regions = Measure.regions
    | val header  = "target,source," + regions.mkString(",")
    |
    | val diceCsv = new java.io.File(workDir, "dice.csv")
    | val diceWriter = new java.io.FileWriter(diceCsv, false)
    | try {
    |   diceWriter.write(header + '\n')
    |   diceCsv.foreach(row => diceWriter.write(row + '\n')
    | }
    | finally diceWriter.close()
    |
    | val jaccCsv = new java.io.File(workDir, "jaccard.csv")
    | val jaccWriter = new java.io.FileWriter(jaccCsv, false)
    | try {
    |   jaccWriter.write(header + '\n')
    |   jaccCsv.foreach(row => jaccWriter.write(row + '\n')
    | }
    | finally jaccWriter.close()
  """.stripMargin) set (
    imports     += "com.andreasschuh.repeat._",
    usedClasses += GlobalSettings.getClass,
    inputs      += (diceRow.toArray, jaccRow.toArray),
    outputFiles += ("dice.csv",    diceCsv),
    outputFiles += ("jaccard.csv", jaccCsv)
  ) hook (
    CopyFileHook(diceCsv, diceCsvPath),
    CopyFileHook(jaccCsv, jaccCsvPath)
  )

// Run overlap evaluation pipeline for each transformation
val exec = (forEachDof -< warpSeg -- calculateOverlap >- writeToCsv) start
exec.waitUntilEnded()
```

Console output:
```
_warpTask: org.openmole.plugin.task.scala.ScalaTaskBuilder{def toTask: org.openmole.plugin.task.scala.ScalaTask with this.Built} = org.openmole.plugin.task.scala.ScalaTask$$anon$2@1000dbea
res0: Any = org.openmole.plugin.task.scala.ScalaTask$$anon$2@1000dbea
warning: there were 6 feature warnings; re-run with -feature for details
warpTask: org.openmole.core.workflow.puzzle.PuzzlePiece = PuzzlePiece(Slot hash 918965208 of scalaTask1,List(),List(org.openmole.plugin.hook.file.CopyFileHook$$anon$1$$anon$2@50f771c6),Some(org.openmole.core.workflow.execution.local.LocalEnvironment@594fcb22),None)
warpSeg: org.openmole.core.workflow.puzzle.Puzzle = Puzzle(Slot hash 1504422323 of emptyTask0,List(emptyTask2),List(Transition from emptyTask0 to Slot hash 1750590156 of emptyTask3, Transition from scalaTask1 to Slot hash 981018779 of emptyTask2, Transition from emptyTask3 to Slot hash 918965208 of scalaTask1, Transition from emptyTask3 to Slot hash 1191390466 of emptyTask2),List(),List((emptyTask0,org.openmole.plugin.source.file.FileSource$$anon$2$$anon$1@10323056)),List((scalaTask1,org.openmole.plugin.hook.file.CopyFileHook$$anon$1$$anon$2@50f771c6)),Map(scalaTask1 -> org.openmole.core.workflow.execution.local.LocalEnvironment@594fcb22),Map())
warning: there were four feature warnings; re-run with -feature for details
calculateOverlap: org.openmole.core.workflow.puzzle.PuzzlePiece = PuzzlePiece(Slot hash 1254925592 of scalaTask4,List(),List(),Some(org.openmole.core.workflow.execution.local.LocalEnvironment@594fcb22),None)
warning: there were 6 feature warnings; re-run with -feature for details
writeToCsv: org.openmole.core.workflow.puzzle.PuzzlePiece = PuzzlePiece(Slot hash 1073343224 of scalaTask5,List(),List(org.openmole.plugin.hook.file.CopyFileHook$$anon$1$$anon$2@4588f119, org.openmole.plugin.hook.file.CopyFileHook$$anon$1$$anon$2@3d255920),None,None)
warning: there was one feature warning; re-run with -feature for details
org.openmole.core.exception.UserBadDataError: Formal validation of your mole has failed, several errors have been found: Input Data outSeg: java.io.File with mode None is missing when reaching the Slot hash 1254925592 of scalaTask4.
Input Data tgtId: Int with mode None is missing when reaching the Slot hash 1254925592 of scalaTask4.
Input Data tgtSeg: java.io.File with mode None is missing when reaching the Slot hash 1254925592 of scalaTask4.
Input Data srcId: Int with mode None is missing when reaching the Slot hash 1254925592 of scalaTask4.
  at org.openmole.core.workflow.mole.MoleExecution.start(MoleExecution.scala:181)
  ... 56 elided
<console>:148: error: not found: value exec
              exec.waitUntilEnded()

```

**Comment by romainreuillon** [comment]
This is what is expected since if the task in the Skip is by passed the inputs of the subsequent task are provided by the previous one. So what is the pb?

**Comment by romainreuillon** [comment]
Actually this is weird since tgtId is provided both by warpBegin and warpTask....

**Comment by romainreuillon** [comment]
In order to debug:
1/ name you task, with name := "some name", so we are sure which capsule is in error,
2/ print you workflow with: 
```
val mole = (forEachDof -< warpSeg -- calculateOverlap >- writeToCsv) toMole
println(mole.capsules)
println(mole.transitions)
```

**Comment by romainreuillon** [comment]
What is also weird is that I cannot reproduce this pb with a simple example, this works:
```
val i = Val[Int]
val j = Val[Int]

val t1 = ScalaTask("val i = 3") set (outputs += i)
val t2 = ScalaTask("i = i * 2") set (inputs += i, outputs += i)
val t3 = ScalaTask("val j = i") set (inputs += i, outputs += j)

val ex = t1 -- Skip(t2, "i < 4") -- (t3 hook ToStringHook())
```

Do you see any difference with your pb?

**Comment by schuhschuh** [comment]
> This is what is expected since if the task in the Skip is bypassed the inputs of the subsequent task are provided from the outputs of previous one. So what is the pb?

Ah, makes sense of course but not actually what I had in mind. But yes, as you said the ```warpBegin``` should already provide all the inputs needed by the task after the skipped one.

> 1/ name you task, with name := "some name", so we are sure which capsule is in error,

Nice, I was already going to ask on the list if it's possible to name tasks :)

But what am I doing wrong? The following
```scala
val warpBegin = EmptyTask() set (
    name    += "warpBegin",
    inputs  += (tgtId, tgtSeg, srcId, srcSeg, outDof),
    outputs += (tgtId, tgtSeg, srcId, srcSeg, outDof, outSeg)
  ) source FileSource(outSegPath, outSeg)
```
gives this error
```
<console>:159: error: value += is not a member of AnyRef{def :=[V <: AnyRef{def setName(name: String): Any}](name: String): V => Any}
           name    += "warpBegin",
```


> What is also weird is that I cannot reproduce this pb with a simple example, this works:

Yes, I also tried it with a simple example that I wanted to post otherwise. Actually, even with the previous construct before using the ```Switch``` I had similar problems when I was using a strainer capsule for the ```end```. I had to specify the inputs and outputs of this ```EmptyTask``` explicitly then it would work, i.e., the first example script I gave in #13 actually produces similar errors.

And indeed, I get the same error with the following amended example script that you can use:
```scala
val i = Val[Int]
val f = Val[File]
val e = ExplorationTask(i in (1 to 10))

val template = "/tmp/file${i}"
val begin = EmptyTask() set(inputs += i, outputs += (i, f)) source FileSource(template, f)
val task = ScalaTask("val f = newFile; // write to file f") set(inputs += i) hook CopyFileHook(f, template)
val cond = "!f.exists()"

val others = StrainerCapsule(EmptyTask()) hook ToStringHook()

// Workflow mole without use of Skip
/*
val end = StrainerCapsule(EmptyTask())
val mole = begin -- ((task -- end) when cond, end when s"!($cond)")
val ex = (e -< mole) + (end -- others) start
*/

// Workflow mole using Skip
val ex = e -< begin -- Skip(task, s"!($cond)") -- others start
```

> Do you see any difference with your pb?

Only that I set more properties of the task, that I have a ```CopyFileHook``` on it and set the parallel environment.

**Comment by romainreuillon** [comment]
It doesn't reproduce it neither, you are just missing ```outputs += f``` for "task".

For the name the syntax is an assignation: name := "blabla".

**Comment by schuhschuh** [comment]
> It doesn't reproduce it neither, you are just missing outputs += f for "task".

Hm, too bad.

In an attempt to adjust it to maybe find a simple example I get the following strange error:
```scala
val i = Val[Int]
val f = Val[File]
val e = ExplorationTask(i in (1 to 10))

val template = "/tmp/file${i}"
val begin = EmptyTask() set(name := "begin", inputs += i, outputs += (i, f)) source FileSource(template, f)
val task = ScalaTask("val f = new java.io.File(\"result.txt\"); // write to file f") set(
    name := "task",
    inputs += i,
    outputFiles += ("result.txt", f)
  ) hook CopyFileHook(f, template)
val cond = "!f.exists()"

val others = StrainerCapsule(EmptyTask() set(name := "others")) hook ToStringHook()

// Workflow mole without use of Skip
val end = StrainerCapsule(EmptyTask() set(name := "end"))
val mole = begin -- ((task -- end) when cond, end when s"!($cond)")
val ex = (e -< mole) + (end -- others) start

// Workflow mole using Skip
//val ex = e -< begin -- Skip(task, s"!($cond)") -- others start
```

```
ex: org.openmole.core.workflow.mole.MoleExecution = org.openmole.core.workflow.mole.MoleExecution@7317fb
java.lang.IllegalStateException: Bundle "initial@reference:file:plugins/org-codehaus-groovy_2.11.jar" has been uninstalled
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.checkValid(AbstractBundle.java:1175)
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:297)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
        at org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:263)
        at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:469)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.codehaus.groovy.reflection.stdclasses.CachedSAMClass$1.run(CachedSAMClass.java:101)
        at org.codehaus.groovy.reflection.stdclasses.CachedSAMClass$1.run(CachedSAMClass.java:99)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.codehaus.groovy.reflection.stdclasses.CachedSAMClass.getDeclaredMethods(CachedSAMClass.java:99)
        at org.codehaus.groovy.reflection.stdclasses.CachedSAMClass.getAbstractMethods(CachedSAMClass.java:117)
        at org.codehaus.groovy.reflection.stdclasses.CachedSAMClass.getSAMMethod(CachedSAMClass.java:183)
        at org.codehaus.groovy.reflection.ClassInfo.isSAM(ClassInfo.java:356)
        at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:346)
        at org.codehaus.groovy.reflection.ClassInfo.access$700(ClassInfo.java:38)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:494)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:485)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:108)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:107)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:189)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:93)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:71)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:62)
        at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
        at groovy.lang.Binding.<init>(Binding.java:33)
        at org.openmole.core.workflow.tools.ToolsPackage$ContextDecorator.toBinding(package.scala:43)
        at org.openmole.core.workflow.tools.GroovyContextAdapter$class.execute(GroovyContextAdapter.scala:24)
        at org.openmole.core.workflow.transition.Condition$$anon$2$$anon$1.execute(Condition.scala:40)
        at org.openmole.core.workflow.transition.Condition$$anon$2.evaluate(Condition.scala:41)
        at org.openmole.core.workflow.transition.Transition.isConditionTrue(Transition.scala:93)
        at org.openmole.core.workflow.transition.Transition.perform(Transition.scala:85)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:144)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:144)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply$mcV$sp(SubMoleExecution.scala:144)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:144)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:144)
        at org.openmole.core.tools.service.LockUtil$LockDecorator.apply(LockUtil.scala:29)
        at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:143)
        at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:256)
        at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$stateChanged$2(SubMoleExecution.scala:216)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
        at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:89)
        at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:93)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:100)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
        at java.lang.Thread.run(Thread.java:745)
```

> In order to debug:
1/ name you task, with name := "some name", so we are sure which capsule is in error,
2/ print you workflow with:

```
mole: org.openmole.core.workflow.mole.Mole = org.openmole.core.workflow.mole.Mole@aabe47a
Set(avgDice, avgJaccard, emptyTask0, warpTask, forEachDof, warpBegin, emptyTask1, writeJaccardToCsv, writeDiceToCsv, calculateOverlap)
List(AggregationTransition from calculateOverlap to Slot hash 2033202724 of writeDiceToCsv, AggregationTransition from calculateOverlap to Slot hash 647920347 of writeJaccardToCsv, AggregationTransition from calculateOverlap to Slot hash 1693638731 of avgDice, AggregationTransition from calculateOverlap to Slot hash 828066955 of avgJaccard, Transition from emptyTask0 to Slot hash 1221853714 of calculateOverlap, ExplorationTransition from forEachDof to Slot hash 1739639273 of warpBegin, Transition from warpBegin to Slot hash 171883032 of emptyTask1, Transition from warpTask to Slot hash 148010227 of emptyTask0, Transition from emptyTask1 to Slot hash 1619423221 of warpTask, Transition from emptyTask1 to Slot hash 1278859058 of emptyTask0)
warning: there was one feature warning; re-run with -feature for details
org.openmole.core.exception.UserBadDataError: Formal validation of your mole has failed, several errors have been found: Input Data tgtId: Int with mode None is missing when reaching the Slot hash 1221853714 of calculateOverlap.
Input Data tgtSeg: java.io.File with mode None is missing when reaching the Slot hash 1221853714 of calculateOverlap.
Input Data outSeg: java.io.File with mode None is missing when reaching the Slot hash 1221853714 of calculateOverlap.
Input Data srcId: Int with mode None is missing when reaching the Slot hash 1221853714 of calculateOverlap.
  at org.openmole.core.workflow.mole.MoleExecution.start(MoleExecution.scala:181)
  ... 56 elided
<console>:148: error: not found: value exec
              exec.waitUntilEnded()
```

**Comment by schuhschuh** [comment]
You should be able to reproduce it using my [REPEAT](https://github.com/schuhschuh/REPEAT) OpenMOLE plugin.

You can run the following shell script/commands to run my script. It will clone my plugin, build it, create some empty dummy files for the ```SelectFileDomain```, and run the OpenMOLE script. You can use the script to re-run the test only as it will not re-clone, or re-create files from a previous execution or simply run the last ```openmole``` command. The execution would fail because you are missing binaries and actual data, but the formal validation error shows up even before that.

```shell
#!/bin/bash
ids=(1 2 3)

if [ -f REPEAT/testSkip ]; then
  cd REPEAT/testSkip
elif [ -f testSkip ]; then
  cd testSkip
elif [ ! -f ../src/main/scala/com/andreasschuh/repeat/package.scala ]; then
  git clone git@github.com:schuhschuh/REPEAT.git || exit 1
  cd REPEAT       || exit 1
  sbt osgi-bundle || exit 1
  mkdir testSkip  || exit 1
  cd testSkip     || exit 1
fi

[ -f ids.csv ] || {
  echo "ID" > ids.csv
  for id in ${ids[@]}; do echo $id >> ids.csv; done
}

for id1 in ${ids[@]}; do
  [ -f ${id1}_3_glm.nii.gz ] || touch ${id1}_3_glm.nii.gz
  for id2 in ${ids[@]}; do
    [ $id1 -eq $id2 -o -f ${id1},${id2}.dof.gz ] || touch ${id1},${id2}.dof.gz
  done
done

[ -f ireg ] || touch ireg
[ -f repeat.conf ] || cat <<EOF > repeat.conf
irtk.bindir = .
image.csv = ids.csv
image.idir = .
segmentation.idir = .
dof.dir = .
EOF

openmole -c -p ../target/scala-2.11/repeat_2.11-0.1.jar -s ../src/mole/Overlap.scala

```

**Comment by romainreuillon** [comment]
It was a bug in the way strained inputs where calculated caused by some design I dislike in the scala collection: when you flatten on a Set it returns a Set so duplicate elements are implicitly remove and a Set is an Iterable, so I got bitten by not knowing I was playing with a Set.

It is fixed new thank for you help on debugging this !

**Comment by schuhschuh** [comment]
Glad it worked out to find the problem.

Compiling the master branch fails with the error:
```
[error] /Users/as12312/Software/OpenMOLE/openmole/core/org.openmole.core.workflow/src/main/scala/org/openmole/core/workflow/validation/TypeUtil.scala:39: type mismatch;
[error]  found   : scala.collection.immutable.Iterable[Option[org.openmole.core.workflow.data.Prototype[_$18]] forSome { type _$18 }]
[error]  required: Seq[Option[org.openmole.core.workflow.data.Prototype[_]]]
[error]     val r: Seq[Option[Prototype[_]]] = indexedD.map {
[error]                                                     ^
[error] one error found
[error] (org-openmole-core-workflow/compile:compileIncremental) Compilation failed
```

**Comment by schuhschuh** [comment]
I believe the fix is to add a ```.toSeq``` to the [following line in TypeUtil.scala](https://github.com/openmole/openmole/blob/69099ae484e76f834ed0d47ec4f602eb2772fa50/openmole/core/org.openmole.core.workflow/src/main/scala/org/openmole/core/workflow/validation/TypeUtil.scala#L37):

```scala
val indexedD = d.flatten.groupBy(_.name)
```

At least it compiles then.

**Comment by schuhschuh** [comment]
Works!
