### ISSUE TITLE
Fix argument parsing in CARE import wizard

### ISSUE THREAD

**Issue by ElCep** [openmole/openmole#160]
Dear magnificent dev team, 
It appear that the order or R launching command argument is relevant ! 
It doesn't work with :
```
R -f myscript.R --slave --args 4

```
but work wiht
```
R --slave -f myscript.R --args 4
```

**Comment by ElCep** [comment]
When packaging my howto R script with the care commend
```
/care-x86_64 -o r.tar.gz.bin R --slave -f myscript.R --args 4
```
The wizard produce this flowing launching commend
```
R  --slave myscript.R --args
```
the consequence is that the script is recognize as input and the argument `--args 4` is ignored .

**Comment by ElCep** [comment]
Dear magnificent dev team,
An other one :-S
```
org.openmole.core.exception.InternalProcessingError: Error for context values in CARETask@-1099920874 {i=100, oMSeed=-1628153349191324933}
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
	at org.openmole.plugin.task.care.CARETask.perform(CARETask.scala:71)
	at org.openmole.core.workflow.task.Task$class.perform(Task.scala:59)
	at org.openmole.plugin.task.care.CARETask.perform(CARETask.scala:71)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:83)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:64)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:61)
	at org.openmole.core.output.OutputManager$.withStreamOutputs(OutputManager.scala:99)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:129)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:61)
	at java.lang.Thread.run(Thread.java:745)
```
![](http://awesomegifs.com/wp-content/uploads/get-all-the-tennis-balls.gif)

**Comment by romainreuillon** [comment]
Parse value argument between argument with dashes (keys).

**Comment by mathieuleclaire** [comment]
966137fea975e7da99a0c02d4f476a47b6d03db9 fixes it.
