### ISSUE TITLE
Display a proper error message when an error is raised during archive extraction

### ISSUE THREAD

**Issue by ElCep** [openmole/openmole#161]
Dear magnificent dev team, 
It can be possible to support other can of archive when you want to import a model environment ?
```

POST https://localhost:39340/org/openmole/gui/shared/Api/extractTGZ
	
500 Internal Server Error
		28ms	
openmole.js (ligne 874)
EntêtesPostRéponse

java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.openmole.tool.file.FilePackage$FileDecorator.gzippedBufferedInputStream(package.scala:366)
	at org.openmole.tool.tar.package$FileTarArchiveDecorator$$anonfun$extractUncompress$1.apply(package
.scala:102)
	at org.openmole.tool.tar.package$FileTarArchiveDecorator$$anonfun$extractUncompress$1.apply(package
.scala:102)
	at org.openmole.tool.stream.package$.withClosable(package.scala:95)
	at org.openmole.tool.tar.package$FileTarArchiveDecorator.extractUncompress(package.scala:102)
	at org.openmole.gui.server.core.ApiImpl$.extractTGZToFromFiles(ApiImpl.scala:120)
	at org.openmole.gui.server.core.ApiImpl$.extractTGZTo(ApiImpl.scala:138)
	at org.openmole.gui.server.core.ApiImpl$.extractTGZ(ApiImpl.scala:129)
	at org.openmole.gui.server.core.ApiImpl$.extractTGZ(ApiImpl.scala:143)
	at org.openmole.gui.server.core.GUIServlet$$anonfun$10$$anonfun$apply$1.applyOrElse(GUIServlet.scala
:143)
	at org.openmole.gui.server.core.GUIServlet$$anonfun$10$$anonfun$apply$1.applyOrElse(GUIServlet.scala
:143)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.openmole.gui.server.core.GUIServlet$$anonfun$10.apply(GUIServlet.scala:143)
	at org.openmole.gui.server.core.GUIServlet$$anonfun$10.apply(GUIServlet.scala:143)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:285)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ScalatraBase$class.withRouteMultiParams(ScalatraBase.scala:356)
	at org.openmole.gui.server.core.GUIServlet.withRouteMultiParams(GUIServlet.scala:47)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:278)
	at org.openmole.gui.server.core.GUIServlet.invoke(GUIServlet.scala:47)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:253)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:251)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:251)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:250)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:250)
	at org.openmole.gui.server.core.GUIServlet.runRoutes(GUIServlet.scala:47)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at org.openmole.gui.server.core.GUIServlet.executeRoutes(GUIServlet.scala:47)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at org.openmole.gui.server.core.GUIServlet.withResponse(GUIServlet.scala:47)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at org.openmole.gui.server.core.GUIServlet.withRequest(GUIServlet.scala:47)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at org.openmole.gui.server.core.GUIServlet.withRequestResponse(GUIServlet.scala:47)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at org.openmole.gui.server.core.GUIServlet.org$scalatra$servlet$ServletBase$$super$handle(GUIServlet
.scala:47)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at org.openmole.gui.server.core.GUIServlet.org$scalatra$servlet$FileUploadSupport$$super$handle(GUIServlet
.scala:47)
	at org.scalatra.servlet.FileUploadSupport$class.handle(FileUploadSupport.scala:94)
	at org.openmole.gui.server.core.GUIServlet.handle(GUIServlet.scala:47)
	at org.scalatra.ScalatraServlet$class.service(ScalatraServlet.scala:60)
	at org.openmole.gui.server.core.GUIServlet.service(GUIServlet.scala:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by romainreuillon** [comment]
We should display a proper error message when an error is raised during extraction.

**Comment by mathieuleclaire** [comment]
7ce1545fb0c36884bfbb0b0a5b1773a520caae0c fixes it
