### ISSUE TITLE
"filename too long" if openmole started on an encrypted Linux partition or docker

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#165]
Got a FileSystemException "filename too long" when starting openmole for the first time. 

```
./openmole
!SESSION 2016-07-13 16:30:12.608 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -cp /home/sam/o/openmole-plugins -gp /home/sam/o/openmole-plugins-gui
Command-line arguments:  -consoleLog -cp /home/sam/o/openmole-plugins -gp /home/sam/o/openmole-plugins-gui

!ENTRY org.eclipse.osgi 4 0 2016-07-13 16:30:19.325
!MESSAGE Application error
!STACK 1
java.nio.file.FileSystemException: /home/sam/.openmole/samt430/webui/js/src/org-openmole-gui-client-core-ExecutionPanel$$anonfun$executionTable$1$$anonfun$apply$11$$anonfun$hiddenMap$lzycompute$1$2$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.sjsir: Nom de fichier trop long
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1118)
	at java.nio.file.Files.copy(Files.java:2831)
	at org.openmole.tool.file.FilePackage$InputStreamDecorator.copy(package.scala:127)
	at org.openmole.gui.bootstrap.js.BootstrapJS$$anonfun$init$1$$anonfun$apply$3$$anonfun$apply$4.apply(BootstrapJS.scala:105)
	at org.openmole.gui.bootstrap.js.BootstrapJS$$anonfun$init$1$$anonfun$apply$3$$anonfun$apply$4.apply(BootstrapJS.scala:104)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at org.openmole.gui.bootstrap.js.BootstrapJS$$anonfun$init$1$$anonfun$apply$3.apply(BootstrapJS.scala:104)
	at org.openmole.gui.bootstrap.js.BootstrapJS$$anonfun$init$1$$anonfun$apply$3.apply(BootstrapJS.scala:103)
	at scala.Option.foreach(Option.scala:257)
	at org.openmole.gui.bootstrap.js.BootstrapJS$$anonfun$init$1.apply(BootstrapJS.scala:103)
	at org.openmole.gui.bootstrap.js.BootstrapJS$$anonfun$init$1.apply(BootstrapJS.scala:102)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at org.openmole.gui.bootstrap.js.BootstrapJS$.init(BootstrapJS.scala:102)
	at org.openmole.ui.Application$$anonfun$start$1.apply(Application.scala:194)
	at org.openmole.ui.Application$$anonfun$start$1.apply(Application.scala:60)
	at org.openmole.core.replication.DBServerRunning$.useDB(DBServerRunning.scala:42)
	at org.openmole.ui.Application.start(Application.scala:60)
	at org.openmole.ui.Application.start(Application.scala:47)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
An error has occurred. See the log file
/home/sam/.openmole/.tmp/1468420212_16529/1468420212888.log.
```
It appears the error is known already: if the filesystem is encrypted, the encryption layer limits the filename size [https://bugs.launchpad.net/ecryptfs/+bug/344878]. Same thing might happen under docker. 
 
The **shortterm workaround** is to just avoid using encrypted partitions, for instance by simlinking ~/.openmole/ to another partition. 

If you want **to solve the issue in the long term**, an option might be passed to the scala compiler so it creates shorter filenames: [http://stackoverflow.com/questions/28565837/filename-too-long-sbt].
Unfortunatly, I don't see how to pass options to the scala compiler when launching openmole. 
Maybe this limitation might just be packaged by default into openmole ? 
It should look like `scalacOptions ++= Seq("-Xmax-classfile-name","140")` in one of the .bst. 
The precise value to define is unclear. For the encrypted ecryptfs partition issue, it should be less than 143 (link before). For docker, I've no idea.

**Comment by romainreuillon** [comment]
Hi Samuel,

This problem shouldn't appear in the dev version that you can get from http://next.openmole.org (since doesn't recompile the sjsir files at launch anymore). And I added the option to scalac aa855c63adfcd882b7f8693d44eddfd9f2fdf107.

Thx for the report !
