### ISSUE TITLE
Necessity to clean website generation project when updating Scala functions

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#172]
Functions defined/updated in `.scala` files cannot be seen by scalatex **unless the project is cleaned before being rebuilt**.

Scalatex code still sees the old definition and crashes at runtime when running the site generation script if `assemble` is called without a prior `clean`:
Below an example where the workDirectory2 was just added and called from Scalatex

```
openmole git:(updateDoc) ✗ ./bin/org.openmole.site/target/assemble/site --target /tmp/docOM --no-test --no-market-test
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.openmole.launcher.Launcher.main(Launcher.java:127)
Caused by: java.lang.NoSuchMethodError: org.openmole.site.Environment$.workDirectory2()Lscalatags/generic/Frag;
```

**Comment by romainreuillon** [comment]
Build system as been reworked reopen if it reappears.
