### ISSUE TITLE
Restarting server cannot be done twice

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#198]
The restart mechanism implemented in #102 calls the restart method of the ApplicationControl class:
https://github.com/openmole/openmole/blob/2e38c60cc7fc504c19599c7f67658d4901da381a/openmole/gui/server/org.openmole.gui.server.core/src/main/scala/org/openmole/gui/server/core/ApiImpl.scala#L79

It perfectly restarts the server once, but it does not work a second time and provides the following error:
```Exception in thread "Thread-1" java.lang.IllegalStateException: Module has been uninstalled.
	at org.eclipse.osgi.container.Module.checkValid(Module.java:526)
	at org.eclipse.osgi.container.Module.start(Module.java:392)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:311)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:386)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:336)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:328)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.openmole.tool.file.FilePackage$FileDecorator.recursiveDelete(package.scala:153)
	at org.openmole.core.workspace.Workspace.clean(Workspace.scala:132)
	at org.openmole.core.workspace.Workspace$$anon$1.run(Workspace.scala:63)


```

**Comment by romainreuillon** [comment]
Fixed in c5b3a42e3e73f4c50a4ba59b786134e7def42154.
