### ISSUE TITLE
Duplicate bcpkix bundle installation

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#2]
After following the [compilation instructions](http://www.openmole.org/current/documentation_development_compilation.html), I get the following startup error using master branch at commit 05b6de5 on OS X Yosemite with Oracle JRE 8 Update 31.

```
> bin/openmole/target/assemble/openmole
tail: -: No such file or directory
```
This error is not affecting the execution and is easily fixed by changing ```tail -1 -``` to ```tail -1``` in the ```openmole``` launcher shell script.

The following error seems to be related to a duplicate import of bcpkix:
```
!SESSION 2015-04-07 11:17:18.615 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -cp /Users/as12312/Software/OpenMOLE/openmole/bin/openmole/target/assemble/openmole-plugins -gp /Users/as12312/Software/OpenMOLE/openmole/bin/openmole/target/assemble/openmole-plugins-gui
Command-line arguments:  -consoleLog -cp /Users/as12312/Software/OpenMOLE/openmole/bin/openmole/target/assemble/openmole-plugins -gp /Users/as12312/Software/OpenMOLE/openmole/bin/openmole/target/assemble/openmole-plugins-gui

!ENTRY org.eclipse.osgi 2 0 2015-04-07 11:17:20.274
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2015-04-07 11:17:20.274
!MESSAGE Bundle au.com.bytecode.opencsv_2.3.0 [76] was not resolved.

!ENTRY org.eclipse.osgi 4 0 2015-04-07 11:17:20.275
!MESSAGE Application error
!STACK 1
org.openmole.core.exception.InternalProcessingError: Installing bundle /Users/as12312/Software/OpenMOLE/openmole/bin/openmole/target/assemble/openmole-plugins/bcpkix-jdk15on-1.50.jar
	at org.openmole.core.pluginmanager.PluginManager$.org$openmole$core$pluginmanager$PluginManager$$installBundle(PluginManager.scala:166)
	at org.openmole.core.pluginmanager.PluginManager$$anonfun$5.apply(PluginManager.scala:126)
	at org.openmole.core.pluginmanager.PluginManager$$anonfun$5.apply(PluginManager.scala:126)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.openmole.core.pluginmanager.PluginManager$.load(PluginManager.scala:126)
	at org.openmole.ui.Application.start(Application.scala:145)
	at org.openmole.ui.Application.start(Application.scala:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: org.eclipse.osgi.framework.internal.core.Framework$DuplicateBundleException: Bundle "bcpkix" version "1.50.0" has already been installed from: initial@reference:file:plugins/bcpkix-jdk15on-1.50.jar
	at org.eclipse.osgi.framework.internal.core.Framework.createAndVerifyBundle(Framework.java:722)
	at org.eclipse.osgi.framework.internal.core.Framework.installWorkerPrivileged(Framework.java:942)
	at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:845)
	at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.Framework.installWorker(Framework.java:904)
	at org.eclipse.osgi.framework.internal.core.Framework.installBundle(Framework.java:840)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.installBundle(BundleContextImpl.java:137)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.installBundle(BundleContextImpl.java:131)
	at org.openmole.core.pluginmanager.PluginManager$.org$openmole$core$pluginmanager$PluginManager$$installBundle(PluginManager.scala:174)
	... 23 more
An error has occurred. See the log file
/Users/as12312/.openmole/.tmp/1428401838_16865/1428401838806.log.
Exception in thread "Thread-3" java.lang.ExceptionInInitializerError
	at org.openmole.core.workspace.Workspace$.defaultLocation$lzycompute(Workspace.scala:70)
	at org.openmole.core.workspace.Workspace$.defaultLocation(Workspace.scala:70)
	at org.openmole.core.workspace.Workspace$.instance$lzycompute(Workspace.scala:71)
	at org.openmole.core.workspace.Workspace$.instance(Workspace.scala:71)
	at org.openmole.core.workspace.Workspace$$anon$2.run(Workspace.scala:75)
Caused by: com.thoughtworks.xstream.InitializationException: Could not instantiate converter : com.thoughtworks.xstream.converters.extended.DurationConverter : null
	at com.thoughtworks.xstream.XStream.registerConverterDynamically(XStream.java:918)
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:876)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
	at org.openmole.core.replication.DBServerInfo$.xstream$lzycompute(DBServerInfo.scala:45)
	at org.openmole.core.replication.DBServerInfo$.xstream(DBServerInfo.scala:45)
	at org.openmole.core.replication.DBServerInfo$.<init>(DBServerInfo.scala:46)
	at org.openmole.core.replication.DBServerInfo$.<clinit>(DBServerInfo.scala)
	... 5 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.thoughtworks.xstream.XStream.registerConverterDynamically(XStream.java:911)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.eclipse.osgi.internal.loader.BundleLoader.findDynamicSource(BundleLoader.java:1167)
	at org.eclipse.osgi.internal.loader.BundleLoader.findResource(BundleLoader.java:629)
	at org.eclipse.osgi.internal.loader.BundleLoader.findResource(BundleLoader.java:577)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.getResource(DefaultClassLoader.java:143)
	at org.eclipse.core.runtime.internal.adaptor.ContextFinder.getResource(ContextFinder.java:144)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1348)
	at javax.xml.datatype.SecuritySupport$4.run(SecuritySupport.java:90)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.datatype.SecuritySupport.getResourceAsStream(SecuritySupport.java:83)
	at javax.xml.datatype.FactoryFinder.findJarServiceProvider(FactoryFinder.java:286)
	at javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:258)
	at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:129)
	at com.thoughtworks.xstream.converters.extended.DurationConverter$1.getFactory(DurationConverter.java:39)
	at com.thoughtworks.xstream.converters.extended.DurationConverter.<init>(DurationConverter.java:44)
	... 20 more
```

**Comment by jopasserat** [comment]
Fixed in b8adcac1420df21314db5265729f582049fcfd82

**Comment by schuhschuh** [comment]
Wait a minute. I should have opened separate issues for this. The actual problem here is the duplicate bundle installation error ;) You think that's fixed, too ?

**Comment by romainreuillon** [comment]
Could you try to do sbt clean "project openmole" assemble, to check if a compilation from scratch leads to the same error ?

**Comment by schuhschuh** [comment]
After a clean build, I don't see this error anymore (also now I have SDK 8 instead of SDK 7 before). When I run ```openmole -c```, no error at all. Without the ```-c``` option it is not working, but as you said the GUI is in development anyway and this possibly expected.

**Comment by romainreuillon** [comment]
Great that it works in console mode. This error is indeed due to the GUI not being stable yet.
