### ISSUE TITLE
Makedir error using SSH  

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#208]
Hi, i continue to log error with ssh (tested on ssh/zebulon and slurm/criann) : 

At the very beginning of submission, i have multiple write error : 

```
PRÉCIS: Error creating base directory /home/rey/.openmole/.tmp/ssh/
java.io.IOException: Error make dir /home on org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1@5f3fa342
        at fr.iscpif.gridscale.storage.Storage$class.errorWrapping(Storage.scala:72)
        at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1.fr$iscpif$gridscale$ssh$SSHStorage$$super$errorWrapping(SSHStorageService$
scala:33)
```

```
mai 04, 2017 5:19:12 PM org.openmole.plugin.environment.batch.storage.StorageService$$anonfun$mkRootDir$1 apply
PRÉCIS: Error creating base directory /home/rey/.openmole/.tmp/ssh/
java.io.IOException: Error make dir /home/rey on org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1@5f3fa342
        at fr.iscpif.gridscale.storage.Storage$class.errorWrapping(Storage.scala:72)
        at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1.fr$iscpif$gridscale$ssh$SSHStorage$$super$errorWrapping(SSHStorageService.
scala:33)

```
etc ... all these errors have the same cause :  

```

Caused by: net.schmizz.sshj.sftp.SFTPException: Failure
        at net.schmizz.sshj.sftp.Response.error(Response.java:113)
        at net.schmizz.sshj.sftp.Response.ensureStatusIs(Response.java:106)
        at net.schmizz.sshj.sftp.Response.ensureStatusPacketIsOK(Response.java:99)
        at net.schmizz.sshj.sftp.SFTPEngine.makeDir(SFTPEngine.java:178)
        at net.schmizz.sshj.sftp.SFTPEngine.makeDir(SFTPEngine.java:183)
        at net.schmizz.sshj.sftp.SFTPClient.mkdir(SFTPClient.java:87)
        at fr.iscpif.gridscale.ssh.impl.SSHJSFTPClient$.mkdir(SSHJSFTPClient.scala:57)
        at fr.iscpif.gridscale.ssh.SSHClient$$anon$2.mkdir(SSHClient.scala:84)
        at fr.iscpif.gridscale.ssh.SSHStorage$$anonfun$_makeDir$1.apply(SSHStorage.scala:91)
        at fr.iscpif.gridscale.ssh.SSHStorage$$anonfun$_makeDir$1.apply(SSHStorage.scala:91)
        at fr.iscpif.gridscale.ssh.SSHHost$$anonfun$withSftpClient$1.apply(SSHHost.scala:51)
        at fr.iscpif.gridscale.ssh.SSHHost$$anonfun$withSftpClient$1.apply(SSHHost.scala:49)
        at fr.iscpif.gridscale.ssh.SSHConnectionCache$class.withConnection(SSHConnectionCache.scala:27)
        at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1.withConnection(SSHStorageService.scala:33)
        at fr.iscpif.gridscale.ssh.SSHHost$class.withSftpClient(SSHHost.scala:48)
        at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1.withSftpClient(SSHStorageService.scala:33)
        at fr.iscpif.gridscale.ssh.SSHStorage$class._makeDir(SSHStorage.scala:90)
        at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1._makeDir(SSHStorageService.scala:33)
        at fr.iscpif.gridscale.storage.Storage$$anonfun$makeDir$1.apply$mcV$sp(Storage.scala:50)
        at fr.iscpif.gridscale.storage.Storage$$anonfun$makeDir$1.apply(Storage.scala:50)
        at fr.iscpif.gridscale.storage.Storage$$anonfun$makeDir$1.apply(Storage.scala:50)
        at fr.iscpif.gridscale.storage.Storage$class.wrapException(Storage.scala:75)
        ... 62 more
```

**Comment by jopasserat** [comment]
Hey @reyman  

I've also had problems on Slurm due to a bug was fixed by @romainreuillon in master.
However we haven't redeployed to the website yet (spoiler alert) as it's undergoing a complete redesign for the 7.0 release.

Can you try with the archive in the pre-release?https://github.com/openmole/openmole/releases/download/v7.0-RC5/openmole.tar.gz

**Comment by jopasserat** [comment]
Any news on this @reyman ?

**Comment by romainreuillon** [comment]
Environment have been refactored in depth, please test and resubmit an issue if it reappears.
