### ISSUE TITLE
Problem with job submission, SLURM, and java null pointer exception ?

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#215]
Hi OpenMOLE team,

I have something weird during execution of even simple functionnal gama task model and very simple wf on grid (**1 execution of less than 2 min !**). 

**I precise that the same workflow works with LocalEnvironment(1) on my local server**

```
logger.level("FINE")
val seed = Val[Int]
val num_points = Val[Int]

val gama = 
  GamaTask(workDirectory / "voronoi.gaml", "voronoi", maxStep = 100) set (
    gamaInputs += (num_points, "num_points"),
    num_points := 5,
    seed := 42,
    
    gamaSeed := seed
  )
 
  val env =
  SLURMEnvironment(
    "sreyco01",
    "myria.criann.fr",
    queue = "2tcourt",
    openMOLEMemory = 4 gigabytes
  )

  gama on env hook ToStringHook()

```
![weird](https://cloud.githubusercontent.com/assets/466329/26730126/3f25a7c2-47b0-11e7-9ec8-245e27b4268b.jpg)

As you can see, the job submission go crazy after that and run multiple simulations.

During slurm execution, i see multiple attempt to create the /ssh directory : 

```
juin 02, 2017 4:44:26 PM org.openmole.plugin.environment.batch.storage.StorageService $anonfun$mkRootDir$5                                                                                                     
PRÉCIS: Error creating base directory /gpfs1/home/2017016/sreyco01/.openmole/.tmp/ssh/                                                                                                                         
java.io.IOException: Error make dir /gpfs1/home/2017016/sreyco01/.openmole/.tmp/ssh on org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1@6097abbc                                                  
        at fr.iscpif.gridscale.storage.Storage.errorWrapping(Storage.scala:72)                                                                                                                                 

...

Caused by: net.schmizz.sshj.sftp.SFTPException: Failure
        at net.schmizz.sshj.sftp.Response.error(Response.java:113)
        at net.schmizz.sshj.sftp.Response.ensureStatusIs(Response.java:106)
        at net.schmizz.sshj.sftp.Response.ensureStatusPacketIsOK(Response.java:99)
        at net.schmizz.sshj.sftp.SFTPEngine.makeDir(SFTPEngine.java:178)
        at net.schmizz.sshj.sftp.SFTPEngine.makeDir(SFTPEngine.java:183)
        at net.schmizz.sshj.sftp.SFTPClient.mkdir(SFTPClient.java:87)

```

Finally after that, script continue to run, because this message appear : 

```
PRÉCIS: SLURM job [85428], description:
 #!/bin/bash
#SBATCH -o ba771ddb-0550-488f-89aa-fd57582e805c.out
#SBATCH -e ba771ddb-0550-488f-89aa-fd57582e805c.err
#SBATCH -p 2tcourt
#SBATCH --mem=4400
#SBATCH --cpus-per-task=1
#SBATCH -D /gpfs1/home/2017016/sreyco01/.openmole/.tmp/ssh/openmole-92a7f4f7-0d29-48f4-893b-45c6588c7e86/tmp/1496414664017/a2483fd7-518e-4338-882b-5e70c9959f26

```

Another error appear later 

**The error :** 
```

juin 02, 2017 4:22:06 PM org.openmole.plugin.environment.batch.refresh.JobManager$ $bang
PRÉCIS: Error during job execution, it will be resubmitted.
java.lang.NullPointerException
        at org.openmole.core.workflow.tools.DefaultSet.iterator(DefaultSet.scala:47)
        at org.openmole.core.workflow.tools.DefaultSet.iterator$(DefaultSet.scala:47)
        at org.openmole.core.workflow.tools.DefaultSet$$anon$1.iterator(DefaultSet.scala:31)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at org.openmole.core.workflow.tools.DefaultSet$$anon$1.foreach(DefaultSet.scala:31)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at org.openmole.core.workflow.tools.DefaultSet$$anon$1.flatMap(DefaultSet.scala:31)
        at org.openmole.core.workflow.tools.InputOutputCheck$.initializeInput(InputOutputCheck.scala:75)
        at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:83)
        at org.openmole.core.expansion.FromContext$$anon$8.from(FromContext.scala:134)
        at org.openmole.core.workflow.task.Task.perform(Task.scala:60)
        at org.openmole.core.workflow.task.Task.perform$(Task.scala:58)
        at org.openmole.plugin.task.gama.GamaTask.perform(GamaTask.scala:90)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:101)
        at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:89)
        at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2$adapted(LocalExecutor.scala:73)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:73)
        at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:143)
        at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:70)
        at java.lang.Thread.run(Thread.java:745)
```

```
juin 07, 2017 9:52:24 AM org.openmole.plugin.environment.batch.refresh.KillerActor$ receive                                                                                                                    
PRÉCIS: Could not kill job.                                                                                                                                                                                    
fr.iscpif.gridscale.ssh.SSHException$NoSuchFileException: rm /gpfs1/home/2017016/sreyco01/.openmole/.tmp/ssh/openmole-5cd44822-d39d-4cb7-aba0-2d13241e3afe/tmp/1496821507647/60c95b76-e5f8-4332-87d3-a8d01e8cd$
43/a456c8b5-779c-45bc-beb8-d81569de2e37.slurm: No such file                                                                                                                                                    
        at fr.iscpif.gridscale.ssh.SSHStorage.errorWrapping(SSHStorage.scala:78)                                                                                                                               
        at fr.iscpif.gridscale.ssh.SSHStorage.errorWrapping$(SSHStorage.scala:75)                                                                                                                              
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.errorWrapping(SLURMJobService.scala:39)                                                                                               
        at fr.iscpif.gridscale.storage.Storage.wrapException(Storage.scala:77)                                                                                                                                 
        at fr.iscpif.gridscale.storage.Storage.wrapException$(Storage.scala:74)                                                                                                                                
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.wrapException(SLURMJobService.scala:39)                                                                                               
        at fr.iscpif.gridscale.ssh.SSHStorage.rmFileWithClient(SSHStorage.scala:121)                                                                                                                           
        at fr.iscpif.gridscale.ssh.SSHStorage.rmFileWithClient$(SSHStorage.scala:120)                                                                                                                          
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.rmFileWithClient(SLURMJobService.scala:39)                                                                                            
        at fr.iscpif.gridscale.slurm.SLURMJobService.$anonfun$delete$2(SLURMJobService.scala:109)                                                                                                              
        at fr.iscpif.gridscale.slurm.SLURMJobService.$anonfun$delete$2$adapted(SLURMJobService.scala:108)                                                                                                      
        at fr.iscpif.gridscale.ssh.SSHHost.$anonfun$withSftpClient$1(SSHHost.scala:51)                                                                                                                         
        at fr.iscpif.gridscale.ssh.SSHConnectionCache.withConnection(SSHConnectionCache.scala:27)                                                                                                              
        at fr.iscpif.gridscale.ssh.SSHConnectionCache.withConnection$(SSHConnectionCache.scala:25)                                                                                                             
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.withConnection(SLURMJobService.scala:39)                                                                                              
        at fr.iscpif.gridscale.ssh.SSHHost.withSftpClient(SSHHost.scala:49)                                                                                                                                    
        at fr.iscpif.gridscale.ssh.SSHHost.withSftpClient$(SSHHost.scala:48)                                                                                                                                   
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.withSftpClient(SLURMJobService.scala:39)                                                                                              
        at fr.iscpif.gridscale.slurm.SLURMJobService.$anonfun$delete$1(SLURMJobService.scala:108)                                                                                                              
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)                                                                                                                              
        at scala.util.Try$.apply(Try.scala:209)                                                                                                                                                                
        at fr.iscpif.gridscale.slurm.SLURMJobService.delete(SLURMJobService.scala:107)                                                                                                                         
        at fr.iscpif.gridscale.slurm.SLURMJobService.delete$(SLURMJobService.scala:106)                                                                                                                        
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.delete(SLURMJobService.scala:39)                                                                                                      
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.delete(SLURMJobService.scala:39)                                                                                                      
        at org.openmole.plugin.environment.gridscale.GridScaleJobService._delete(GridScaleJobService.scala:31)                                                                                                 
        at org.openmole.plugin.environment.gridscale.GridScaleJobService._delete$(GridScaleJobService.scala:31)                                                                                                
        at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1._delete(SLURMEnvironment.scala:96)                                                                                                   
        at org.openmole.plugin.environment.batch.jobservice.JobService.delete(JobService.scala:44)                                                                                                             
        at org.openmole.plugin.environment.batch.jobservice.JobService.delete$(JobService.scala:43)
        at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1.delete(SLURMEnvironment.scala:96)
        at org.openmole.plugin.environment.batch.jobservice.BatchJob.kill(BatchJob.scala:51)
        at org.openmole.plugin.environment.batch.jobservice.BatchJob.kill$(BatchJob.scala:49)
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$2.org$openmole$plugin$environment$batch$jobservice$BatchJobId$$super$kill(SLURMJobService.scala:66)
        at org.openmole.plugin.environment.batch.jobservice.BatchJobId.kill(BatchJobId.scala:26)
        at org.openmole.plugin.environment.batch.jobservice.BatchJobId.kill$(BatchJobId.scala:26)
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$2.kill(SLURMJobService.scala:66)
        at org.openmole.plugin.environment.batch.refresh.KillerActor$.$anonfun$receive$1(KillerActor.scala:30)
        at org.openmole.plugin.environment.batch.refresh.KillerActor$.$anonfun$receive$1$adapted(KillerActor.scala:29)
        at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken(UsageControl.scala:28)
        at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken$(UsageControl.scala:26)
        at org.openmole.plugin.environment.batch.control.LimitedAccess.tryWithToken(LimitedAccess.scala:26)
        at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken(BatchService.scala:28)
        at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken$(BatchService.scala:28)
        at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1.tryWithToken(SLURMEnvironment.scala:96)
        at org.openmole.plugin.environment.batch.refresh.KillerActor$.receive(KillerActor.scala:29)
        at org.openmole.plugin.environment.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:51)
        at org.openmole.plugin.environment.batch.refresh.JobManager$.$anonfun$dispatch$1(JobManager.scala:57)
        at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:21)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)


```

**Comment by jopasserat** [comment]
Can you reproduce on:
 - a simple `SSHEnvironment`?
 - the `EGIEnvironment`?

**Comment by reyman** [comment]
I have the same type of error with `SSHEnvironment` on Zebulon. I'm waiting the resbumission

```
juin 02, 2017 5:36:32 PM org.openmole.plugin.environment.batch.storage.StorageService $anonfun$mkRootDir$5                                                                                                     
PRÉCIS: Error creating base directory /home/rey/.openmole/.tmp/ssh/                                                                                                                                            
java.io.IOException: Error make dir /home/rey/.openmole/.tmp on org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1@64f66b4c                                                                         
        at fr.iscpif.gridscale.storage.Storage.errorWrapping(Storage.scala:72)                                                                                                                                 
        at fr.iscpif.gridscale.storage.Storage.errorWrapping$(Storage.scala:72)                       
```

**Comment by reyman** [comment]
Actually i could not work with OpenMOLE at all :( 

![selection_016](https://user-images.githubusercontent.com/466329/26867932-715b05c4-4b67-11e7-850b-16af42e5beae.jpg)

I have also problem to authorize my certificate p12 with dev version (same password which work on another instance) on egi, don't know why;

**Comment by romainreuillon** [comment]
The problem is the NPE, it is linked to the GamaTask I think....

**Comment by reyman** [comment]
Not totally sure, the gamaTask using Voronoi very simple model work well using localEnvironment but not using SLURM.

**Comment by romainreuillon** [comment]
For some some reasone the defautMap here:
 https://github.com/openmole/openmole/blob/dev/openmole/core/org.openmole.core.workflow/src/main/scala/org/openmole/core/workflow/tools/DefaultSet.scala#L43

is not properly instantiated after deserialisation...

**Comment by romainreuillon** [comment]
I reproduce the error, I am fixing it...

**Comment by romainreuillon** [comment]
This is caused by a regression in scala 2.12: https://issues.scala-lang.org/browse/SI-10075

**Comment by reyman** [comment]
Great, i'm happy to know that i'm not crazy finally :) :+1:

**Comment by romainreuillon** [comment]
Could you test with 03d296170eb7d4896ea9d77ea8714fae5ec0fe37

**Comment by reyman** [comment]
Yes, i test that.

**Comment by reyman** [comment]
Yep, it works/finish on SLURM :+1: 

Some errors appear in console at the end of experiment : 

```
juin 07, 2017 3:25:07 PM org.openmole.plugin.environment.batch.refresh.KillerActor$ receive                                                
PRÉCIS: Could not kill job.                                                                                                                
fr.iscpif.gridscale.ssh.SSHException$NoSuchFileException: rm /gpfs1/home/2017016/sreyco01/.openmole/.tmp/ssh/openmole-5cd44822-d39d-4cb7-ab
a0-2d13241e3afe/tmp/1496841794726/61e03919-1efd-42ec-8612-315b7563b26a/01d99159-22b6-45a1-85f3-7b7795ead5a4.slurm: No such file            
        at fr.iscpif.gridscale.ssh.SSHStorage.errorWrapping(SSHStorage.scala:78)                                                           
        at fr.iscpif.gridscale.ssh.SSHStorage.errorWrapping$(SSHStorage.scala:75)                                                          
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.errorWrapping(SLURMJobService.scala:39)                           
        at fr.iscpif.gridscale.storage.Storage.wrapException(Storage.scala:77)                                                             
        at fr.iscpif.gridscale.storage.Storage.wrapException$(Storage.scala:74)                                                            
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.wrapException(SLURMJobService.scala:39)                           
        at fr.iscpif.gridscale.ssh.SSHStorage.rmFileWithClient(SSHStorage.scala:121)                                                       
        at fr.iscpif.gridscale.ssh.SSHStorage.rmFileWithClient$(SSHStorage.scala:120)                                                      
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.rmFileWithClient(SLURMJobService.scala:39)                        
        at fr.iscpif.gridscale.slurm.SLURMJobService.$anonfun$delete$2(SLURMJobService.scala:109)                                          
        at fr.iscpif.gridscale.slurm.SLURMJobService.$anonfun$delete$2$adapted(SLURMJobService.scala:108)                                  
        at fr.iscpif.gridscale.ssh.SSHHost.$anonfun$withSftpClient$1(SSHHost.scala:51)                                                     
        at fr.iscpif.gridscale.ssh.SSHConnectionCache.withConnection(SSHConnectionCache.scala:27)                                          
        at fr.iscpif.gridscale.ssh.SSHConnectionCache.withConnection$(SSHConnectionCache.scala:25)                                         
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.withConnection(SLURMJobService.scala:39)                          
        at fr.iscpif.gridscale.ssh.SSHHost.withSftpClient(SSHHost.scala:49)                                                                
        at fr.iscpif.gridscale.ssh.SSHHost.withSftpClient$(SSHHost.scala:48)                                                               
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.withSftpClient(SLURMJobService.scala:39)     
        at fr.iscpif.gridscale.slurm.SLURMJobService.$anonfun$delete$1(SLURMJobService.scala:108)                     
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)                                     
        at scala.util.Try$.apply(Try.scala:209)                                                                       
        at fr.iscpif.gridscale.slurm.SLURMJobService.delete(SLURMJobService.scala:107)                                
        at fr.iscpif.gridscale.slurm.SLURMJobService.delete$(SLURMJobService.scala:106)                               
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.delete(SLURMJobService.scala:39)        
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.delete(SLURMJobService.scala:39)        
        at org.openmole.plugin.environment.gridscale.GridScaleJobService._delete(GridScaleJobService.scala:31)   
        at org.openmole.plugin.environment.gridscale.GridScaleJobService._delete$(GridScaleJobService.scala:31)  
        at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1._delete(SLURMEnvironment.scala:96)     
        at org.openmole.plugin.environment.batch.jobservice.JobService.delete(JobService.scala:44)               
        at org.openmole.plugin.environment.batch.jobservice.JobService.delete$(JobService.scala:43)              
        at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1.delete(SLURMEnvironment.scala:96)      
        at org.openmole.plugin.environment.batch.jobservice.BatchJob.kill(BatchJob.scala:51)                 
        at org.openmole.plugin.environment.batch.jobservice.BatchJob.kill$(BatchJob.scala:49)     
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$2.org$openmole$plugin$environment$batch$jobservice$BatchJobId$$super
$kill(SLURMJobService.scala:66)                                                                  
        at org.openmole.plugin.environment.batch.jobservice.BatchJobId.kill(BatchJobId.scala:26) 
        at org.openmole.plugin.environment.batch.jobservice.BatchJobId.kill$(BatchJobId.scala:26)
        at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$2.kill(SLURMJobService.scala:66)
        at org.openmole.plugin.environment.batch.refresh.KillerActor$.$anonfun$receive$1(KillerActor.scala:30)
        at org.openmole.plugin.environment.batch.refresh.KillerActor$.$anonfun$receive$1$adapted(KillerActor.scala:29)
        at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken(UsageControl.scala:28)
        at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken$(UsageControl.scala:26)
        at org.openmole.plugin.environment.batch.control.LimitedAccess.tryWithToken(LimitedAccess.scala:26)
        at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken(BatchService.scala:28)
        at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken$(BatchService.scala:28)
        at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1.tryWithToken(SLURMEnvironment.scala:96)
        at org.openmole.plugin.environment.batch.refresh.KillerActor$.receive(KillerActor.scala:29)
        at org.openmole.plugin.environment.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:51)
        at org.openmole.plugin.environment.batch.refresh.JobManager$.$anonfun$dispatch$1(JobManager.scala:57)
        at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:21)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by romainreuillon** [comment]
This error is armless, great that it works.
