### ISSUE TITLE
error make dir with SGE

### ISSUE THREAD

**Issue by gnoubi** [openmole/openmole#217]
Hi, 

There is an error with SGE. 

The simulation was running and achieving well. But data retrieve make an error

best
nicolas

```
Error		Date	Level
open failed	53	21/6/2017, 22:20:56	DEBUG
read /Work/Users/nmarilleau/openmole-299698f7-9023-400c-89c6-c677306b970f/tmp/1498076333146/f3aac890-8e2d-4fbf-8bc7-80fa9d0f7e41/result_7dd52230-66ab-46f6-ac03-18ab73687142.bin on org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1@76fd7b0f: No such file	1	21/6/2017, 22:20:21	DEBUG
```

```
fr.iscpif.gridscale.ssh.SSHException$NoSuchFileException: rm /Work/Users/nmarilleau/openmole-299698f7-9023-400c-89c6-c677306b970f/tmp/1498076333146/a7aaf1b5-45f2-4de5-a4eb-104616f7b87e/job77f96291-a2ed-40eb-82c4-8a6d8bf50cae.sge: No such file
	at fr.iscpif.gridscale.ssh.SSHStorage.errorWrapping(SSHStorage.scala:78)
	at fr.iscpif.gridscale.ssh.SSHStorage.errorWrapping$(SSHStorage.scala:75)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$1.errorWrapping(SGEJobService.scala:39)
	at fr.iscpif.gridscale.storage.Storage.wrapException(Storage.scala:77)
	at fr.iscpif.gridscale.storage.Storage.wrapException$(Storage.scala:74)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$1.wrapException(SGEJobService.scala:39)
	at fr.iscpif.gridscale.ssh.SSHStorage.rmFileWithClient(SSHStorage.scala:121)
	at fr.iscpif.gridscale.ssh.SSHStorage.rmFileWithClient$(SSHStorage.scala:120)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$1.rmFileWithClient(SGEJobService.scala:39)
	at fr.iscpif.gridscale.sge.SGEJobService.$anonfun$delete$2(SGEJobService.scala:109)
	at fr.iscpif.gridscale.ssh.SSHHost.$anonfun$withSftpClient$1(SSHHost.scala:51)
	at fr.iscpif.gridscale.ssh.SSHConnectionCache.withConnection(SSHConnectionCache.scala:27)
	at fr.iscpif.gridscale.ssh.SSHConnectionCache.withConnection$(SSHConnectionCache.scala:25)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$1.withConnection(SGEJobService.scala:39)
	at fr.iscpif.gridscale.ssh.SSHHost.withSftpClient(SSHHost.scala:49)
	at fr.iscpif.gridscale.ssh.SSHHost.withSftpClient$(SSHHost.scala:48)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$1.withSftpClient(SGEJobService.scala:39)
	at fr.iscpif.gridscale.sge.SGEJobService.$anonfun$delete$1(SGEJobService.scala:108)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at fr.iscpif.gridscale.sge.SGEJobService.delete(SGEJobService.scala:107)
	at fr.iscpif.gridscale.sge.SGEJobService.delete$(SGEJobService.scala:106)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$1.delete(SGEJobService.scala:39)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$1.delete(SGEJobService.scala:39)
	at org.openmole.plugin.environment.gridscale.GridScaleJobService._delete(GridScaleJobService.scala:31)
	at org.openmole.plugin.environment.gridscale.GridScaleJobService._delete$(GridScaleJobService.scala:31)
	at org.openmole.plugin.environment.sge.SGEEnvironment$$anon$1._delete(SGEEnvironment.scala:79)
	at org.openmole.plugin.environment.batch.jobservice.JobService.delete(JobService.scala:44)
	at org.openmole.plugin.environment.batch.jobservice.JobService.delete$(JobService.scala:43)
	at org.openmole.plugin.environment.sge.SGEEnvironment$$anon$1.delete(SGEEnvironment.scala:79)
	at org.openmole.plugin.environment.batch.jobservice.BatchJob.kill(BatchJob.scala:51)
	at org.openmole.plugin.environment.batch.jobservice.BatchJob.kill$(BatchJob.scala:49)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$2.org$openmole$plugin$environment$batch$jobservice$BatchJobId$$super$kill(SGEJobService.scala:61)
	at org.openmole.plugin.environment.batch.jobservice.BatchJobId.kill(BatchJobId.scala:26)
	at org.openmole.plugin.environment.batch.jobservice.BatchJobId.kill$(BatchJobId.scala:26)
	at org.openmole.plugin.environment.sge.SGEJobService$$anon$2.kill(SGEJobService.scala:61)
	at org.openmole.plugin.environment.batch.refresh.KillerActor$.$anonfun$receive$1(KillerActor.scala:30)
	at org.openmole.plugin.environment.batch.refresh.KillerActor$.$anonfun$receive$1$adapted(KillerActor.scala:29)
	at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken(UsageControl.scala:28)
	at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken$(UsageControl.scala:26)
	at org.openmole.plugin.environment.batch.control.LimitedAccess.tryWithToken(LimitedAccess.scala:26)
	at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken(BatchService.scala:28)
	at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken$(BatchService.scala:28)
	at org.openmole.plugin.environment.sge.SGEEnvironment$$anon$1.tryWithToken(SGEEnvironment.scala:79)
	at org.openmole.plugin.environment.batch.refresh.KillerActor$.receive(KillerActor.scala:29)
	at org.openmole.plugin.environment.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:51)
	at org.openmole.plugin.environment.batch.refresh.JobManager$.$anonfun$dispatch$1(JobManager.scala:57)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:21)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

juin 21, 2017 11:01:53 PM org.openmole.plugin.environment.batch.environment.BatchJobWatcher update
```

**Comment by jopasserat** [comment]
Hi @gnoubi 

I could reproduce on other SSH based environments as well.
This bug was fixed by @romainreuillon in a master but we didn't redeploy to the website (spoiler alert) which is undergoing a complete redesign for the 7.0 release.

Can you try with the archive in the pre-release?https://github.com/openmole/openmole/releases/download/v7.0-RC5/openmole.tar.gz
