### ISSUE TITLE
Out of heap memory in fetchOutputFiles

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#22]
I had a running OpenMOLE script which evaluates some experiment results stored on disk using a ScalaTask that executes an external process and writes these to a CSV file using the ```AppendToFileHook```. Then I changed the script to use ```AppendToCSVFileHook```. It was working fine. Now suddenly when I run the script I get the following error after some time:
```
Apr 15, 2015 6:20:34 PM org.openmole.core.workflow.mole.SubMoleExecution finalState
SEVERE: Error in user job execution for capsule calculateOverlap, job state is FAILED.
org.openmole.core.exception.InternalProcessingError: Error for context values in calculateOverlap {oMSeed=3013629829646801551, outSeg=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz, srcId=1003, tgtId=1004, tgtSeg=/Users/as12312/Data/Registrations/MAC2012/data/Labels/1004_3_glm.nii.gz}
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:97)
        at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:35)
        at org.openmole.core.workflow.task.Task$class.perform(Task.scala:46)
        at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:35)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:99)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.IdentityHashMap.resize(IdentityHashMap.java:471)
        at java.util.IdentityHashMap.put(IdentityHashMap.java:440)
        at org.openmole.core.tools.obj.ClassUtils$ObjectClassDecorator.flatObjectGraph(ClassUtils.scala:120)
        at org.openmole.plugin.task.external.ExternalTask$$anonfun$contextFiles$1$2.apply(ExternalTask.scala:121)
        at org.openmole.plugin.task.external.ExternalTask$$anonfun$contextFiles$1$2.apply(ExternalTask.scala:121)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at org.openmole.plugin.task.external.ExternalTask$class.contextFiles$1(ExternalTask.scala:121)
        at org.openmole.plugin.task.external.ExternalTask$class.fetchOutputFiles(ExternalTask.scala:124)
        at org.openmole.plugin.task.scala.ScalaTask.fetchOutputFiles(ScalaTask.scala:35)
        at org.openmole.plugin.task.jvm.JVMLanguageTask$class.process(JVMLanguageTask.scala:45)
        at org.openmole.plugin.task.scala.ScalaTask.process(ScalaTask.scala:35)
        at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
        at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
        ... 9 more

org.openmole.core.exception.InternalProcessingError: Error for context values in calculateOverlap {oMSeed=3013629829646801551, outSeg=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz, srcId=1003, tgtId=1004, tgtSeg=/Users/as12312/Data/Registrations/MAC2012/data/Labels/1004_3_glm.nii.gz}
  at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:97)
  at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:35)
  at org.openmole.core.workflow.task.Task$class.perform(Task.scala:46)
  at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:35)
  at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:99)
  at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
  at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
  at java.util.IdentityHashMap.resize(IdentityHashMap.java:471)
  at java.util.IdentityHashMap.put(IdentityHashMap.java:440)
  at org.openmole.core.tools.obj.ClassUtils$ObjectClassDecorator.flatObjectGraph(ClassUtils.scala:120)
  at org.openmole.plugin.task.external.ExternalTask$$anonfun$contextFiles$1$2.apply(ExternalTask.scala:121)
  at org.openmole.plugin.task.external.ExternalTask$$anonfun$contextFiles$1$2.apply(ExternalTask.scala:121)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.Iterator$class.foreach(Iterator.scala:750)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
  at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
  at org.openmole.plugin.task.external.ExternalTask$class.contextFiles$1(ExternalTask.scala:121)
  at org.openmole.plugin.task.external.ExternalTask$class.fetchOutputFiles(ExternalTask.scala:124)
  at org.openmole.plugin.task.scala.ScalaTask.fetchOutputFiles(ScalaTask.scala:35)
  at org.openmole.plugin.task.jvm.JVMLanguageTask$class.process(JVMLanguageTask.scala:45)
  at org.openmole.plugin.task.scala.ScalaTask.process(ScalaTask.scala:35)
  at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
  at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
  at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
  ... 9 more
```

I have since reverted not only my script to the previous version where it didn't use the CSV file hook, but also tried earlier builds of the OpenMOLE master branch. Note that the workflow execution is stuck before any of the tasks which have a hook in place is executed. Does the error suggest an endless recursion/loop in fetchOutputFiles?

I now tried with OpenMOLE master branch commit c6905c8 which works fine. One of the later commits did not work and raise this error. Seems there was a bug introduced at some point.

**Comment by romainreuillon** [comment]
Have you pulled the latest changes. I corrected a very similar bug just today.

**Comment by romainreuillon** [comment]
With this commit: b1d42f0f52a3a72d277a65a46a183bd99eb21077.

**Comment by schuhschuh** [comment]
I am running the script with commit 06446158 right now, the merge commit that followed this fix, but I get the same error.

**Comment by romainreuillon** [comment]
From your stack, it is obvious you did... Can you just check which object is being constantly added with a dirty println in the while loop?

**Comment by schuhschuh** [comment]
Can you point me to the while loop you are referring to?

**Comment by romainreuillon** [comment]
In this loop, OpenMOLE is trying to traverse all the object graph to check which file the output context is referencing and so shouldn't be deleted. The loop is in the ClassUtils file of the core.tools.obj package. From line 110.

**Comment by schuhschuh** [comment]
Ok, found it and will add it in the current HEAD of master. (FYI 672a5c1fb still worked as well)

**Comment by romainreuillon** [comment]
(Not quite is was buggy because it was using "structural" equality instead of identity, which what we need to go through the object graph by reflexion and because of that it was also throwing ConcurentModificationException in multithreaded context)

**Comment by romainreuillon** [comment]
I knew this code was touchy when I coded it, but I'm sure we can make it work. I have to go, I'll check the output you get in a few hours.

**Comment by schuhschuh** [comment]
Here's the output of
```scala
println("ClassUtils.scala: ObjectClassDecorator(o=" + o.toString + ": cur=" + cur.toString)
```
inside the while loop right after ```val cur = ...```.

```
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=0.40588291428571427,0.5859643611111112,0.4542630044776119
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=0
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=[C@3de75353
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=diceRow: java.lang.String
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=java.lang.String
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=List()
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=class java.lang.String
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=None
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=diceRow
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=1656635571
ClassUtils.scala: ObjectClassDecorator(o=diceRow=0.40588291428571427,0.5859643611111112,0.4542630044776119: cur=[C@6307ed6a
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=0.2629126326530613,0.42919217500000006,0.3075847485074626
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=0
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=[C@5750148e
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=jaccRow: java.lang.String
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=java.lang.String
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=List()
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=class java.lang.String
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=None
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=jaccRow
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=-1837369725
ClassUtils.scala: ObjectClassDecorator(o=jaccRow=0.2629126326530613,0.42919217500000006,0.3075847485074626: cur=[C@2e44ec71
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=oMSeed=-8449484863345444363
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=-8449484863345444363
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=oMSeed: Long
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=Long
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=1264213713
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=Long
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=0
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=[C@23961dda
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=oMSeed
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=-1043447473
ClassUtils.scala: ObjectClassDecorator(o=oMSeed=-8449484863345444363: cur=[C@30953fbe
ClassUtils.scala: ObjectClassDecorator(o=outSeg=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz: cur=outSeg=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz
ClassUtils.scala: ObjectClassDecorator(o=outSeg=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz: cur=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz
ClassUtils.scala: ObjectClassDecorator(o=outSeg=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz: cur=/Users/as12312/Data/Registrations/MAC2012/output/labels/affine/1003-1004_3_glm.nii.gz
Apr 15, 2015 6:56:10 PM org.openmole.core.workflow.mole.SubMoleExecution finalState
SEVERE: Error in user job execution for capsule calculateOverlap, job state is FAILED.
```

**Comment by schuhschuh** [comment]
>  I have to go, I'll check the output you get in a few hours.

No problem. I actually gotta go as well.

**Comment by romainreuillon** [comment]
Did you get the java heap space? 

From what I see, it doesn't seems to be looping indefinitely, it just gets too big...

**Comment by romainreuillon** [comment]
After thinking a bit about it, I think that going through the object graph is too memory consuming, so lets search only the context variables for files.

It should work ok now.

**Comment by schuhschuh** [comment]
Indeed, it seems this problem is resolved.
