### ISSUE TITLE
Better handle full storage over SSH

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#220]
Writing to a full storage on an SSH based environment returns the following stacktrace:

```
org.openmole.plugin.environment.batch.refresh.JobRemoteExecutionException: Fatal exception thrown during the execution of the job execution on the execution node
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$.getResult(GetResultActor.scala:72)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$.$anonfun$receive$1(GetResultActor.scala:49)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$.$anonfun$receive$1$adapted(GetResultActor.scala:47)
	at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken(UsageControl.scala:28)
	at org.openmole.plugin.environment.batch.control.UsageControl.tryWithToken$(UsageControl.scala:26)
	at org.openmole.plugin.environment.batch.control.LimitedAccess.tryWithToken(LimitedAccess.scala:26)
	at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken(BatchService.scala:28)
	at org.openmole.plugin.environment.batch.environment.BatchService.tryWithToken$(BatchService.scala:28)
	at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$2.tryWithToken(SSHPersistentStorage.scala:64)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$.receive(GetResultActor.scala:47)
	at org.openmole.plugin.environment.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:50)
	at org.openmole.plugin.environment.batch.refresh.JobManager$.$anonfun$dispatch$1(JobManager.scala:57)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:21)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /vol/biomedic/users/jpassera/openmole_data2/.tmp/ssh/openmole-13b77cce-b2be-45c0-bc0a-20f5de27e868/tmp/1498497615854/979b28c1-1a04-4593-b610-2e3f372a2ddd/1982a865-8f4b-4410-afcc-c11c259b8143/.tmp/dfce0e26-e995-4581-b9ca-79dc7a96ffca/filefd8b157e-4d5d-44d1-9006-9b02191d2188.bin
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:837)
	at org.openmole.tool.file.FilePackage$FileDecorator.realFile(package.scala:73)
	at org.openmole.tool.file.FilePackage$FileDecorator.mode_$eq(package.scala:224)
	at org.openmole.core.communication.message.package$ReplicatedFile$.download(package.scala:93)
	at org.openmole.runtime.Runtime.getReplicatedFile$1(Runtime.scala:93)
	at org.openmole.runtime.Runtime.$anonfun$apply$5(Runtime.scala:111)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.openmole.runtime.Runtime.apply(Runtime.scala:110)
	at org.openmole.runtime.SimExplorer$.$anonfun$run$2(SimExplorer.scala:99)
	at scala.Option.foreach(Option.scala:257)
	at org.openmole.runtime.SimExplorer$.run(SimExplorer.scala:81)
	at org.openmole.runtime.SimExplorer.run(SimExplorer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openmole.launcher.Launcher.main(Launcher.java:129)
```

We're missing a previous exception reporting that the file in the `NoSuchFile` was not created properly.
_(This might be tricky to untangle from copy errors due to dropped connections)_

**Comment by romainreuillon** [comment]
Totally agree, lets try to improve all case of error when we redesign the envs and port them to the monadic version of gridscale.
