### ISSUE TITLE
Jobs completing on PBS cluster but not returning results

### ISSUE THREAD

**Issue by gdower** [openmole/openmole#225]
Hello,

I am attempting to setup OpenMOLE 7.0-RC4 to run on a PBS (Version: 6.1.1.1 Commit: 22f28343b8ee83b1234479b20224353f6c2db317) cluster. The jobs get submitted to the PBS queue and show PBS state C for complete, but in the environment pane I get the debug message "Unrecognized state C," and no results return:

```
java.lang.RuntimeException: Unrecognized state C
	at fr.iscpif.gridscale.pbs.PBSJobService$class.translateStatus(PBSJobService.scala:101)
	at org.openmole.plugin.environment.pbs.PBSJobService$$anon$1.translateStatus(PBSJobService.scala:39)
	at fr.iscpif.gridscale.pbs.PBSJobService$$anonfun$state$1.apply(PBSJobService.scala:78)
	at fr.iscpif.gridscale.pbs.PBSJobService$$anonfun$state$1.apply(PBSJobService.scala:64)
	at fr.iscpif.gridscale.ssh.SSHConnectionCache$class.withConnection(SSHConnectionCache.scala:27)
	at org.openmole.plugin.environment.pbs.PBSJobService$$anon$1.withConnection(PBSJobService.scala:39)
	at fr.iscpif.gridscale.pbs.PBSJobService$class.state(PBSJobService.scala:64)
	at org.openmole.plugin.environment.pbs.PBSJobService$$anon$1.state(PBSJobService.scala:39)
	at org.openmole.plugin.environment.pbs.PBSJobService$$anon$1.state(PBSJobService.scala:39)
	at org.openmole.plugin.environment.gridscale.GridScaleJobService$class._state(GridScaleJobService.scala:30)
	at org.openmole.plugin.environment.pbs.PBSEnvironment$$anon$1._state(PBSEnvironment.scala:86)
	at org.openmole.plugin.environment.batch.jobservice.JobService$$anonfun$state$1.apply(JobService.scala:41)
	at org.openmole.plugin.environment.batch.jobservice.JobService$$anonfun$state$1.apply(JobService.scala:41)
	at org.openmole.plugin.environment.batch.control.LimitedAccess$LimitedAccessToken.access(LimitedAccess.scala:37)
	at org.openmole.plugin.environment.batch.jobservice.JobService$class.state(JobService.scala:41)
	at org.openmole.plugin.environment.pbs.PBSEnvironment$$anon$1.state(PBSEnvironment.scala:86)
	at org.openmole.plugin.environment.batch.jobservice.BatchJob$class.updateState(BatchJob.scala:57)
	at org.openmole.plugin.environment.pbs.PBSJobService$$anon$2.org$openmole$plugin$environment$batch$jobservice$BatchJobId$$super$updateState(PBSJobService.scala:63)
	at org.openmole.plugin.environment.batch.jobservice.BatchJobId$class.updateState(BatchJobId.scala:27)
	at org.openmole.plugin.environment.pbs.PBSJobService$$anon$2.updateState(PBSJobService.scala:63)
	at org.openmole.plugin.environment.batch.refresh.RefreshActor$$anonfun$receive$1.apply(RefreshActor.scala:35)
	at org.openmole.plugin.environment.batch.refresh.RefreshActor$$anonfun$receive$1.apply(RefreshActor.scala:32)
	at org.openmole.plugin.environment.batch.control.UsageControl$class.tryWithToken(UsageControl.scala:28)
	at org.openmole.plugin.environment.batch.control.LimitedAccess.tryWithToken(LimitedAccess.scala:26)
	at org.openmole.plugin.environment.batch.environment.BatchService$class.tryWithToken(BatchService.scala:28)
	at org.openmole.plugin.environment.pbs.PBSEnvironment$$anon$1.tryWithToken(PBSEnvironment.scala:86)
	at org.openmole.plugin.environment.batch.refresh.RefreshActor$.receive(RefreshActor.scala:32)
	at org.openmole.plugin.environment.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:49)
	at org.openmole.plugin.environment.batch.refresh.JobManager$$anonfun$dispatch$1.apply$mcV$sp(JobManager.scala:57)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:21)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I don't see a state C at lines 99-101 of https://github.com/openmole/gridscale/blob/master/modules/gridscale-pbs/src/main/scala/fr/iscpif/gridscale/pbs/PBSJobService.scala:

```
  def translateStatus(retCode: Int, status: String) =
    status match {
      case "R" | "E" | "H" | "S" ⇒ Running
      case "Q" | "W" | "T"       ⇒ Submitted
      case _                     ⇒ throw new RuntimeException("Unrecognized state " + status)
    }
```

The submitted jobs dwindle down towards 0 and then get resubmitted by OpenMOLE. 

Here's a qstat from PBS:

```
Job ID                    Name             User            Time Use S Queue
------------------------- ---------------- --------------- -------- - -----
940.cam1                   ...ff1480160.pbs pi              00:00:00 C batch          
941.cam1                   ...c839be65d.pbs pi              00:00:00 C batch          
942.cam1                   ...79cd988b0.pbs pi              00:00:00 C batch          
943.cam1                   ...df3ce1fb5.pbs pi              00:00:00 C batch          
944.cam1                   ...d964870d9.pbs pi              00:00:00 C batch          
945.cam1                   ...4024c354f.pbs pi              00:00:00 C batch          
946.cam1                   ...f73b7faae.pbs pi              00:00:00 C batch          
947.cam1                   ...ee767a09f.pbs pi              00:00:00 C batch          
948.cam1                   ...04159a6ea.pbs pi              00:00:00 C batch          
949.cam1                   ...f929e6c7d.pbs pi              00:00:00 C batch          
950.cam1                   ...6ad74d7ea.pbs pi              00:00:00 C batch          
951.cam1                   ...6ccd91227.pbs pi              00:00:00 C batch          
952.cam1                   ...14fdf6121.pbs pi              00:00:00 C batch          
953.cam1                   ...2a4c4126a.pbs pi              00:00:00 C batch          
954.cam1                   ...0f3f8d8f6.pbs pi              00:00:00 C batch          
955.cam1                   ...78362160f.pbs pi              00:00:00 C batch          
956.cam1                   ...14fd22463.pbs pi              00:00:00 C batch          
957.cam1                   ...961d37d22.pbs pi              00:00:00 C batch          
958.cam1                   ...d70da99ba.pbs pi              00:00:00 C batch
```

Here's the test code that I am using, which is the NetLogo fire example modified to run on a cluster:

```
val env =
  PBSEnvironment(
    "pi",
    "172.27.8.1",
    port=1022
  )

val density = Val[Double]
val seed = Val[Int]
val burned = Val[Double]

val cmds = 
  List(
    "random-seed ${seed}",
    "setup",
    "while [any? turtles] [go]"
  )

val fireTask =
  NetLogo6Task(workDirectory / "Fire.nlogo", cmds) set (
    inputs += seed,
    outputs += (seed, density),
    netLogoInputs += (density, "density"),
    netLogoOutputs += ("burned-trees", burned)
  )

val csvHook = CSVHook(workDirectory / "result.csv", density, burned, seed)

val exploration = 
  DirectSampling(
    evaluation = Replication(fireTask on env hook csvHook, seed, 10),
    sampling = density in (20.0 to 80.0 by 10.0)
  )

exploration
```

Please let me know if I an provide any additional debugging information. Thanks for your help!

**Comment by jopasserat** [comment]
You've spotted it right, we never encountered this state before so didn't handle it in GridScale :)
I'm closing this issue and moving the discussion to [GridScale's issue list](https://github.com/openmole/gridscale/issues/13) if you'd like to join there @gdower?
