### ISSUE TITLE
Type "int" not found error

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#23]
For some reason, the scala code generated for my ScalaTask contains an ```Array[int]``` type for my variables ```val tgtId = Val[Int]``` and ```val srcId = Val[Int]```. This occurs after preceding two parallel empty tasks which both have these variables as inputs and outputs.

```
<console>:13: error: not found: type int
              (_input_value_diceRow: Array[Double],_input_value_jaccRow: Array[Double],_input_value_oMSeed: Long,_input_value_srcId: Array[int],_input_value_tgtId: Array[int],_input_value_workDir: java.io.File) => {
```

**Comment by schuhschuh** [comment]
Here some more details where the error occurs:


```
Apr 16, 2015 1:58:01 AM org.openmole.core.workflow.mole.SubMoleExecution finalState
SEVERE: Error in user job execution for capsule writeOverlapToCsvEnd, job state is FAILED.
org.openmole.core.exception.InternalProcessingError: Error for context values in writeOverlapToCsvEnd {diceRow=[0.40588291428571427, 0.5859643611111112, 0.4542630044776119], jaccRow=[0.2629126326530613, 0.42919217500000006, 0.3075847485074626], oMSeed=-3610530535514446643, srcId=[1003, 1003], tgtId=[1004, 1004]}
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:97)
        at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:35)
        at org.openmole.core.workflow.task.Task$class.perform(Task.scala:46)
        at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:35)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:99)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.InternalProcessingError: Error compiling import org.openmole.plugin.task.jvm.JVMLanguageTask.newRNG
import org.openmole.plugin.task.jvm.JVMLanguageTask.newFile
import org.openmole.plugin.task.jvm.JVMLanguageTask.newDir

(_input_value_diceRow: Array[Double],_input_value_jaccRow: Array[Double],_input_value_oMSeed: Long,_input_value_srcId: Array[int],_input_value_tgtId: Array[int],_input_value_workDir: java.io.File) => {
    object input {
      var diceRow = _input_value_diceRow; var jaccRow = _input_value_jaccRow; var oMSeed = _input_value_oMSeed; var srcId = _input_value_srcId; var tgtId = _input_value_tgtId; var workDir = _input_value_workDir
    }
    import input._
    implicit lazy val oMRNG: util.Random = newRNG(oMSeed).toScala;
    
 val tgtId = input.tgtId.head
 val srcId = input.srcId.head
  
    
import scala.collection.JavaConversions.mapAsJavaMap
mapAsJavaMap(Map[String, Any](  "diceRow" -> diceRow, "jaccRow" -> jaccRow, "srcId" -> srcId, "tgtId" -> tgtId ))
    
}

        at org.openmole.plugin.task.scala.ScalaCompilation$$anonfun$compile$1.apply(ScalaCompilation.scala:33)
        at scala.util.Try$.apply(Try.scala:191)
        at org.openmole.plugin.task.scala.ScalaCompilation$class.compile(ScalaCompilation.scala:29)
        at org.openmole.plugin.task.scala.ScalaTask.compile(ScalaTask.scala:35)
        at org.openmole.plugin.task.scala.ScalaWrappedCompilation$class.function(ScalaWrappedCompilation.scala:67)
        at org.openmole.plugin.task.scala.ScalaTask.function(ScalaTask.scala:35)
        at org.openmole.plugin.task.scala.ScalaWrappedCompilation$$anonfun$6.apply(ScalaWrappedCompilation.scala:112)
        at org.openmole.plugin.task.scala.ScalaWrappedCompilation$$anonfun$6.apply(ScalaWrappedCompilation.scala:112)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
        at org.openmole.plugin.task.scala.ScalaWrappedCompilation$class.compiled(ScalaWrappedCompilation.scala:112)
        at org.openmole.plugin.task.scala.ScalaTask.compiled(ScalaTask.scala:35)
        at org.openmole.plugin.task.scala.ScalaWrappedCompilation$class.compiled(ScalaWrappedCompilation.scala:128)
        at org.openmole.plugin.task.scala.ScalaTask.compiled(ScalaTask.scala:35)
        at org.openmole.plugin.task.scala.ScalaTask.processCode(ScalaTask.scala:36)
        at org.openmole.plugin.task.jvm.JVMLanguageTask$class.process(JVMLanguageTask.scala:45)
        at org.openmole.plugin.task.scala.ScalaTask.process(ScalaTask.scala:35)
        at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
        at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
        ... 9 more
```

And here the offending parts of the OpenMOLE script (particularly ```writeOverlapToCsvEnd```):
```scala
val writeOverlapToCsvBegin = EmptyTask() set (
    name    := "writeOverlapToCsvBegin",
    inputs  += (tgtId, srcId, diceRow, jaccRow),
    outputs += (tgtId, srcId, diceRow, jaccRow)
  )

val writeDiceToCsv = EmptyTask() set (
    name    := "writeDiceToCsv",
    inputs  += (tgtId, srcId, diceRow),
    outputs += (tgtId, srcId, diceRow)
  ) hook (
    AppendToCSVFileHook(diceCsvPath, tgtId, srcId, diceRow) set (
      csvHeader := "target,source," + regions.mkString(","),
      singleRow := true
    )
  )

val writeJaccardToCsv = EmptyTask() set (
    name    := "writeJaccardToCsv",
    inputs  += (tgtId, srcId, jaccRow),
    outputs += (tgtId, srcId, jaccRow)
  ) hook (
    AppendToCSVFileHook(jaccCsvPath, tgtId, srcId, jaccRow) set (
      csvHeader := "target,source," + regions.mkString(","),
      singleRow := true
    )
  )

val writeOverlapToCsvEnd = ScalaTask(
  """
    | val tgtId = input.tgtId.head
    | val srcId = input.srcId.head
  """.stripMargin) set (
    name    := "writeOverlapToCsvEnd",
    inputs  += (tgtId.toArray, srcId.toArray, diceRow, jaccRow),
    outputs += (tgtId,         srcId,         diceRow, jaccRow)
  )

val writeOverlapToCsv = writeOverlapToCsvBegin -- (writeDiceToCsv, writeJaccardToCsv) -- writeOverlapToCsvEnd
```

**Comment by schuhschuh** [comment]
It appears to me this issue was introduced by [this change](https://github.com/openmole/openmole/commit/847101e086b9c2842b5d34c0b1c056718fe18a79#diff-4f08c92f4b5261a693e854ece1e97152R157) which is part of commit 847101e.

**Comment by schuhschuh** [comment]
I am curious why the ```toScalaNativeType``` function is even needed [here](https://github.com/openmole/openmole/blob/2e95e7c0d2904f9b32bec0a188ebf178d019d9ab/openmole/plugins/org.openmole.plugin.task.scala/src/main/scala/org/openmole/plugin/task/scala/ScalaWrappedCompilation.scala#L77). Is it not sufficient to use the ```Prototype.toString``` function as in the following?

```scala
${inputs.toSeq.map(i ⇒ prefix + i.toString).mkString(",")}
```

**Comment by romainreuillon** [comment]
Actually because OpenMOLE runs on the JVM it as to take native java type into account. So the function toScalaNativeType check if the type in the manifest is a native java type (int, double, float) and convert it to a native scala type so the scala compile is happy. It didn't take into account arrays though. It should be fixed now.

Note: the code I just committed is guaranteed 100% untested :)

**Comment by schuhschuh** [comment]
> the code I just committed is guaranteed 100% untested

Well done then ;) Works now, thanks!
