### ISSUE TITLE
StackOverflow execption when running Pi example from console

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#258]
When running the Pi example from the market place in console mode, OM (`dev` branch) crashes with a StackOverflow exception when gathering the results.

```shell
➜  next_openmole ./openmole --script ./Pi.oms
  ___                   __  __  ___  _     _____   _____
 / _ \ _ __   ___ _ __ |  \/  |/ _ \| |   | ____| |___  |
| | | | '_ \ / _ \ '_ \| |\/| | | | | |   |  _|      / /
| |_| | |_) |  __/ | | | |  | | |_| | |___| |___    / /
 \___/| .__/ \___|_| |_|_|  |_|\___/|_____|_____|  /_/
      |_|
    (Type :q to quit)
Error during script execution: 
org.openmole.core.exception.InternalProcessingError: Error for context values in org.openmole.core.workflow.tools.InputOutputCheck$@2f887b79 {pi=3.14944}
        at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:91)
        at org.openmole.core.expansion.FromContext$$anon$9.from(FromContext.scala:162)
        at org.openmole.core.workflow.mole.Hook.perform(Hook.scala:36)
        at org.openmole.core.workflow.mole.Hook.perform$(Hook.scala:32)
        at org.openmole.plugin.hook.display.ToStringHook.perform(ToStringHook.scala:43)
        at org.openmole.core.workflow.mole.SubMoleExecution.executeHook$1(SubMoleExecution.scala:133)
        at org.openmole.core.workflow.mole.SubMoleExecution.$anonfun$jobFinished$1(SubMoleExecution.scala:144)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at scala.collection.immutable.List.flatMap(List.scala:352)
        at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:144)
        at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:269)
        at org.openmole.core.workflow.mole.SubMoleExecution.stateChanged$2(SubMoleExecution.scala:228)
        at org.openmole.core.workflow.mole.SubMoleExecution.$anonfun$submit$6(SubMoleExecution.scala:231)
        at org.openmole.core.workflow.mole.SubMoleExecution.$anonfun$submit$6$adapted(SubMoleExecution.scala:231)
        at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:86)
        at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:90)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:103)
        at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:77)
        at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2$adapted(LocalExecutor.scala:73)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:73)
        at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:115)
        at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:127)
        at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:70)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StackOverflowError
        at scala.collection.Iterator.find(Iterator.scala:979)
        at scala.collection.Iterator.find$(Iterator.scala:978)
        at scala.collection.AbstractIterator.find(Iterator.scala:1417)
        at org.openmole.core.outputmanager.OutputManager$.findRedirect(OutputManager.scala:49)
        at org.openmole.core.outputmanager.OutputManager$.org$openmole$core$outputmanager$OutputManager$$redirectedOutput(OutputManager.scala:53)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.write(OutputManager.scala:67)
        at java.io.PrintStream.write(PrintStream.java:449)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1$adapted(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$.org$openmole$core$outputmanager$OutputManager$$redirectedOutput(OutputManager.scala:55)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.write(OutputManager.scala:67)
        at java.io.PrintStream.write(PrintStream.java:449)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1$adapted(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$.org$openmole$core$outputmanager$OutputManager$$redirectedOutput(OutputManager.scala:55)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.write(OutputManager.scala:67)
        at java.io.PrintStream.write(PrintStream.java:449)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1$adapted(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$.org$openmole$core$outputmanager$OutputManager$$redirectedOutput(OutputManager.scala:55)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.write(OutputManager.scala:67)
        at java.io.PrintStream.write(PrintStream.java:449)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.$anonfun$write$1$adapted(OutputManager.scala:67)
        at org.openmole.core.outputmanager.OutputManager$.org$openmole$core$outputmanager$OutputManager$$redirectedOutput(OutputManager.scala:55)
        at org.openmole.core.outputmanager.OutputManager$$anon$1.write(OutputManager.scala:67)
```

The same workflow **runs fine in the WebUI**.

Note that this is a regression that **doesn't happen with the stable release (7.1)**.

**Comment by romainreuillon** [comment]
fixed in 42ce1a6e51d7c7aa2ef2a797222c4c6b7b30e6dd
