### ISSUE TITLE
Netlogo task: input parameters of type file should be passed with quotes 

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#278]
When running a Netlogo task which receives a `Val[File]` as an input parameter, the NetLogo task fails with the following error

```
org.openmole.core.exception.InternalProcessingError: Error for context values in org.openmole.core.workflow.tools.InputOutputCheck$@70f6e344 {advertisementDuration=6.0, advertisementProportionPerStep=0.04, averagepathlength=4.0507, diameter=6.0, durationProactive=5.0, durationSeek=5.0, initialProportionKnowledgeable=0.03, nedges=4000.0, networkfile=/home/sam/.openmole/sam440/.tmp/945258ea-ec45-4d1e-86f4-9ce0d8ab76b6/executionc2c08667-06aa-4b82-a488-9e012976d052/containers/ab3d9191-40d3-4496-b4da-b87c074ae702/nnpchipndbmjkkbaokheanlibdjbmaaj/ROOT/tmp/network_generated.net, nvertices=1000.0, openmole$seed=6497870242201176563, probabilityLinkMeeting=0.42, proportionCurious=0.15, proportionEnthusiastic=0.15, proportionSupporters=0.08, seed=0, transitivity=0.2376, withGui=false}
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:91)
	at org.openmole.core.expansion.FromContext$$anon$9.from(FromContext.scala:163)
	at org.openmole.core.workflow.task.Task.perform(Task.scala:64)
	at org.openmole.core.workflow.task.Task.perform$(Task.scala:62)
	at org.openmole.plugin.task.netlogo6.NetLogo6Task.perform(NetLogo6Task.scala:110)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:77)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2$adapted(LocalExecutor.scala:73)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:73)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:120)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:127)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openmole.core.exception.UserBadDataError: Error while executing command set network-filename /home/sam/.openmole/sam440/.tmp/945258ea-ec45-4d1e-86f4-9ce0d8ab76b6/executionc2c08667-06aa-4b82-a488-9e012976d052/containers/ab3d9191-40d3-4496-b4da-b87c074ae702/nnpchipndbmjkkbaokheanlibdjbmaaj/ROOT/tmp/network_generated.net:
 | Nothing named /HOME/SAM/.OPENMOLE/SAM440/.TMP/945258EA-EC45-4D1E-86F4-9CE0D8AB76B6/EXECUTIONC2C08667-06AA-4B82-A488-9E012976D052/CONTAINERS/AB3D9191-40D3-4496-B4DA-B87C074AE702/NNPCHIPNDBMJKKBAOKHEANLIBDJBMAAJ/ROOT/TMP/NETWORK_GENERATED.NET has been defined. at position 54 in 
 | 	at org.nlogo.core.Fail$.exception(Fail.scala:27)
 | 	at org.nlogo.core.Fail$.exception(Fail.scala:25)
 | 	at org.nlogo.core.Fail$.exception(Fail.scala:23)
 | 	at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$4(ExpressionParser.scala:391)
 | 	at scala.Option.getOrElse(Option.scala:121)
 | 	at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:391)
 | 	at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
 | 	at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
 | 	at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
 | 	at scala.collection.immutable.Range.foreach(Range.scala:156)
 | 	at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
 | 	at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
 | 	at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:69)
 | 	at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
 | 	at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
 | 	at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
 | 	at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 | 	at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 | 	at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 | 	at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
 | 	at scala.collection.Iterator.foreach(Iterator.scala:929)
 | 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
 | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
 | 	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
 | 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
 | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
 | 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
 | 	at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 | 	at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 | 	at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 | 	at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 | 	at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 | 	at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 | 	at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:42)
 | 	at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:78)
 | 	at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:91)
 | 	at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:158)
 | 	at org.nlogo.workspace.Evaluator.evaluateCommands(Evaluator.scala:20)
 | 	at org.nlogo.workspace.Evaluating.command(Evaluating.scala:80)
 | 	at org.nlogo.workspace.Evaluating.command$(Evaluating.scala:79)
 | 	at org.nlogo.workspace.AbstractWorkspaceScala.command(AbstractWorkspaceScala.scala:24)
 | 	at org.openmole.plugin.tool.netlogo6.NetLogo6.command(NetLogo6.java:54)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$6(NetLogoTask.scala:83)
 | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.wrapError(NetLogoTask.scala:54)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.executeNetLogo$1(NetLogoTask.scala:83)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$8(NetLogoTask.scala:93)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$8$adapted(NetLogoTask.scala:88)
 | 	at scala.collection.Iterator.foreach(Iterator.scala:944)
 | 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
 | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
 | 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
 | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
 | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$4(NetLogoTask.scala:88)
 | 	at org.openmole.tool.thread.package$.withThreadClassLoader(package.scala:53)
 | 	at org.openmole.core.code.CodePackage.withThreadClassLoader(CodePackage.scala:49)
 | 	at org.openmole.core.code.CodePackage.withThreadClassLoader$(CodePackage.scala:48)
 | 	at org.openmole.core.workflow.dsl$.withThreadClassLoader(package.scala:46)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$2(NetLogoTask.scala:77)
 | 	at org.openmole.plugin.task.external.External$.withWorkDir(External.scala:73)
 | 	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$1(NetLogoTask.scala:61)
 | 	at org.openmole.core.expansion.FromContext$$anon$8.from(FromContext.scala:157)
 | 	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:88)
 | 	at org.openmole.core.expansion.FromContext$$anon$9.from(FromContext.scala:163)
 | 	at org.openmole.core.workflow.task.Task.perform(Task.scala:64)
 | 	at org.openmole.core.workflow.task.Task.perform$(Task.scala:62)
 | 	at org.openmole.plugin.task.netlogo6.NetLogo6Task.perform(NetLogo6Task.scala:110)
 | 	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:77)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2$adapted(LocalExecutor.scala:73)
 | 	at scala.collection.Iterator.foreach(Iterator.scala:944)
 | 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
 | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
 | 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
 | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
 | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:73)
 | 	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:120)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:127)
 | 	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:70)
 | 	at java.lang.Thread.run(Thread.java:748)
	at org.openmole.plugin.task.netlogo.NetLogoTask.wrapError(NetLogoTask.scala:57)
	at org.openmole.plugin.task.netlogo.NetLogoTask.executeNetLogo$1(NetLogoTask.scala:83)
	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$8(NetLogoTask.scala:93)
	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$8$adapted(NetLogoTask.scala:88)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$4(NetLogoTask.scala:88)
	at org.openmole.tool.thread.package$.withThreadClassLoader(package.scala:53)
	at org.openmole.core.code.CodePackage.withThreadClassLoader(CodePackage.scala:49)
	at org.openmole.core.code.CodePackage.withThreadClassLoader$(CodePackage.scala:48)
	at org.openmole.core.workflow.dsl$.withThreadClassLoader(package.scala:46)
	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$2(NetLogoTask.scala:77)
	at org.openmole.plugin.task.external.External$.withWorkDir(External.scala:73)
	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$1(NetLogoTask.scala:61)
	at org.openmole.core.expansion.FromContext$$anon$8.from(FromContext.scala:157)
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:88)
	... 18 more
```

It seems like the file parameter is passed to NetLogo without being quoted, so NetLogo searches for an object named as the path of the filename.

**Comment by jopasserat** [comment]
Pull Request would be great please 😃

On 16 April 2018 10:23:56 BST, Samuel Thiriot <notifications@github.com> wrote:
>I tested the following bugfix  in NetLogoTask.scala (ancestor of both
>NetLogo5 and 6 tasks):
>```
>         for (inBinding ← netLogoInputs) {
>            val v = preparedContext(inBinding._1) match {
>              case x: String ⇒ '"' + x + '"'
>              case x: File   ⇒ '"' + x.toString + '"'
>              case x         ⇒ x.toString
>            }
>            executeNetLogo("set " + inBinding._2 + " " + v)
>          }
>```
>(just added the "File" case). 
>
>If the bugfix is ok for you, how to you prefer me to share it? A simple
>commit, or would you like a mergerequest ? 
>
>Tks
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openmole/openmole/issues/278#issuecomment-381535964

-- 
Jonathan Passerat-Palmbach, PhD
Research Associate
Department of Computing
Imperial College London

South Kensington Campus
Huxley Building - room 344
180 Queen's Gate
London SW7 2AZ

https://jopasser.at

**Comment by JusteRaimbault** [comment]
I'm not sure this is a bug, but the expected behavior of using string substitution when providing commands : in the workflow we are not aware of NetLogo's context and I guess adding the quote in a hardcoded way would interfere with this philosophy. I think you need to add yourself the quotes with escaping, for example
launchingCommandas = Seq("setup \"${file}\"")
(the correspondence between the NL context and the workflow is precised by the user with NetLogoInputs / Outputs, but should not be forced a priori - that's how I perceive the embedding idea, but maybe it is not how it was designed)

**Comment by samthiriot** [comment]
Sorry @JusteRaimbault , just seeing your comment now. 

I'm in a case where I have an openmole Val[File] which I add to netlogoInputs . So as far as I understand, this input is recognized as a file and copied / transmitted to the environment of the netlogo task. 

I had the feeling this was part of the philosophy of the task, but I'm very new here so it might be a mistake?

Now the way the value is actually passed to Netlogo in its language depends on the type. If that's a String, the conversion is done by adding quotes around the string. For other types a string substitution works naturally. I have the feeling the File is a specific cas, as the String one, where we need to quote the path of the file. It sounds like a generic need to me, but one more time, I may have a too narrowed understanding of it.

**Comment by mathieuleclaire** [comment]
To be tested on remote environments

**Comment by JusteRaimbault** [comment]
Works fine for me with a SSH environment. Closed.
