### ISSUE TITLE
Torque run: "No such file" error

### ISSUE THREAD

**Issue by IlPulpo** [openmole/openmole#290]
Dear openMole devs,

I am running a Netlogo model on a Torque environment. When running a small number of jobs it does works very fine, however when I tried a larger number (10.000+) I do get the error below.
Would you have a hint of a mistake I could have done?
Thanks you for your time,

Nicolas

read /home/nicolast/.openmole/.tmp/ssh/openmole-de5375f5-fa13-48fc-8717-77b7671f081c/tmp/1525167544587/bd2b6e42-2804-4b59-9162-02eef6aae082/result_923c2b79-2940-46e4-8066-78ac9d82f6d2.bin on org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1@8d63e69: No such file

fr.iscpif.gridscale.ssh.SSHException$NoSuchFileException: read /home/nicolast/.openmole/.tmp/ssh/openmole-de5375f5-fa13-48fc-8717-77b7671f081c/tmp/1525167544587/bd2b6e42-2804-4b59-9162-02eef6aae082/result_923c2b79-2940-46e4-8066-78ac9d82f6d2.bin on org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1@8d63e69: No such file
	at fr.iscpif.gridscale.ssh.SSHStorage$class.errorWrapping(SSHStorage.scala:78)
	at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1.errorWrapping(SSHStorageService.scala:33)
	at fr.iscpif.gridscale.storage.Storage$class.wrapException(Storage.scala:77)
	at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1.wrapException(SSHStorageService.scala:33)
	at fr.iscpif.gridscale.storage.Storage$class.read(Storage.scala:55)
	at org.openmole.plugin.environment.ssh.SSHStorageService$$anon$1.read(SSHStorageService.scala:33)
	at org.openmole.plugin.environment.gridscale.GridScaleStorage$class._downloadStream(GridScaleStorage.scala:36)
	at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$2._downloadStream(SSHPersistentStorage.scala:64)
	at org.openmole.plugin.environment.batch.storage.Storage$class._download(Storage.scala:69)
	at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$2._download(SSHPersistentStorage.scala:64)
	at org.openmole.plugin.environment.batch.storage.StorageService$$anonfun$download$1.apply$mcV$sp(StorageService.scala:209)
	at org.openmole.plugin.environment.batch.storage.StorageService$$anonfun$download$1.apply(StorageService.scala:209)
	at org.openmole.plugin.environment.batch.storage.StorageService$$anonfun$download$1.apply(StorageService.scala:209)
	at org.openmole.plugin.environment.batch.control.LimitedAccess$LimitedAccessToken.access(LimitedAccess.scala:37)
	at org.openmole.plugin.environment.batch.storage.StorageService$class.download(StorageService.scala:209)
	at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$2.download(SSHPersistentStorage.scala:64)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$getRuntimeResult$1$$anonfun$apply$3$$anonfun$apply$1.apply$mcV$sp(GetResultActor.scala:95)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$getRuntimeResult$1$$anonfun$apply$3$$anonfun$apply$1.apply(GetResultActor.scala:95)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$getRuntimeResult$1$$anonfun$apply$3$$anonfun$apply$1.apply(GetResultActor.scala:95)
	at org.openmole.plugin.environment.batch.environment.BatchEnvironment$.signalDownload(BatchEnvironment.scala:86)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$getRuntimeResult$1$$anonfun$apply$3.apply(GetResultActor.scala:95)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$getRuntimeResult$1$$anonfun$apply$3.apply(GetResultActor.scala:94)
	at org.openmole.core.workspace.NewFile.withTmpFile(NewFile.scala:27)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$getRuntimeResult$1.apply(GetResultActor.scala:94)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$getRuntimeResult$1.apply(GetResultActor.scala:94)
	at org.openmole.core.tools.service.Retry$.retry(Retry.scala:35)
	at org.openmole.core.tools.service.Retry$.retry(Retry.scala:42)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$.getRuntimeResult(GetResultActor.scala:93)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$.getResult(GetResultActor.scala:65)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$receive$1.apply(GetResultActor.scala:49)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$$anonfun$receive$1.apply(GetResultActor.scala:47)
	at org.openmole.plugin.environment.batch.control.UsageControl$class.tryWithToken(UsageControl.scala:28)
	at org.openmole.plugin.environment.batch.control.LimitedAccess.tryWithToken(LimitedAccess.scala:26)
	at org.openmole.plugin.environment.batch.environment.BatchService$class.tryWithToken(BatchService.scala:28)
	at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$2.tryWithToken(SSHPersistentStorage.scala:64)
	at org.openmole.plugin.environment.batch.refresh.GetResultActor$.receive(GetResultActor.scala:47)
	at org.openmole.plugin.environment.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:50)
	at org.openmole.plugin.environment.batch.refresh.JobManager$$anonfun$dispatch$1.apply$mcV$sp(JobManager.scala:57)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:21)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by romainreuillon** [comment]
Hi Nicolas,

could you try with the latest version (soon to be released) of openmole on next.openmole.org ?

Romain

**Comment by IlPulpo** [comment]
Hi Romain,

I've just tried it and have got a Javascript error while accessing the app on the browser.

In org/openmole/gui/ext/api/Api/getGUIPlugins:
java.lang.ArrayIndexOutOfBoundsException: 2
	at boopickle.StringCodecFast.decodeFastArray(StringCodecBase.scala:105)
	at boopickle.StringCodecFast.decodeFast(StringCodecBase.scala:16)
	at boopickle.DecoderSize.readString(CodecSize.scala:212)
	at boopickle.BasicPicklers$StringPickler$.unpickle(Pickler.scala:156)
	at boopickle.BasicPicklers$StringPickler$.unpickle(Pickler.scala:134)
	at boopickle.BasicPicklers$$anon$6.unpickle(Pickler.scala:444)
	at boopickle.BasicPicklers$$anon$6.unpickle(Pickler.scala:410)
	at boopickle.UnpickleImpl$UnpickledCurry.fromBytes(Default.scala:97)
	at org.openmole.gui.server.core.GUIServlet.$anonfun$addRouter$1(GUIServlet.scala:364)
	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:285)
	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:279)
	at org.scalatra.ScalatraBase.withRouteMultiParams(ScalatraBase.scala:356)
	at org.scalatra.ScalatraBase.withRouteMultiParams$(ScalatraBase.scala:352)
	at org.openmole.gui.server.core.GUIServlet.withRouteMultiParams(GUIServlet.scala:138)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:278)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:277)
	at org.openmole.gui.server.core.GUIServlet.invoke(GUIServlet.scala:138)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:253)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:251)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:490)
	at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:250)
	at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:248)
	at org.openmole.gui.server.core.GUIServlet.runRoutes(GUIServlet.scala:138)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:187)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:153)
	at org.openmole.gui.server.core.GUIServlet.executeRoutes(GUIServlet.scala:138)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:126)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at org.openmole.gui.server.core.GUIServlet.withResponse(GUIServlet.scala:138)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at org.openmole.gui.server.core.GUIServlet.withRequest(GUIServlet.scala:138)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at org.openmole.gui.server.core.GUIServlet.withRequestResponse(GUIServlet.scala:138)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:122)
	at org.openmole.gui.server.core.GUIServlet.org$scalatra$servlet$ServletBase$$super$handle(GUIServlet.scala:138)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at org.openmole.gui.server.core.GUIServlet.org$scalatra$servlet$FileUploadSupport$$super$handle(GUIServlet.scala:138)
	at org.scalatra.servlet.FileUploadSupport.handle(FileUploadSupport.scala:94)
	at org.scalatra.servlet.FileUploadSupport.handle$(FileUploadSupport.scala:79)
	at org.openmole.gui.server.core.GUIServlet.handle(GUIServlet.scala:138)
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:61)
	at org.scalatra.ScalatraServlet.service$(ScalatraServlet.scala:60)
	at org.openmole.gui.server.core.GUIServlet.service(GUIServlet.scala:138)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)

**Comment by mathieuleclaire** [comment]
Hey Nicolas,
how do you use OpenMOLE ? Did build it from sources or did you download it ?
Mathieu

**Comment by IlPulpo** [comment]
Hi Mathieu,
I downloaded the 8.0 snapshot and run the openmole.bat script using Windows.
I was using the 7.1 version in the same way without having this exception.
Nicolas

**Comment by mathieuleclaire** [comment]
OK. I am working on GUI plugins in a separate branch, it should be finished (or at least mergeable) today or tomorow and it should fix this bug. I will let you know.

Note also that we test a lot the plateform on linux systems but not really on Windows.
Mathieu

**Comment by IlPulpo** [comment]
Neat.
I understand that, it is personally a university related constraint.
I shall try on linux later on then.
And thanks for the responsiveness :)

**Comment by IlPulpo** [comment]
I have just try it (after a while) and the GUI bit is working perfectly :)
However it looks like Torque is not supported anymore? I can't see it in the next.* documentation and get a "You might want to specify a different PBS flavour in your job description? flavour = PBSPro" error.

**Comment by jopasserat** [comment]
Hey @IlPulpo Torque and PBS is the same, i've just edited the doc to make it clearer. Check thsi page: https://next.openmole.org/Clusters.html#PBS

The warning you've received is because we now support two different types of PBS: the open source one and PBSPro. They don't accept the exact same options, so depending on the version installed on your cluster you'll have to opt for one or the other.
By default it selects regular PBS.

I don't have a Torque install at hand though so please let us know if you can submit successfully using the latest version on next.openmole.org

**Comment by IlPulpo** [comment]
I state it this way and it uses the Pro flavour at the moment: 

val env =
  PBSEnvironment(
    "USER_ID",
    "IP_ADDRESS",
    nodes = 1,
    threads = 2,
    wallTime = 1 hour
)

**Comment by jopasserat** [comment]
I don't think it does it's set here: https://github.com/openmole/openmole/blob/dev/openmole/plugins/org.openmole.plugin.environment.pbs/src/main/scala/org/openmole/plugin/environment/pbs/PBSEnvironment.scala#L50

It could be that the error message is misleading though.. Can you post it all?

**Comment by jopasserat** [comment]
Important bit is here: `stderr=qsub: node(s) specification error`.
Seems like the way we specify PBS jobs is not compatible with your cluster...

Can you try to flip to PBSPro flavour just in case.

Otherwise, what would be valuable is an example script that works on your cluster (pbs script) and/or link to your uni's documentation pages.

**Comment by IlPulpo** [comment]
Thanks, I haven't got any errors at this stage with the current openMole version however.
How do you filp the flavour? I couldn't find it in the documentation.

Also, here is an example script they gave me:
`#! /bin/bash
### Transfer environment variables
#PBS -V
### Specify the queue to use
#PBS -q route
### Specify job name
#PBS -N helloWorld
### Merge standard error and standard output into one file
#PBS -j oe
### Specify required number of nodes and processors per node
#PBS -l nodes=8:ppn=16
### Limit the walltime for the job to 5 mins
#PBS -l walltime=00:05:00
### Load appropriate compile/mpi environment eg suite/gcc6_ompi2
module load modulename
cd $PBS_O_WORKDIR
cat $PBS_NODEFILE > ./cluster_nodes
NCPU=`wc -l < $PBS_NODEFILE`
mpiexec -np ${NCPU} –bind-to-core -machinefile ${PBS_NODEFILE} ./helloWorld >> ./helloWorld.out`

**Comment by jopasserat** [comment]
seems in line with [what we're doing in GridScale for open source PBS/Torque](https://github.com/openmole/gridscale/blob/master/pbs/src/main/scala/gridscale/pbs/package.scala#L30-L51).

I see your documentation mentions a `queue`, maybe it's compulsory to specify one?

See how to here: https://next.openmole.org/Clusters.html#PBS

**Comment by IlPulpo** [comment]
Indeed, it looks exactly the same. 
At the moment I only have access to a test platform on which there is no queue defined. 
I use this script on the test platform which is basically the same without the queue option:

```
#! /bin/bash
### Transfer environment variables
#PBS -V
### Specify job name
#PBS -N helloWorld
### Merge standard error and standard output into one file
#PBS -j oe
### Specify required number of nodes and processors per node
#PBS -l nodes=1:ppn=2:vmem=200mb
### Limit the walltime for the job to 5 mins
#PBS -l walltime=00:05:00try
### Load appropriate compile/mpi environment eg suite/gcc6_ompi2
cd $PBS_O_WORKDIRtry
cat $PBS_NODEFILE > ./cluster_nodes
NCPU=`wc -l < $PBS_NODEFILE`
bash p.sh
```

Do you know if there is a way for me to have the script GridScale is producing? I could play with and try to find why the error happens?

**Comment by jopasserat** [comment]
could be this `vmem` instead of `mem` we're using?

if you can build scala projects, try the example in gridscale https://github.com/openmole/gridscale/blob/master/examples/pbs/src/main/scala/gridscale/pbs/PBSExample.scala

you have direct access to the job description generated, it's the one used in OM
we used to log it in FINE log level but it's not here anymore :disappointed:

**Comment by IlPulpo** [comment]
Oh my bad! I was toying with the script when I sent you the copy, neither vmem nor mem is working.
But I haven't defined it so it should not matter, except if a default one is defined somewhere?

**Comment by jopasserat** [comment]
defaults to empty string in gridscale so shouldn't be the problem

**Comment by romainreuillon** [comment]
@IlPulpo I can craft a build of openmole that dump the pbs script in the console. Would that help you?

**Comment by romainreuillon** [comment]
I just committed a patch. If you run `openmole --loger-level fine` you should see the pbs script in the console, once a job is submitted.

This build should be available in a hour or so on http://next.openmole.org

**Comment by IlPulpo** [comment]
That would be awesome @romainreuillon! I have just downloaded it and get the warning: `WARNING: Ignored options: --loger-level fine` using both linux and windows.

**Comment by romainreuillon** [comment]
My mistake, the syntax is: `--logger-level fine`

**Comment by IlPulpo** [comment]
Fair, I could have pick it up as well. I can see the FINE: ... logs but can't find the script in them.

**Comment by romainreuillon** [comment]
This should fix the pb: 6c14eba47c02532249a197b23aaf6880855c5cdf

I guess it was because the submission was failing and therefore preventing the log from being printed.

**Comment by IlPulpo** [comment]
I can't manage to build the project properly on my computer so I can't help much more :-(

**Comment by jopasserat** [comment]
perfect then we've found it! 
i'll fix that asap and push a new build

**Comment by jopasserat** [comment]
i've pushed a fix in a new gridscale PR, if you want to try there before we merge back in openmole @IlPulpo ?

**Comment by IlPulpo** [comment]
Thanks you very much! We will have to wait a bit as I can't build the project on my computer (I've got trouble with compiling Scala files)

**Comment by romainreuillon** [comment]
I updated gridscale in a4d821c3e7710c200525963de23d3d4951d05959

I new version of openmole with the fix will be available on next.openmole.org in half an hour.
