### ISSUE TITLE
Java Metaspace

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#291]
I'm getting random exceptions (on some nodes on the grid only) when running a large NetLogo model that otherwise works well, caused by : 
java.lang.OutOfMemoryError: Metaspace
is seems to be linked not with the size of the JVM but the number of classes loaded and that some jvm options such as -XX:MetaspaceSize=... can help solving the problem.
Should we increase the size of the metaspace by default when running the java command ?
maybe adding a generic argument to openmole which would be arguments passed to the jvm would be interesting ?

**Comment by mathieuleclaire** [comment]
Could it be a Netlogo issue ? There a couples of issues like this on the [Netlogo github](https://github.com/NetLogo/NetLogo/issues?utf8=%E2%9C%93&q=OutOfMemoryError)

**Comment by chapinux** [comment]
" Out Of Memory Error : MetaSpace " :  #TitleOfMyHDRThesis  :-D

**Comment by JusteRaimbault** [comment]
@mathieuleclaire it may be NetLogo opening plenty of classes, more than it needs (we had the issue of it opening too many files and never closing it, causing bugs on local instances limiting total number of files opened) - I look into that.
@chapinux sorry the rest of the exception is not informative, just that it opens during workspace loading

**Comment by JusteRaimbault** [comment]
org.openmole.core.exception.InternalProcessingError: Error for context values in org.openmole.core.workflow.tools.InputOutputCheck$@39b47460 {evolution$population=[], evolution$state=EvolutionState(0,1525254415667,scala.util.Random@51fc3568,([Lmgo.algorithm.package$CDGenome$NoisyIndividual$Individual;@15614eb,[Lscala.collection.immutable.Vector;@16292406)), openmole$seed=6601323803259477854}
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:91)
	at org.openmole.core.expansion.FromContext$$anon$9.from(FromContext.scala:163)
	at org.openmole.core.workflow.task.Task.perform(Task.scala:65)
	at org.openmole.core.workflow.task.Task.perform$(Task.scala:63)
	at org.openmole.core.workflow.task.MoleTask.perform(MoleTask.scala:61)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:77)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2$adapted(LocalExecutor.scala:73)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:73)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:130)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:70)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.InternalProcessingError: Error for context values in org.openmole.core.workflow.tools.InputOutputCheck$@39b47460 {betaDC=2.598511882207546, gammaCDA=0.5050442711719071, gammaCDE=0.5661647752602249, lambdaAcc=0.005, networkSpeed=5.0, openmole$seed=7784379442494883116, relocationRate=0.7419212604911561, replication=517383983, scenario=3}
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:91)
	at org.openmole.core.expansion.FromContext$$anon$9.from(FromContext.scala:163)
	at org.openmole.core.workflow.task.Task.perform(Task.scala:65)
	at org.openmole.core.workflow.task.Task.perform$(Task.scala:63)
	at org.openmole.core.workflow.task.MoleTask.perform(MoleTask.scala:61)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:102)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:77)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$2$adapted(LocalExecutor.scala:73)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.openmole.core.workflow.execution.local.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:73)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:120)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:127)
	... 2 more
Caused by: org.openmole.core.exception.InternalProcessingError: Error for context values in org.openmole.core.workflow.tools.InputOutputCheck$@39b47460 {betaDC=2.598511882207546, gammaCDA=0.5050442711719071, gammaCDE=0.5661647752602249, lambdaAcc=0.005, networkSpeed=5.0, openmole$seed=7784379442494883116, relocationRate=0.7419212604911561, replication=517383983, scenario=3}
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:91)
	at org.openmole.core.expansion.FromContext$$anon$9.from(FromContext.scala:163)
	at org.openmole.core.workflow.task.Task.perform(Task.scala:65)
	at org.openmole.core.workflow.task.Task.perform$(Task.scala:63)
	at org.openmole.plugin.task.netlogo5.NetLogo5Task.perform(NetLogo5Task.scala:112)
	... 14 more
Caused by: java.lang.OutOfMemoryError: Metaspace

**Comment by romainreuillon** [comment]
It might be because netlogo generate many classes at runtime. If it is a leakage we can increase the metaspace but it will only make it work a bit longer.

Could you try with netlogo6, and if the same thing happens we could raise the metaspace size of the openmole runtime?

**Comment by romainreuillon** [comment]
What we could do, if the pb persist in netlogo6 is to cache and reuse the instance of the netlogo workspaces created by openmole. It might solve this pb, but it may also come with is set of problem (other memory leaks, variable initialisation...).

**Comment by JusteRaimbault** [comment]
hum, seems a bit dangerous as it interferes a bit with the black box concept ?
I'm migrating my extensions to 6 (they changed the API quite a bit) and test that

**Comment by JusteRaimbault** [comment]
There seem to be still some metaspace issues with NL6, but I was running nl6 after a nl5 task to compare their outputs ; I try a GA with nl6 version only

**Comment by JusteRaimbault** [comment]
To continue with the MetaSpace issues, I still got these exceptions when running the model with netlogo 6 (seems less but still a significant number of nodes crashing). [I also get some  java.lang.NoClassDefFoundError sometimes but this seems due to a bug in the new nw extension : org.nlogo.extensions.nw.gephi.GephiUtils$.$anonfun$shutdownStupidExtraThreads$1(GephiUtils.scala:33) - although I do not use these procedures at all !?? ; and the "shutdownStupidExtraThread" is a curious name for a function..)

**Comment by romainreuillon** [comment]
Okay, so I'll implement a cache for the netlogo workspace.

For the gephi issue it is probably because it looks for the class in the wrong class loader. If you can find the source code we may be able to understand how to force it to use the proper classloader...

**Comment by romainreuillon** [comment]
After thinking about the caching workspace, it comes with is own set of problems. They might be overcome, but it is not a trivial task. I have to work a bit on this to understand if there are any fundamental limitation or not.

@JusteRaimbault did you ping the netlogo dev on the meta space issue ? It seems that there is a class loader leak in the interaction between openmole and netlogo... Do we have any idea how netlogo loads the classes of its plugin ? Can we interact with it to provide a stable class loader in which classes are loaded once and for all ?

**Comment by romainreuillon** [comment]
Continuing my thought process.... I think we delete the extension jars after a model execution, so there is something to fix on the openmole side anyway.

**Comment by JusteRaimbault** [comment]
I look more into that on the netlogo side ; some extensions such as nw add their own classloaders (example above).

**Comment by JusteRaimbault** [comment]
I do not remember if we already discussed that ; a solution would be to call the HeadlessWorkspace.newInstance only once and use it in a concurrent way with an additional call to clear-all before any netlogo command (but is it easy to know that tasks are executed sequentially because they are on a node for example ?)

**Comment by romainreuillon** [comment]
Yes that would be a good solution. The problem I am trying to overcome is in the case when the simulation produces files that are used by a subsequent task. We should make sure that they are not overwritten by the next run of the netlogo task (since they use the same workspace).

**Comment by JusteRaimbault** [comment]
ok I guess there may be issues also because the .dispose() method is not called (like closing these produced files ?).
anyway it seems impossible to impose a single stable classloaders to the netlogo ExtensionManager, the class to load extension (jarContainer) has its own classLoader, so there is at least a classloader for each extension loaded, changing that would mess too much with the architecture..

**Comment by JusteRaimbault** [comment]
the .dispose() only kills running jobs, remove registered plots (no plots in headless) and resets extensions, so no issue with files on this point.

**Comment by romainreuillon** [comment]
This is a good news. I'am looking into a way to move the produced files out of the netlogo workspace then before releasing it and using it for another model run.

**Comment by romainreuillon** [comment]
yes it would :). There are already some post processing function to gather and clean files for openmole external tasks. I think we should make use of them to detect the files that are collected at the end of the netlogo task execution and add an option to move those file in a external folder. The rest of the files should be cleaned except for the model, the extension and all the data that are provided by the user for the task to be able to run...

**Comment by JusteRaimbault** [comment]
ok ! that would however imply a stricter use of the `resources` option (I guess people just use the `embedWorkspace` dirtily and do not specify resources - at least I do ; but that would be better indeed !)

**Comment by romainreuillon** [comment]
The `embedWorkspace` option make use of the `resources` mechanism internally. If the preservation of resources is achieved it should cover `embedWorkspace` as well.

**Comment by JusteRaimbault** [comment]
The pooling newly implemented by @romainreuillon with the option `reuseWorkspace` in the NetLogoTask solves this for NetLogo ; as it was the only task causing the issue I guess we can close.
