### ISSUE TITLE
Cannot start openmole after a fresh build

### ISSUE THREAD

**Issue by guillaumecherel** [openmole/openmole#293]
After a fresh build of a newly cloned the repository, trying to run openmole gives the error below. I cloned the repository and then ran the script `build.sh`. I don't know if it is related, but the script crashed with a `java.lang.OutOfMemoryError: Metaspace`, at the step of building openmole. Rerunning that step a second time (`(cd openmole && sbt "project openmole" assemble)`) finished without error and produced the executable, but this one crashes at startup:

```
May 07, 2018 12:48:05 PM org.openmole.gui.server.core.Utils$ addPluginRoutes
INFO: Loading GUI plugins
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openmole.launcher.Launcher.main(Launcher.java:131)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.openmole.gui.server.core.GUIServer.start(GUIServer.scala:142)
        at org.openmole.ui.Application$.$anonfun$run$23(Application.scala:278)
        at org.openmole.ui.Application$.$anonfun$run$23$adapted(Application.scala:276)
        at org.openmole.gui.server.core.GUIServices$.withServices(GUIServlet.scala:106)
        at org.openmole.ui.Application$.$anonfun$run$19(Application.scala:276)
        at org.openmole.ui.Application$.$anonfun$run$19$adapted(Application.scala:260)
        at org.openmole.tool.stream.package$.withClosable(package.scala:117)
        at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withFileOutputStream$1(package.scala:422)
        at org.openmole.ui.Application$.run(Application.scala:260)
        at org.openmole.ui.Application.run(Application.scala)
        ... 5 more
```

**Comment by jopasserat** [comment]
Seems like you've still got an old instance running in the background.

Try `pkill -f openmole` and start again maybe?

On 7 May 2018 11:55:30 BST, guillaumecherel <notifications@github.com> wrote:
>After a fresh build of a newly cloned the repository, trying to run
>openmole gives the error below. I cloned the repository and then ran
>the script `build.sh`. I don't know if it is related, but the script
>crashed with a `java.lang.OutOfMemoryError: Metaspace`, at the step of
>building openmole. Rerunning that step a second time (`(cd openmole &&
>sbt "project openmole" assemble)`) finished without error and produced
>the executable, but this one crashes at startup:
>
>```
>May 07, 2018 12:48:05 PM org.openmole.gui.server.core.Utils$
>addPluginRoutes
>INFO: Loading GUI plugins
>java.lang.reflect.InvocationTargetException
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at
>sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>at
>sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>        at java.lang.reflect.Method.invoke(Method.java:498)
>        at org.openmole.launcher.Launcher.main(Launcher.java:131)
>Caused by: java.net.BindException: Address already in use
>        at sun.nio.ch.Net.bind0(Native Method)
>        at sun.nio.ch.Net.bind(Net.java:433)
>        at sun.nio.ch.Net.bind(Net.java:425)
>at
>sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
>    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
>at
>org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
>at
>org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
>at
>org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
>at
>org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
>at
>org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>   at org.openmole.gui.server.core.GUIServer.start(GUIServer.scala:142)
> at org.openmole.ui.Application$.$anonfun$run$23(Application.scala:278)
>at
>org.openmole.ui.Application$.$anonfun$run$23$adapted(Application.scala:276)
>at
>org.openmole.gui.server.core.GUIServices$.withServices(GUIServlet.scala:106)
> at org.openmole.ui.Application$.$anonfun$run$19(Application.scala:276)
>at
>org.openmole.ui.Application$.$anonfun$run$19$adapted(Application.scala:260)
>   at org.openmole.tool.stream.package$.withClosable(package.scala:117)
>at
>org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withFileOutputStream$1(package.scala:422)
>        at org.openmole.ui.Application$.run(Application.scala:260)
>        at org.openmole.ui.Application.run(Application.scala)
>        ... 5 more
>```
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openmole/openmole/issues/293

-- 
Jonathan Passerat-Palmbach, PhD
Research Associate
Department of Computing
Imperial College London

South Kensington Campus
Huxley Building - room 344
180 Queen's Gate
London SW7 2AZ

https://jopasser.at

**Comment by JusteRaimbault** [comment]
I also encountered the MetaSpace error during building recently ; then relaunched and it worked fine and the resulting openmole worked.

**Comment by guillaumecherel** [comment]
@jopasserat that did the trick, thanks!

**Comment by jopasserat** [comment]
The metaspace error means `sbt` needs more memory though

**Comment by JusteRaimbault** [comment]
it seems that the argument MaxMetaSpaceSize can be set when launching the jvm to increase the metaspace. Is it easy to pass jvm args when launching sbt ?
