### ISSUE TITLE
NoSuchElementException after recent master branch changes

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#30]
My REPEAT project workflows are working fine when compiled against and run in OpenMOLE master branch revision 2f9ff7b6 from 20/4/2015. With the current HEAD of the master branch (4a0d0124) it fails, however, with the following error.

```
OpenMOLE> import com.andreasschuh.repeat.workflow._
import com.andreasschuh.repeat.workflow._
OpenMOLE> PreRegistration ().start
java.util.NoSuchElementException: key not found: log
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at org.openmole.core.workflow.mole.Capsule$$anonfun$8$$anonfun$apply$5.apply(Capsule.scala:117)
  at org.openmole.core.workflow.mole.Capsule$$anonfun$8$$anonfun$apply$5.apply(Capsule.scala:117)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
  at scala.collection.SetLike$class.map(SetLike.scala:92)
  at scala.collection.AbstractSet.map(Set.scala:47)
  at org.openmole.core.workflow.mole.Capsule$$anonfun$8.apply(Capsule.scala:117)
  at org.openmole.core.workflow.mole.Capsule$$anonfun$8.apply(Capsule.scala:116)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
  at org.openmole.core.workflow.mole.Capsule.received(Capsule.scala:116)
  at org.openmole.core.workflow.mole.Capsule.strainerOutputs(Capsule.scala:97)
  at org.openmole.core.workflow.mole.Capsule.outputs(Capsule.scala:79)
  at org.openmole.core.workflow.transition.Transition.data(Transition.scala:93)
  at org.openmole.core.workflow.transition.Transition.data(Transition.scala:37)
  at org.openmole.core.workflow.validation.TypeUtil$$anonfun$computeTransmissions$1.apply(TypeUtil.scala:87)
  at org.openmole.core.workflow.validation.TypeUtil$$anonfun$computeTransmissions$1.apply(TypeUtil.scala:87)
  at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
  at org.openmole.core.workflow.validation.TypeUtil$.computeTransmissions(TypeUtil.scala:87)
  at org.openmole.core.workflow.validation.TypeUtil$.computeTypes(TypeUtil.scala:56)
  at org.openmole.core.workflow.validation.TypeUtil$.validTypes(TypeUtil.scala:50)
  at org.openmole.core.workflow.validation.Validation$$anonfun$5$$anonfun$apply$10$$anonfun$apply$11.apply(Validation.scala:116)
  at org.openmole.core.workflow.validation.Validation$$anonfun$5$$anonfun$apply$10$$anonfun$apply$11.apply(Validation.scala:115)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
  at scala.collection.SetLike$class.map(SetLike.scala:92)
  at scala.collection.AbstractSet.map(Set.scala:47)
  at org.openmole.core.workflow.validation.Validation$$anonfun$5$$anonfun$apply$10.apply(Validation.scala:115)
  at org.openmole.core.workflow.validation.Validation$$anonfun$5$$anonfun$apply$10.apply(Validation.scala:113)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
  at scala.collection.immutable.List.flatMap(List.scala:344)
  at org.openmole.core.workflow.validation.Validation$$anonfun$5.apply(Validation.scala:113)
  at org.openmole.core.workflow.validation.Validation$$anonfun$5.apply(Validation.scala:112)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.Iterator$class.foreach(Iterator.scala:750)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
  at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
  at org.openmole.core.workflow.validation.Validation$.sourceTypeErrors(Validation.scala:112)
  at org.openmole.core.workflow.validation.Validation$$anonfun$apply$39.apply(Validation.scala:286)
  at org.openmole.core.workflow.validation.Validation$$anonfun$apply$39.apply(Validation.scala:274)
  at scala.collection.immutable.List.flatMap(List.scala:327)
  at org.openmole.core.workflow.validation.Validation$.apply(Validation.scala:274)
  at org.openmole.core.workflow.mole.MoleExecution.start(MoleExecution.scala:172)
  ... 43 elided
```

Links to my source code:
- [```PreRegistration``` workflow](https://github.com/schuhschuh/REPEAT/blob/824907b23ae39c55ff86f3084bf42678fbf84d26/src/main/scala/com/andreasschuh/repeat/workflow/PreRegistration.scala#L111)
- [```RegisterToTemplateRigid``` puzzle](https://github.com/schuhschuh/REPEAT/blob/824907b23ae39c55ff86f3084bf42678fbf84d26/src/main/scala/com/andreasschuh/repeat/puzzle/RegisterToTemplateRigid.scala#L83)
- [```RegisterToTemplateAffine``` puzzle](https://github.com/schuhschuh/REPEAT/blob/824907b23ae39c55ff86f3084bf42678fbf84d26/src/main/scala/com/andreasschuh/repeat/puzzle/RegisterToTemplateAffine.scala#L83)

ScalaTask code which sets the "log" variable can be found [here](https://github.com/schuhschuh/REPEAT/blob/824907b23ae39c55ff86f3084bf42678fbf84d26/src/main/scala/com/andreasschuh/repeat/puzzle/RegisterToTemplateAffine.scala#L68) and [here](https://github.com/schuhschuh/REPEAT/blob/824907b23ae39c55ff86f3084bf42678fbf84d26/src/main/scala/com/andreasschuh/repeat/puzzle/RegisterToTemplateRigid.scala#L66). Note that these are two different objects created by ```Val[File]```.

**Comment by romainreuillon** [comment]
This should be working now.

**Comment by schuhschuh** [comment]
This error is indeed gone. Instead I am getting now a formal validation error:
```
OpenMOLE>import com.andreasschuh.repeat.workflow._
import com.andreasschuh.repeat.workflow._
OpenMOLE>val ex = PreRegistration().start
org.openmole.core.exception.UserBadDataError: Formal validation of your mole has failed, several errors have been found: Wrong type received at Slot hash 2031003023 of ComputeRigidTemplateDofsBegin, srcId: Int is expected but srcId: Array[Int] is provided.
Wrong type received at Slot hash 2024275149 of CopyFiles, srcIm: java.io.File is expected but srcIm: Array[java.io.File] is provided.
  at org.openmole.core.workflow.mole.MoleExecution.start(MoleExecution.scala:173)
  ... 43 elided
```
The pipeline is [here](https://github.com/schuhschuh/REPEAT/blob/6e5cbe7cd4cf2afe6eb597aa22793de6a268d6ea/src/main/scala/com/andreasschuh/repeat/workflow/PreRegistration.scala#L86):
```scala
forEachIm -< CopyFilesTo -- RegisterToTemplateRigid // -- ...
```

See also [CopyFilesTo](https://github.com/schuhschuh/REPEAT/blob/6e5cbe7cd4cf2afe6eb597aa22793de6a268d6ea/src/main/scala/com/andreasschuh/repeat/puzzle/CopyFilesTo.scala#L66) and the line of [RegisterToTemplateRigid](https://github.com/schuhschuh/REPEAT/blob/6e5cbe7cd4cf2afe6eb597aa22793de6a268d6ea/src/main/scala/com/andreasschuh/repeat/puzzle/RegisterToTemplateRigid.scala#L59) which causes the error.

Note that the same workflow worked fine before and I also cannot see why the input would be an ```Array[Int]``` after the exploration because there is no aggregation transition.

**Comment by romainreuillon** [comment]
I changed (simplified) some part of the validation system so it makes sens that some bug might have been introduced here. Could you try to provide a simple workflow so I could reproduce it?

Otherwise how could I generate you workflow in order to inspect it?

**Comment by romainreuillon** [comment]
OK, I think I reproduced the bug, it is happening when the exploration is in a strainer and the previous task produce a variable with a similar name, such as in:
```
    val pInt = Prototype[Int]("t")
    val exploration = ExplorationTask(ExplicitSampling(pInt, (0 to 10)))

    val t1 = EmptyTask()
    t1 addInput pInt

    val t2 = EmptyTask()
    t2 addInput pInt

    val puzzle = (Capsule(exploration, strainer = true) -< Capsule(t1, strainer = true) -- t2)
```

I have to go, but I'll fix that later.

**Comment by schuhschuh** [comment]
Glad you found a toy example.

**Comment by romainreuillon** [comment]
It should be fixed now.

**Comment by schuhschuh** [comment]
It's working now, thanks!
