### ISSUE TITLE
Relative path of environment workDirectory should be made absolute

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#36]
The `workDirectory` of the `SLURMEnvironment` (and possibly others as well) must at the moment be an absolute path. With a relative path, the following error is raised:

```
java.net.URISyntaxException: Relative path in absolute URI: file://as12312@localhostopenmole
    at java.net.URI.checkPath(URI.java:1804)
    at java.net.URI.<init>(URI.java:679)
    at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$2.<init>(SSHPersistentStorage.scala:48)
    at org.openmole.plugin.environment.ssh.SSHPersistentStorage$class.storage(SSHPersistentStorage.scala:46)
    at org.openmole.plugin.environment.slurm.SLURMEnvironment.storage$lzycompute(SLURMEnvironment.scala:57)
    at org.openmole.plugin.environment.slurm.SLURMEnvironment.storage(SLURMEnvironment.scala:57)
    at org.openmole.plugin.environment.ssh.SSHPersistentStorage$class.allStorages(SSHPersistentStorage.scala:60)
    at org.openmole.plugin.environment.slurm.SLURMEnvironment.allStorages(SLURMEnvironment.scala:57)
    at org.openmole.plugin.environment.slurm.SLURMEnvironment.allStorages(SLURMEnvironment.scala:57)
    at org.openmole.core.batch.environment.BatchEnvironment$class.storages(BatchEnvironment.scala:173)
    at org.openmole.plugin.environment.slurm.SLURMEnvironment.storages$lzycompute(SLURMEnvironment.scala:57)
    at org.openmole.plugin.environment.slurm.SLURMEnvironment.storages(SLURMEnvironment.scala:57)
    at org.openmole.core.batch.environment.BatchEnvironment$class.selectAStorage(BatchEnvironment.scala:185)
    at org.openmole.plugin.environment.slurm.SLURMEnvironment.selectAStorage(SLURMEnvironment.scala:57)
    at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:69)
    at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:65)
    at org.openmole.core.workspace.Workspace.withTmpFile(Workspace.scala:211)
    at org.openmole.core.batch.refresh.UploadActor.org$openmole$core$batch$refresh$UploadActor$$initCommunication(UploadActor.scala:65)
    at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply$mcV$sp(UploadActor.scala:54)
    at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply(UploadActor.scala:50)
    at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply(UploadActor.scala:50)
    at org.openmole.core.batch.refresh.package$.withRunFinalization(package.scala:23)
    at org.openmole.core.batch.refresh.UploadActor.receive(UploadActor.scala:50)
    at org.openmole.core.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:81)
    at org.openmole.core.batch.refresh.JobManager$$anonfun$1$$anon$1.run(JobManager.scala:63)
```

This error could be circumvented if relative paths would be made absolute using the current working directory of the OpenMOLE console as base.

**Comment by romainreuillon** [comment]
This solution would only work in the case of a shared storage because the openmole install dir would not make sens on the remote machine otherwise. Do you see a general solution?

**Comment by schuhschuh** [comment]
I see, so it's a string of a path on the remote machine, which in my case coincides with the submission machine. I think it's still reasonable to make the passed relative path absolute using the CWD of the console on the submission machine b/c if it were different on the remote, the user of course needs to specify the absolute path. As they chose not to, the paths must be identical to the submission machine. Also, you could do this based on ```storageSharedLocally```. If ```true```, make the path absolute using the CWD, if not, throw a proper error message asking the user to specify an absolute path.

**Comment by romainreuillon** [comment]
Env have been refactored in depth, reopen this issue if it is still problematic.
