### ISSUE TITLE
[Build] NPM dependencies update fails

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#367]
I'm obtaining a trust issue (see below) when building OpenMOLE (sbt buildOpenMOLE in openmole directory), when updating npm dependencies. I tried to set `npm config set strict-ssl false` and had a similar issue ; then `npm config set strict-ssl true` solved the issue and OpenMOLE was successively built. This is quite strange however, as setting back to false it still works; the issue is not really reproducible. Any idea of what may have caused the issue / how to solve or warn users in the doc ?

`[info] Updating NPM dependencies
[error] npm WARN package.json @ No description
[error] npm WARN package.json @ No repository field.
[error] npm WARN package.json @ No README data
[error] npm http GET https://registry.npmjs.org/ace-builds/1.2.9
[error] bnd: The Bundle Activator org.openmole.plugin.task.udocker.Activator does not implement BundleActivator.
[error] npm http GET https://registry.npmjs.org/plotly.js/1.31.0
[error] npm http GET https://registry.npmjs.org/sortablejs/1.7.0
[error] npm http GET https://registry.npmjs.org/bootstrap.native/2.0.22
[error] bnd: The Bundle Activator org.openmole.plugin.task.scilab.Activator does not implement BundleActivator.
[error] bnd: The Bundle Activator org.openmole.plugin.task.r.Activator does not implement BundleActivator.
[error] bnd: The Bundle Activator org.openmole.gui.plugin.authentication.sshkey.Activator does not implement BundleActivator.
[error] bnd: The Bundle Activator org.openmole.gui.plugin.authentication.sshlogin.Activator does not implement BundleActivator.
[error] bnd: The Bundle Activator org.openmole.gui.plugin.authentication.egi.Activator does not implement BundleActivator.
[error] npm http GET https://registry.npmjs.org/ace-builds/1.2.9
[error] npm http GET https://registry.npmjs.org/bootstrap.native/2.0.22
[error] npm http GET https://registry.npmjs.org/plotly.js/1.31.0
[error] npm http GET https://registry.npmjs.org/sortablejs/1.7.0
[error] npm http GET https://registry.npmjs.org/bootstrap.native/2.0.22
[error] npm http GET https://registry.npmjs.org/ace-builds/1.2.9
[error] npm http GET https://registry.npmjs.org/sortablejs/1.7.0
[error] npm http GET https://registry.npmjs.org/plotly.js/1.31.0
[error] npm ERR! Error: CERT_UNTRUSTED
[error] npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
[error] npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
[error] npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
[error] npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
[error] npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
[error] npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
[error] npm ERR!     at doWrite (_stream_writable.js:223:10)
[error] npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
[error] npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
[error] npm ERR!     at write (_stream_readable.js:583:24)
[error] npm ERR!     at flow (_stream_readable.js:592:7)
[error] npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
[error] npm ERR! If you need help, you may report this log at:
[error] npm ERR!     <http://github.com/isaacs/npm/issues>
[error] npm ERR! or email it to:
[error] npm ERR!     <npm-@googlegroups.com>
[error] npm ERR! System Linux 3.13.0-125-generic
[error] npm ERR! command "/usr/bin/nodejs" "/usr/local/bin/npm" "install"`

**Comment by JusteRaimbault** [comment]
After discussion, we should close the issue as it does not seem to be reproductible (may have been a network issue or configuration of this particular server).
