### ISSUE TITLE
[Core] Concurrent OpenMoles fail due to database concurrent access

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#390]
When trying to run two instances of OpenMole on the same machine, the second sometimes fails at launch, apparently due to concurrent access to the database - it is however not reproducible, sometimes it works and others not.

`java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openmole.launcher.Launcher.main(Launcher.java:147)
Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused"
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:457)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:367)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
        at org.h2.Driver.connect(Driver.java:69)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:72)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:439)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:47)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:38)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:218)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:217)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:38)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.h2.util.NetUtils.createSocket(NetUtils.java:103)
        at org.h2.util.NetUtils.createSocket(NetUtils.java:83)
        at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:115)
        at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:453)`

**Comment by JusteRaimbault** [comment]
Still encountering this issue from time to time (currently one instance must extensively be using the database as removing a lot of replicas - impossible to launch an other instance)

**Comment by JusteRaimbault** [comment]
I'm closing this sordid issue as first it is not reproducible and secondly it makes no sense to run several openmole in parallel in the same place.
