### ISSUE TITLE
Output file key not found error when grouping jobs

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#44]
After I added "by 10" to my tasks, I encountered the following error which I just now could relate to this change. If I remove that grouping of batch jobs, the error goes away.

It may also be important to know that I use it within a ```Skip```, i.e.,
```scala
begin -- Skip(reg on Env.short by 10, cond1 + " && " + cond2)
```
Unfortunately I didn't manage to reproduce the issue with a simple test script, though.

Error output:
```
May 06, 2015 3:45:15 AM org.openmole.core.batch.refresh.JobManager $bang
FINE: Error in job refresh
com.thoughtworks.xstream.converters.ConversionException: key not found: /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/5a0cd7ef-da4d-49a0-9dd8-3b539b3c160b/.tmp/d4841b96-2295-478c-9f15-18d7bb100b8d/categoryd6654590-d370-431a-a2c8-1a8350fd5450/mni305.nii.gz : key not found: /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/5a0cd7ef-da4d-49a0-9dd8-3b539b3c160b/.tmp/d4841b96-2295-478c-9f15-18d7bb100b8d/categoryd6654590-d370-431a-a2c8-1a8350fd5450/mni305.nii.gz
---- Debugging information ----
message             : key not found: /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/5a0cd7ef-da4d-49a0-9dd8-3b539b3c160b/.tmp/d4841b96-2295-478c-9f15-18d7bb100b8d/categoryd6654590-d370-431a-a2c8-1a8350fd5450/mni305.nii.gz
cause-exception     : java.util.NoSuchElementException
cause-message       : key not found: /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/5a0cd7ef-da4d-49a0-9dd8-3b539b3c160b/.tmp/d4841b96-2295-478c-9f15-18d7bb100b8d/categoryd6654590-d370-431a-a2c8-1a8350fd5450/mni305.nii.gz
class               : java.io.File
required-type       : java.io.File
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
wrapped-converter   : org.openmole.core.serializer.file.FileConverterInjecter
path                : /org.openmole.core.batch.message.package$ContextResults/results/tree/value/value/variables/tree/value/value
line number         : 25
class[1]            : org.openmole.core.workflow.data.Variable$$anon$1
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : scala.collection.immutable.RedBlackTree$BlackTree
class[3]            : scala.collection.immutable.TreeMap
class[4]            : org.openmole.core.workflow.data.Context$$anon$1
class[5]            : scala.util.Success
class[6]            : org.openmole.core.batch.message.package$ContextResults
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1206)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1190)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1070)
	at org.openmole.core.serializer.file.FileInjection$class.fromXML(FileInjection.scala:30)
	at org.openmole.core.serializer.SerialiserService$$anon$7$$anon$8.fromXML(SerialiserService.scala:71)
	at org.openmole.core.serializer.SerialiserService$$anonfun$deserialiseReplaceFiles$2$$anonfun$apply$3.apply(SerialiserService.scala:148)
	at org.openmole.core.serializer.SerialiserService$$anonfun$deserialiseReplaceFiles$2$$anonfun$apply$3.apply(SerialiserService.scala:146)
	at org.openmole.core.serializer.converter.Factory$class.exec(Factory.scala:56)
	at org.openmole.core.serializer.SerialiserService$$anon$7.exec(SerialiserService.scala:69)
	at org.openmole.core.serializer.SerialiserService$$anonfun$deserialiseReplaceFiles$2.apply(SerialiserService.scala:145)
	at org.openmole.tool.lock.package$ReadWriteLockDecorator.read(package.scala:48)
	at org.openmole.core.serializer.SerialiserService$.deserialiseReplaceFiles(SerialiserService.scala:145)
	at org.openmole.core.serializer.SerialiserService$$anonfun$deserialiseReplaceFiles$1.apply(SerialiserService.scala:140)
	at org.openmole.tool.lock.package$ReadWriteLockDecorator.read(package.scala:48)
	at org.openmole.core.serializer.SerialiserService$.deserialiseReplaceFiles(SerialiserService.scala:138)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$getContextResults$1$$anonfun$apply$5.apply(GetResultActor.scala:132)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$getContextResults$1$$anonfun$apply$5.apply(GetResultActor.scala:130)
	at org.openmole.core.workspace.Workspace.withTmpFile(Workspace.scala:217)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$getContextResults$1.apply(GetResultActor.scala:130)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$getContextResults$1.apply(GetResultActor.scala:123)
	at org.openmole.core.workspace.Workspace.withTmpFile(Workspace.scala:217)
	at org.openmole.core.batch.refresh.GetResultActor.getContextResults(GetResultActor.scala:123)
	at org.openmole.core.batch.refresh.GetResultActor.getResult(GetResultActor.scala:71)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1$$anonfun$apply$mcV$sp$1.apply(GetResultActor.scala:50)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1$$anonfun$apply$mcV$sp$1.apply(GetResultActor.scala:48)
	at org.openmole.core.batch.control.UsageControl$class.tryWithToken(UsageControl.scala:28)
	at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$2.tryWithToken(SSHPersistentStorage.scala:47)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1.apply$mcV$sp(GetResultActor.scala:48)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1.apply(GetResultActor.scala:46)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1.apply(GetResultActor.scala:46)
	at org.openmole.core.batch.refresh.package$.withRunFinalization(package.scala:23)
	at org.openmole.core.batch.refresh.GetResultActor.receive(GetResultActor.scala:46)
	at org.openmole.core.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:84)
	at org.openmole.core.batch.refresh.JobManager$$anonfun$1$$anon$1.run(JobManager.scala:63)
Caused by: java.util.NoSuchElementException: key not found: /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/5a0cd7ef-da4d-49a0-9dd8-3b539b3c160b/.tmp/d4841b96-2295-478c-9f15-18d7bb100b8d/categoryd6654590-d370-431a-a2c8-1a8350fd5450/mni305.nii.gz
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.openmole.core.serializer.file.FileInjection$class.getMatchingFile(FileInjection.scala:28)
	at org.openmole.core.serializer.SerialiserService$$anon$7$$anon$8.getMatchingFile(SerialiserService.scala:71)
	at org.openmole.core.serializer.file.FileConverterInjecter.fromString(FileConverterInjecter.scala:28)
	at com.thoughtworks.xstream.converters.SingleValueConverterWrapper.fromString(SingleValueConverterWrapper.java:41)
	at com.thoughtworks.xstream.converters.SingleValueConverterWrapper.unmarshal(SingleValueConverterWrapper.java:49)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 87 more
```

**Comment by romainreuillon** [comment]
I was not able to reproduce it, but I tried a fix, could you test it?

**Comment by schuhschuh** [comment]
Unfortunately I still get this error when grouping jobs.

**Comment by romainreuillon** [comment]
I think I found where it came from, could you test with the last commit?

**Comment by schuhschuh** [comment]
There is a compilation error in JobLauncher.scala:317. The "src" variable given as first argument to ReplicatedFile is unknown.

**Comment by schuhschuh** [comment]
I see you just fixed it...

**Comment by schuhschuh** [comment]
Another problem fixed successfully :+1:

**Comment by romainreuillon** [comment]
Great!
