### ISSUE TITLE
Openmole with PBS: waiting for jobs to finish.

### ISSUE THREAD

**Issue by guillaumecherel** [openmole/openmole#445]
Hi,

I'm trying to run jobs on a cluster using PBS. I use a minimal test script that runs only 1 job (see below). When I hit run, it never terminates, the status stays on "running". OpenMOLE seems to be waiting forever for the job to finish (see the output below, running openmole with --logger-level fine), even though when I log on the cluster to monitor the jobs manually, it seems to have terminated successfully. I see no error reported in the "Environments" pane.

I'm using openmole from the current state of the branch 10-dev (from the github repository).

Here is my openmole test script (I've tried with both PBSPro and Torque):
```
val seed = Val[Int]
val o = Val[Int]

val task = ScalaTask("val o = 1") set(
  inputs += seed,
  outputs += o,
  
  seed := 0
  )
  
val upmc = PBSEnvironment(
    user = "blablabla",
    host = "mesu.dsi.upmc.fr",
    flavour = PBSPro,
    wallTime = 60.seconds)
  
task hook ToStringHook() on upmc
```

Here is the output of the command `tracejob` that I run on the cluster and makes me think that the job terminated succesfully (see "Exit_status=0" on the last line):
```
Job: 488292.mesu2

08/14/2019 16:41:17  L    Considering job to run
08/14/2019 16:41:17  S    Job Queued at request of blablabla@mesu1.ib0.xa.dsi.upmc.fr, owner =
                          blablabla@mesu1.ib0.xa.dsi.upmc.fr, job name =
                          job-fe912add-8257-4e94-a2bf-7a108cfe4bb4.pbs, queue = f1c_b
08/14/2019 16:41:17  S    Job Modified at request of Scheduler@mesu2.ib0.xa.dsi.upmc.fr
08/14/2019 16:41:17  S    Job Run at request of Scheduler@mesu2.ib0.xa.dsi.upmc.fr on exec_vnode
                          (r1i3n33:ncpus=1)
08/14/2019 16:41:17  L    Job run
08/14/2019 16:41:17  S    enqueuing into beta, state 1 hop 1
08/14/2019 16:41:17  S    dequeuing from beta, state 1
08/14/2019 16:41:17  S    enqueuing into f1c_b, state 1 hop 1
08/14/2019 16:41:26  S    Obit received momhop:1 serverhop:1 state:4 substate:42
08/14/2019 16:41:26  S    Exit_status=0 resources_used.cpupercent=103 resources_used.cput=00:00:18
                          resources_used.mem=0kb resources_used.ncpus=1 resources_used.vmem=0kb
                          resources_used.walltime=00:00:10
```

In OpenMOLE's GUI standard output, running openmole with the argument `--logger-level fine`, I see the following message, with the last few lines repeating every few seconds, they mention checking if mole execution is finished:
```
org.openmole.core.workflow.mole.MoleExecutionMessage.dispatch:617 - processing message StartMoleExecution(None) in mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7
org.openmole.core.workflow.mole.MoleExecution.start:334 - Starting mole execution
org.openmole.core.workflow.mole.MoleExecution.updateNbJobs:156 - update number of jobs of sub mole execution org.openmole.core.workflow.mole.MoleExecution$SubMoleExecutionState@11a750b4, add 1 to 0
org.openmole.core.workflow.mole.MoleExecution.checkMoleExecutionIsFinished:491 - check if mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7 is finished, message queue empty false, number of jobs 1: TreeMap(0 -> capsule@138512161:task@1543925628) - TreeMap(false -> TreeSet(0))
org.openmole.core.workflow.mole.MoleExecutionMessage.dispatch:617 - processing message WithMoleExecutionSate(org.openmole.plugin.environment.batch.refresh.JobManager$$$Lambda$2497/1058438015@25f78d9f) in mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7
org.openmole.core.workflow.mole.MoleExecution.checkMoleExecutionIsFinished:491 - check if mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7 is finished, message queue empty true, number of jobs 1: TreeMap(0 -> capsule@138512161:task@1543925628) - TreeMap(false -> TreeSet(0))
org.openmole.core.workflow.mole.MoleExecutionMessage.dispatch:617 - processing message WithMoleExecutionSate(org.openmole.plugin.environment.batch.refresh.JobManager$$$Lambda$2497/1058438015@50c5c94a) in mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7
org.openmole.core.workflow.mole.MoleExecution.checkMoleExecutionIsFinished:491 - check if mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7 is finished, message queue empty true, number of jobs 1: TreeMap(0 -> capsule@138512161:task@1543925628) - TreeMap(false -> TreeSet(0))
org.openmole.core.workflow.mole.MoleExecutionMessage.dispatch:617 - processing message WithMoleExecutionSate(org.openmole.plugin.environment.batch.refresh.JobManager$$$Lambda$2497/1058438015@6b4b080c) in mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7
org.openmole.core.workflow.mole.MoleExecution.checkMoleExecutionIsFinished:491 - check if mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7 is finished, message queue empty true, number of jobs 1: TreeMap(0 -> capsule@138512161:task@1543925628) - TreeMap(false -> TreeSet(0))
org.openmole.core.workflow.mole.MoleExecutionMessage.dispatch:617 - processing message WithMoleExecutionSate(org.openmole.plugin.environment.batch.refresh.JobManager$$$Lambda$2497/1058438015@6b3b310) in mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7
org.openmole.core.workflow.mole.MoleExecution.checkMoleExecutionIsFinished:491 - check if mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7 is finished, message queue empty true, number of jobs 1: TreeMap(0 -> capsule@138512161:task@1543925628) - TreeMap(false -> TreeSet(0))
org.openmole.core.workflow.mole.MoleExecutionMessage.dispatch:617 - processing message WithMoleExecutionSate(org.openmole.plugin.environment.batch.refresh.JobManager$$$Lambda$2497/1058438015@4b7ad969) in mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7
org.openmole.core.workflow.mole.MoleExecution.checkMoleExecutionIsFinished:491 - check if mole execution org.openmole.core.workflow.mole.MoleExecution@652e8ed7 is finished, message queue empty true, number of jobs 1: TreeMap(0 -> capsule@138512161:task@1543925628) - TreeMap(false -> TreeSet(0))
```

Last, although no error get reported in the Environments pane in openmole, digging a bit in the .openmole folder on the distant cluster, I found the temporary files that openmole creates to run the jobs, including the ".pbs" script, and files ending in .err and .out, that I suppose contain the jobs stdout and stderr. Here is the content of the .err file:
```
Aug 14, 2019 4:41:20 PM org.openmole.runtime.SimExplorer$ $anonfun$run$3
WARNING: Error loading bundle envplugins/plugin6.jar
org.openmole.core.exception.InternalProcessingError: Installing bundle envplugins/plugin6.jar
        at org.openmole.core.pluginmanager.PluginManager$.installBundle(PluginManager.scala:193)
        at org.openmole.core.pluginmanager.PluginManager$.$anonfun$tryLoad$3(PluginManager.scala:113)
        at scala.util.Try$.apply(Try.scala:209)
        at org.openmole.core.pluginmanager.PluginManager$.$anonfun$tryLoad$2(PluginManager.scala:113)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike.map(TraversableLike.scala:233)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.openmole.core.pluginmanager.PluginManager$.tryLoad(PluginManager.scala:113)
        at org.openmole.runtime.SimExplorer$.$anonfun$run$1(SimExplorer.scala:102)
        at scala.Option.foreach(Option.scala:257)
        at org.openmole.runtime.SimExplorer$.run(SimExplorer.scala:83)
        at org.openmole.runtime.SimExplorer.run(SimExplorer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openmole.launcher.Launcher.main(Launcher.java:147)
Caused by: org.osgi.framework.BundleException: A bundle is already installed with the name "org.openmole.tool.exception" and version "10.0.0.SNAPSHOT"
        at org.eclipse.osgi.container.ModuleContainer.install(ModuleContainer.java:303)
        at org.eclipse.osgi.storage.Storage.install(Storage.java:682)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:149)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:142)
        at org.openmole.core.pluginmanager.PluginManager$.installBundle(PluginManager.scala:188)
        ... 20 more

Aug 14, 2019 4:41:20 PM org.openmole.runtime.SimExplorer$ $anonfun$run$3
WARNING: Error loading bundle envplugins/plugin9.jar
org.openmole.core.exception.InternalProcessingError: Installing bundle envplugins/plugin9.jar
        at org.openmole.core.pluginmanager.PluginManager$.installBundle(PluginManager.scala:193)
        at org.openmole.core.pluginmanager.PluginManager$.$anonfun$tryLoad$3(PluginManager.scala:113)
        at scala.util.Try$.apply(Try.scala:209)
        at org.openmole.core.pluginmanager.PluginManager$.$anonfun$tryLoad$2(PluginManager.scala:113)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike.map(TraversableLike.scala:233)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.openmole.core.pluginmanager.PluginManager$.tryLoad(PluginManager.scala:113)
        at org.openmole.runtime.SimExplorer$.$anonfun$run$1(SimExplorer.scala:102)
        at scala.Option.foreach(Option.scala:257)
        at org.openmole.runtime.SimExplorer$.run(SimExplorer.scala:83)
        at org.openmole.runtime.SimExplorer.run(SimExplorer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openmole.launcher.Launcher.main(Launcher.java:147)
Caused by: org.osgi.framework.BundleException: A bundle is already installed with the name "org.openmole.tool.osgi" and version "10.0.0.SNAPSHOT"
        at org.eclipse.osgi.container.ModuleContainer.install(ModuleContainer.java:303)
        at org.eclipse.osgi.storage.Storage.install(Storage.java:682)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:149)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:142)
        at org.openmole.core.pluginmanager.PluginManager$.installBundle(PluginManager.scala:188)
        ... 20 more

``` 

Thanks for your help!

**Comment by romainreuillon** [comment]
PBSPro not been tested properly yet. We'll do that together this week. Do you have access to this cluster ?

**Comment by guillaumecherel** [comment]
Yes, I have access to it. We can test it this week, thanks.
