### ISSUE TITLE
Could not kill job

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#45]
Every time a job finishes, I get the following error message (log level FINE). I know the error is not crucial and the workflow continues with the execution just fine, however, the number of watched jobs is updated a bit later only and furthermore would I prefer not to see any errors in the output if they have been dealt with. It may also be worth looking into why the exception is not handled.

```
May 06, 2015 5:03:08 AM org.openmole.core.batch.refresh.KillerActor$$anonfun$receive$1 apply$mcV$sp
FINE: Could not kill job.
java.io.IOException: Error rm /homes/as12312/.openmole/.tmp/ssh/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1430884865326/70e9a55e-ccee-44bb-8f04-ea0c753c5b67/fbefd460-9db9-476d-8f0c-9eb693fe1530.slurm
	at fr.iscpif.gridscale.storage.Storage$class.wrapException(Storage.scala:65)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.wrapException(SLURMJobService.scala:42)
	at fr.iscpif.gridscale.ssh.SSHStorage$class.rmFileWithClient(SSHStorage.scala:97)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.rmFileWithClient(SLURMJobService.scala:42)
	at fr.iscpif.gridscale.slurm.SLURMJobService$$anonfun$purge$1.apply(SLURMJobService.scala:89)
	at fr.iscpif.gridscale.slurm.SLURMJobService$$anonfun$purge$1.apply(SLURMJobService.scala:88)
	at fr.iscpif.gridscale.ssh.SSHHost$$anonfun$withSftpClient$1.apply(SSHHost.scala:60)
	at fr.iscpif.gridscale.ssh.SSHHost$$anonfun$withSftpClient$1.apply(SSHHost.scala:58)
	at fr.iscpif.gridscale.ssh.SSHConnectionCache$class.withConnection(SSHConnectionCache.scala:28)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.withConnection(SLURMJobService.scala:42)
	at fr.iscpif.gridscale.ssh.SSHHost$class.withSftpClient(SSHHost.scala:57)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.withSftpClient(SLURMJobService.scala:42)
	at fr.iscpif.gridscale.slurm.SLURMJobService$class.purge(SLURMJobService.scala:88)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.purge(SLURMJobService.scala:42)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$1.purge(SLURMJobService.scala:42)
	at org.openmole.plugin.environment.gridscale.GridScaleJobService$class._purge(GridScaleJobService.scala:32)
	at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1._purge(SLURMEnvironment.scala:80)
	at org.openmole.core.batch.jobservice.JobService$class.purge(JobService.scala:48)
	at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1.purge(SLURMEnvironment.scala:80)
	at org.openmole.core.batch.jobservice.BatchJob$class.kill(BatchJob.scala:56)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$3.org$openmole$core$batch$jobservice$BatchJobId$$super$kill(SLURMJobService.scala:74)
	at org.openmole.core.batch.jobservice.BatchJobId$class.kill(BatchJobId.scala:26)
	at org.openmole.plugin.environment.slurm.SLURMJobService$$anon$3.kill(SLURMJobService.scala:74)
	at org.openmole.core.batch.refresh.KillerActor$$anonfun$receive$1$$anonfun$apply$mcV$sp$1.apply(KillerActor.scala:34)
	at org.openmole.core.batch.refresh.KillerActor$$anonfun$receive$1$$anonfun$apply$mcV$sp$1.apply(KillerActor.scala:33)
	at org.openmole.core.batch.control.UsageControl$class.tryWithToken(UsageControl.scala:28)
	at org.openmole.plugin.environment.slurm.SLURMEnvironment$$anon$1.tryWithToken(SLURMEnvironment.scala:80)
	at org.openmole.core.batch.refresh.KillerActor$$anonfun$receive$1.apply$mcV$sp(KillerActor.scala:33)
	at org.openmole.core.batch.refresh.KillerActor$$anonfun$receive$1.apply(KillerActor.scala:31)
	at org.openmole.core.batch.refresh.KillerActor$$anonfun$receive$1.apply(KillerActor.scala:31)
	at org.openmole.core.batch.refresh.package$.withRunFinalization(package.scala:23)
	at org.openmole.core.batch.refresh.KillerActor.receive(KillerActor.scala:31)
	at org.openmole.core.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:85)
	at org.openmole.core.batch.refresh.JobManager$$anonfun$1$$anon$1.run(JobManager.scala:63)
Caused by: net.schmizz.sshj.sftp.SFTPException: No such file
	at net.schmizz.sshj.sftp.Response.error(Response.java:113)
	at net.schmizz.sshj.sftp.Response.ensureStatusIs(Response.java:106)
	at net.schmizz.sshj.sftp.Response.ensureStatusPacketIsOK(Response.java:99)
	at net.schmizz.sshj.sftp.SFTPEngine.remove(SFTPEngine.java:199)
	at net.schmizz.sshj.sftp.SFTPClient.rm(SFTPClient.java:129)
	at fr.iscpif.gridscale.ssh.SSHStorage$$anonfun$rmFileWithClient$1.apply$mcV$sp(SSHStorage.scala:98)
	at fr.iscpif.gridscale.ssh.SSHStorage$$anonfun$rmFileWithClient$1.apply(SSHStorage.scala:98)
	at fr.iscpif.gridscale.ssh.SSHStorage$$anonfun$rmFileWithClient$1.apply(SSHStorage.scala:98)
	at fr.iscpif.gridscale.storage.Storage$class.wrapException(Storage.scala:63)
	... 33 more
```

**Comment by jopasserat** [comment]
The stacktrace should not appear anymore (fixed in GridScale fbd74233d5cfb5183c2dadbea22ab45df5ee237a).

Could you please confirm if it's fine with you?

The "Could not kill job" is probably due to the fact that the job had already completed when OpenMOLE attempted to kill it.

**Comment by schuhschuh** [comment]
> The "Could not kill job" is probably due to the fact that the job had already completed when OpenMOLE attempted to kill it.

Yes, that's what I think was the cause for this.

> Could you please confirm if it's fine with you?

Sure, that'll take me some time to get back to you, though. I was in the progress of refactoring my plugin when I had to stop working on it (meaning not sure if I can simply re-run it) and focus on other tasks...

**Comment by romainreuillon** [comment]
Fixed
