### ISSUE TITLE
pass random seed to R (no emergency)

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#459]
Dear beloved OpenMole team,

I'm using stochastic algorithms in an `RTask`, so I would need to control the seed of `R`. This is usually done by using the `set.seed()` R function taking an integer as a seed. 

So I wrote this minimalistic workflow (on version 12.snapshot)
```
val seed = Val[Long]

// Task
val rTask1 = RTask("""
    set.seed(seed)

    # Here you write code in R
    f = function(x){
        x+1
    }
     j = f(2)
""") set (
    inputs += seed.mapped    
)

// Workflow
Replication(
  evaluation = rTask1, // the model to run
  seed = seed, // the seed variable
  sample = 100
)
```

Yet a problem happens because seed is a Long in OpenMole and an Int in OpenMole. 
If you run the previous workflow long enough, it fails with the following output

```
Error in set.seed(seed) : supplied seed is not a valid integer
In addition: Warning message:
In set.seed(seed) : NAs introduced by coercion to integer range
Execution halted
```

and stacktrace 
```
Error in rTask1@1972564237 for context values {openmole$seed=7311483310106405216, seed=-3911434648978304477}
org.openmole.core.exception.InternalProcessingError: Error in rTask1@1972564237 for context values {openmole$seed=7311483310106405216, seed=-3911434648978304477}
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:126)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:243)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:244)
	at org.openmole.core.workflow.task.Task.perform(Task.scala:104)
	at org.openmole.core.workflow.task.Task.perform$(Task.scala:102)
	at org.openmole.plugin.task.r.RTask.perform(RTask.scala:98)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:90)
	at org.openmole.core.workflow.execution.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:62)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at org.openmole.core.workflow.execution.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:58)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:123)
	at org.openmole.core.workflow.execution.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:119)
	at org.openmole.core.workflow.execution.LocalExecutor.run(LocalExecutor.scala:54)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openmole.core.exception.UserBadDataError: Process exited a non 0 return code (1), you can chose ignore this by settings errorOnReturnValue = true
	at org.openmole.plugin.task.container.ContainerTask.$anonfun$process$8(ContainerTask.scala:337)
	at org.openmole.tool.cache.Pool.apply(Pool.scala:49)
	at org.openmole.plugin.task.container.ContainerTask.$anonfun$process$1(ContainerTask.scala:311)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:243)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:244)
	at org.openmole.plugin.task.r.RTask.$anonfun$process$8(RTask.scala:184)
	at org.openmole.core.workspace.TmpDirectory.withTmpFile(TmpDirectory.scala:24)
	at org.openmole.plugin.task.r.RTask.$anonfun$process$7(RTask.scala:141)
	at org.openmole.core.workspace.TmpDirectory.withTmpFile(TmpDirectory.scala:24)
	at org.openmole.plugin.task.r.RTask.$anonfun$process$1(RTask.scala:140)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:243)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:244)
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:123)
	... 13 more
```

If I try to make the openmole variable seed an Int, it makes the Replication task unsatisfied. 

Do you have a recommandation?

Sam

**Comment by samthiriot** [comment]
I have a potential fix: in R, apply a modulo with the max acceptable integer value `set.seed(seed %% .Machine$integer.max)`. This should preserve reproducibility when reusing the same seed, and statistical distribution of values. 

Does that sound correct to you? 

Sam

**Comment by romainreuillon** [comment]
Val[Int] are supposed to be supported by the Replication method. I just tryed it with the following script ind it work okay:

```scala
// Define the variables that are transmitted between the tasks
val seed = Val[Int]
val pi = Val[Double]
val piAvg = Val[Double]


// Define the model task that computes an estimation of pi
val model =
  ScalaTask("""
    |val random = Random(seed)
    |val points = 100000
    |
    |val inside =
    |  for {
    |    i <- (0 until points).toIterator
    |    x = random.nextDouble()
    |    y = random.nextDouble()
    |  } yield { (x * x) + (y * y) }
    |val pi = (inside.count(_ < 1).toDouble / points) * 4
    |""".stripMargin) set (
      inputs += seed,
      outputs += pi
    )

Replication(
  evaluation = model,
  seed = seed,
  sample = 10
) hook(workDirectory / "output.csv")
```

Do you have the exact error that you obtain when using an Val[Int] ?

**Comment by samthiriot** [comment]
Thanks a lot Romain,
I did the beginner stupid error: `Val[Integer]`  instead of  `Val[Int]`
You're true, it works perfectly with the Int version.
Sorry for inconvenience :-/
