### ISSUE TITLE
R task error on nixos

### ISSUE THREAD

**Issue by guillaumecherel** [openmole/openmole#463]
Still climbing the slope of packaging openmole for NixOS. Simple scripts with ScalaTasks work. 

I'm getting the following error when running the Hello World in R from the market place. I'm pretty sure I'm missing some dependency, but I don't know which one (I installed singularity and R). Does one of you have an idea?

```
Process exited a non 0 return code (1)
org.openmole.core.exception.UserBadDataError: Process exited a non 0 return code (1)
	at org.openmole.plugin.task.container.ContainerTask$.executeInstall(ContainerTask.scala:219)
	at org.openmole.plugin.task.container.ContainerTask$.$anonfun$prepare$1(ContainerTask.scala:208)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLockInDirectory$1(package.scala:412)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$5(package.scala:402)
	at org.openmole.tool.stream.package$.withClosable(package.scala:117)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$3(package.scala:400)
	at org.openmole.tool.stream.package$.withClosable(package.scala:117)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$1(package.scala:399)
	at org.openmole.tool.lock.LockRepository.withLock(LockRepository.scala:54)
	at org.openmole.tool.file.FilePackage$FileDecorator.withLock(package.scala:399)
	at org.openmole.tool.file.FilePackage$FileDecorator.withLockInDirectory(package.scala:412)
	at org.openmole.plugin.task.container.ContainerTask$.prepare(ContainerTask.scala:197)
	at org.openmole.plugin.task.r.RTask$.apply(RTask.scala:82)
	at $line100000019.$read$$iw$$anon$2.run(<console>:22)
	at org.openmole.core.project.Compiled.eval(Project.scala:200)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$synchronousCompilation$7(ApiImpl.scala:355)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:123)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$synchronousCompilation$6(ApiImpl.scala:355)
	at org.openmole.gui.ext.server.utils$.catchAll(utils.scala:332)
	at org.openmole.gui.server.core.ApiImpl.synchronousCompilation(ApiImpl.scala:355)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$asynchronousCompilation$1(ApiImpl.scala:390)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by romainreuillon** [comment]
Did you install [singularity](https://sylabs.io/) ?

**Comment by guillaumecherel** [comment]
Yes I did, as well as R.

Le 19 août 2020 15:17:25 CEST, Romain Reuillon <notifications@github.com> a écrit :
>Did you install [singularity](https://sylabs.io/) ?
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openmole/openmole/issues/463#issuecomment-676341104

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
