### ISSUE TITLE
RTask failing to download an image because of proxy authentification error: unclear error message

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#467]
Dear beloved OpenMole community,

when an RTask is executed and tries to download data from the web, if the proxy is not authentified (and maybe when any other network connection occurs?), it fails with a cryptic error message:
```
None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at container.Registry$Token$.withToken(Registry.scala:166)
	at container.Registry$.downloadManifest(Registry.scala:215)
	at container.ImageDownloader$.$anonfun$downloadContainerImage$2(ImageDownloader.scala:121)
	at container.tool.Retry$.retry(Retry.scala:8)
	at container.tool.Retry$.retry(Retry.scala:17)
	at container.ImageDownloader$.downloadContainerImage(ImageDownloader.scala:121)
	at org.openmole.plugin.task.container.ContainerTask$.downloadImage(ContainerTask.scala:77)
	at org.openmole.plugin.task.container.ContainerTask$.localImage(ContainerTask.scala:240)
	at org.openmole.plugin.task.container.ContainerTask$.$anonfun$prepare$1(ContainerTask.scala:220)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLockInDirectory$1(package.scala:412)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$5(package.scala:402)
	at org.openmole.tool.stream.package$.withClosable(package.scala:117)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$3(package.scala:400)
	at org.openmole.tool.stream.package$.withClosable(package.scala:117)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$1(package.scala:399)
	at org.openmole.tool.lock.LockRepository.withLock(LockRepository.scala:54)
	at org.openmole.tool.file.FilePackage$FileDecorator.withLock(package.scala:399)
	at org.openmole.tool.file.FilePackage$FileDecorator.withLockInDirectory(package.scala:412)
	at org.openmole.plugin.task.container.ContainerTask$.prepare(ContainerTask.scala:210)
	at org.openmole.plugin.task.r.RTask$.apply(RTask.scala:82)
	at $line100000019.$read$$iw$$anon$2.run(<console>:21)
	at org.openmole.core.project.Compiled.eval(Project.scala:200)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$synchronousCompilation$7(ApiImpl.scala:355)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:123)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$synchronousCompilation$6(ApiImpl.scala:355)
	at org.openmole.gui.ext.server.utils$.catchAll(utils.scala:332)
	at org.openmole.gui.server.core.ApiImpl.synchronousCompilation(ApiImpl.scala:355)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$asynchronousCompilation$1(ApiImpl.scala:390)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Users not familiar with technics might not find the solution easily. Would it be possible to raise a more explicit error?

Tks 

Sam

**Comment by romainreuillon** [comment]
These fix in container should fix this pb : https://github.com/openmole/container/commit/11f5f344212c3db0029c98cc9155a27056a77929

**Comment by samthiriot** [comment]
Hello @romainreuillon 

thanks for your effort on this small topic
I'm afraid there is still one case where a proper error message is not sent. I tried with the last image 12 snapshot from 14/09/2020, and got the following exception:
```
None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at container.Registry$Token$.withToken(Registry.scala:166)
	at container.Registry$.downloadManifest(Registry.scala:215)
	at container.ImageDownloader$.$anonfun$downloadContainerImage$2(ImageDownloader.scala:121)
	at container.tool.Retry$.retry(Retry.scala:8)
	at container.tool.Retry$.retry(Retry.scala:17)
	at container.ImageDownloader$.downloadContainerImage(ImageDownloader.scala:121)
	at org.openmole.plugin.task.container.ContainerTask$.downloadImage(ContainerTask.scala:77)
	at org.openmole.plugin.task.container.ContainerTask$.localImage(ContainerTask.scala:240)
	at org.openmole.plugin.task.container.ContainerTask$.$anonfun$prepare$1(ContainerTask.scala:220)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLockInDirectory$1(package.scala:412)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$5(package.scala:402)
	at org.openmole.tool.stream.package$.withClosable(package.scala:117)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$3(package.scala:400)
	at org.openmole.tool.stream.package$.withClosable(package.scala:117)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withLock$1(package.scala:399)
	at org.openmole.tool.lock.LockRepository.withLock(LockRepository.scala:54)
	at org.openmole.tool.file.FilePackage$FileDecorator.withLock(package.scala:399)
	at org.openmole.tool.file.FilePackage$FileDecorator.withLockInDirectory(package.scala:412)
	at org.openmole.plugin.task.container.ContainerTask$.prepare(ContainerTask.scala:210)
	at org.openmole.plugin.task.r.RTask$.apply(RTask.scala:83)
	at $line100000019.$read$$iw$_83d3afe2673ee7e890ace486efac1bdc1f99a233$.taskPlotLastParetoFront$lzycompute(<console>:22)
	at $line100000019.$read$$iw$_83d3afe2673ee7e890ace486efac1bdc1f99a233$.taskPlotLastParetoFront(<console>:48)
	at $line100000019.$read$$iw$$anon$5.run(<console>:109)
	at org.openmole.core.project.Compiled.eval(Project.scala:200)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$synchronousCompilation$7(ApiImpl.scala:366)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:123)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$synchronousCompilation$6(ApiImpl.scala:366)
	at org.openmole.gui.ext.server.utils$.catchAll(utils.scala:332)
	at org.openmole.gui.server.core.ApiImpl.synchronousCompilation(ApiImpl.scala:366)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$asynchronousCompilation$1(ApiImpl.scala:405)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
One more time, no urge nor importance from my point of view, this is only I guess "nice to have" for new users. 

Sam
