### ISSUE TITLE
cannot pass a Boolean to an RTask

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#469]
Dear beloved OpenMole community,

I try to pass a Boolean as an input of a `RTask`, but I don't achieve to make it work. I get a runtime error `org.openmole.core.exception.UserBadDataError: Value true of type class java.lang.Boolean is not convertible to JSON`.

A test script:
```
val b = Val[Boolean]

val rTaskPlot = RTask("""
    print(b)
    """) set (
    inputs += b.mapped,
    b := true
)
rTaskPlot
```

The error:
```
Error in rTaskPlot@1308922611 for context values {b=true, openmole$seed=-3451302866873884307}
org.openmole.core.exception.InternalProcessingError: Error in rTaskPlot@1308922611 for context values {b=true, openmole$seed=-3451302866873884307}
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:126)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:243)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:244)
	at org.openmole.core.workflow.task.Task.perform(Task.scala:104)
	at org.openmole.core.workflow.task.Task.perform$(Task.scala:102)
	at org.openmole.plugin.task.r.RTask.perform(RTask.scala:99)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:90)
	at org.openmole.core.workflow.execution.LocalExecutor.$anonfun$run$2(LocalExecutor.scala:62)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at org.openmole.core.workflow.execution.LocalExecutor.$anonfun$run$1(LocalExecutor.scala:58)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:123)
	at org.openmole.core.workflow.execution.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:119)
	at org.openmole.core.workflow.execution.LocalExecutor.run(LocalExecutor.scala:54)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openmole.core.exception.UserBadDataError: Value true of type class java.lang.Boolean is not convertible to JSON
	at org.openmole.plugin.tool.json.package$.toJSONValue(package.scala:24)
	at org.openmole.plugin.tool.json.package$.$anonfun$toJSONValue$1(package.scala:21)
	at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:924)
	at org.openmole.plugin.tool.json.package$.toJSONValue(package.scala:21)
	at org.openmole.plugin.tool.json.package$.$anonfun$toJSONValue$1(package.scala:21)
	at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:924)
	at org.openmole.plugin.tool.json.package$.toJSONValue(package.scala:21)
	at org.openmole.plugin.task.r.RTask.writeInputsJSON$1(RTask.scala:125)
	at org.openmole.plugin.task.r.RTask.$anonfun$process$8(RTask.scala:149)
	at org.openmole.core.workspace.TmpDirectory.withTmpFile(TmpDirectory.scala:24)
	at org.openmole.plugin.task.r.RTask.$anonfun$process$7(RTask.scala:142)
	at org.openmole.core.workspace.TmpDirectory.withTmpFile(TmpDirectory.scala:24)
	at org.openmole.plugin.task.r.RTask.$anonfun$process$1(RTask.scala:141)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:243)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:244)
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:123)
	... 13 more
```

Maybe I'm using a wrong type somewhere? 

Tks !

Sam

**Comment by samthiriot** [comment]
Wonderful Romain, thanks! 

I'll try it when it'll be published as a container. 
I guess we can close the bug right now. 

Sam
