### ISSUE TITLE
[Plugin][Enh] Add ssh proxy option

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#491]
Http proxy was introduced as an option for downloading R packages for examples; in a different context it would be very useful to integrate ssh proxies (`ProxyJump`, or `-J` flag) for ssh environment or cluster environments.

**Comment by JusteRaimbault** [comment]
This was implemented in gridscale by [8c6e6121](https://github.com/openmole/gridscale/commit/8c6e6121aa62189cc419bcc831107698e3a670a5)
and in openmole by [fa1826b6](https://github.com/openmole/openmole/commit/fa1826b6215afa0dee897f2a7c0de1c008d196ff)
It works in practice - was able to run large scale simulations on a SGE environment behind a bastion; however I am not sure everything is totally clean when dealing with closing connections and everything - getting sometimes the exceptions below in the openmole log - so leaving this open until more testing is done.

```
13:55:09.449 [Thread-242] ERROR net.schmizz.concurrent.Promise - <<chan#33159 / close>> woke to: net.schmizz.sshj.connection.ConnectionException: Disconnected
13:55:09.482 [Thread-77] ERROR net.schmizz.concurrent.Promise - <<chan#33162 / close>> woke to: net.schmizz.sshj.connection.ConnectionException: Disconnected
09:37:15.409 [sshj-Reader-$HOST/$IPV4:22] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
        at net.schmizz.sshj.transport.Reader.run(Reader.java:58)
10:14:08.368 [sshj-Reader-$PROXYHOST/$IPV4:22] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Connection reset
java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:50)

```
