### ISSUE TITLE
Error runing Executable example

### ISSUE THREAD

**Issue by javierdvalle** [openmole/openmole#493]
Hi, I am new to openmole. I am trying to run the Executable example: [Containers from the docker hub](https://openmole.org/Executable.html#Containersfromthedockerhub) 

I get this error:

```
org.openmole.core.console.ScalaREPL$CompilationError: (line 6) type mismatch;
 found   : Unit
 required: org.openmole.core.workflow.composition.DSL
}
^
Compiling code:

class _928a51240d14d2812de511800f8e3b6d8303449eClass {
lazy val _imports = new {

}
}
lazy val _928a51240d14d2812de511800f8e3b6d8303449e = new _928a51240d14d2812de511800f8e3b6d8303449eClass
           
     

new org.openmole.core.project.Project.OMSScript {

def run(): org.openmole.core.workflow.composition.DSL = {
import _928a51240d14d2812de511800f8e3b6d8303449e._imports._
val container = ContainerTask(
  "python:3.6-stretch",
  """python -c 'print("splendid!")'"""
)

}
}
         
	at org.openmole.core.console.ScalaREPL$CompilationError.copy(ScalaREPL.scala:70)
	at org.openmole.core.console.ScalaREPL$CompilationError$$anon$2.$anonfun$modifyF$2(ScalaREPL.scala:70)
	at cats.package$$anon$1.map(package.scala:48)
	at org.openmole.core.console.ScalaREPL$CompilationError$$anon$2.modifyF(ScalaREPL.scala:70)
	at org.openmole.core.console.ScalaREPL$CompilationError$$anon$2.modifyF(ScalaREPL.scala:70)
	at monocle.PLens$$anon$4.modifyF(Lens.scala:189)
	at monocle.PTraversal$$anon$2.modifyF(Traversal.scala:119)
	at monocle.PTraversal$$anon$2.modifyF(Traversal.scala:119)
	at monocle.PTraversal$$anon$2.modifyF(Traversal.scala:119)
	at monocle.PTraversal$$anon$2.modifyF(Traversal.scala:119)
	at monocle.PTraversal.$anonfun$modify$1(Traversal.scala:83)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at org.openmole.core.project.Project$.compile$1(Project.scala:175)
	at org.openmole.core.project.Project$.compile(Project.scala:181)
	at org.openmole.gui.server.core.ApiImpl.synchronousCompilation(ApiImpl.scala:353)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$asynchronousCompilation$1(ApiImpl.scala:405)
	at org.openmole.core.threadprovider.ThreadProvider$RunClosure.run(ThreadProvider.scala:24)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.script.ScriptException: Compile-time error (result is Error)
	at org.openmole.core.console.OMScripted.$anonfun$compile$3(OMScripted.scala:124)
	at scala.Option.getOrElse(Option.scala:201)
	at org.openmole.core.console.OMScripted.$anonfun$compile$1(OMScripted.scala:122)
	at org.openmole.core.console.OMScripted.withCompileContext(OMScripted.scala:94)
	at org.openmole.core.console.OMScripted.compile(OMScripted.scala:108)
	at org.openmole.core.console.OMScripted.compile(OMScripted.scala:133)
	at org.openmole.core.console.ScalaREPL.compile(ScalaREPL.scala:230)
	at org.openmole.core.project.Project$.compile$1(Project.scala:152)
	... 9 more
```

I am using openmole version 11.5, runing on Ubuntu 20.04 with the openjdk. 

Java:

    $ java -version
    openjdk version "15" 2020-09-15
    OpenJDK Runtime Environment (build 15+36-1562)
    OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

**Comment by javierdvalle** [comment]
After digging a bit, I found the code is being copied into a function, that expects the variable "container" to be returned

I suggest the example should be modified to return the container explicitly:

```
val container = ContainerTask(
  "python:3.6-stretch",
  """python -c 'print("splendid!")'"""
)

return container // <-- add this line
``` 

Or just return it implicitly:

```
ContainerTask(
  "python:3.6-stretch",
  """python -c 'print("splendid!")'"""
)
```

**Comment by romainreuillon** [comment]
Dear @javierdvalle,

you got the right idea.  An OpenMOLE script must end with the method or task you want to execute. You may not use the return keyword. 

This is legit as well:

```scala
val container = ContainerTask(
  "python:3.6-stretch",
  """python -c 'print("splendid!")'"""
)

container
```

cheers,
Romain
