### ISSUE TITLE
Windows listFiles, MaxPermSize & InaccessibleObjectException

### ISSUE THREAD

**Issue by ScriBanana** [openmole/openmole#513]
Hi everyone,

I'm having several issues running OpenMOLE on Windows, which may or may not be linked to one another.

*Specs :*
Windows 10, JRE and JDK as up to date as can be (17.0.1).
OM 14.0 (built on 02/12/21, dev-14 branch iirc). Tried with the 13.0 public release – same issues.

*Problems :*
1.  OM refuses to build because of some apparently outdated JVM parameters : `-XX:MaxPermSize=128M` (returns : `Unrecognized VM option 'MaxPermSize=128M'` upon running the BAT file). I do thus have to remove the corresponding two lines from the file in order to run it.
2. OM works only when the openmole.js file, in ~/.openmole/persistent/webui, doesn't exist, _i.e._ on a fresh install or when I delete it manually. When I don't (when I try to run OM after closing it a first time), I get the following :
```batch
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.openmole.launcher.Launcher.main(Launcher.java:147)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public void sun.nio.fs.WindowsDirectoryStream.close() throws java.io.IOException accessible: module java.base does not "opens sun.nio.fs" to unnamed module @30517a57
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at scala.reflect.package$.ensureAccessible(package.scala:58)
        at scala.runtime.ScalaRunTime$.ensureAccessible(ScalaRunTime.scala:153)
        at org.openmole.tool.stream.package$.reflMethod$Method1(package.scala:118)
        [... etc]
```
3. When it does run, the app returns the following, either on start up, when I try to mess with files and directory or when I attempt to upload something from the marketplace : `The request listFiles failed.`
4. I shall add that it is unable to establish SSH connections (which would work on other instances of OM), but that is the least of my concerns as of now.
```batch
Error authenticating to ssh server <server>:22
gridscale.authentication.AuthenticationException: Error authenticating to ssh server <server>:22
	at gridscale.authentication.AuthenticationException$.apply(AuthenticationException.scala:20)
        [...]
Caused by: gridscale.authentication.AuthenticationException: Error during ssh login/password authentication
        [...]
Caused by: net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        [...]
```

Voilà, I don't know what I messed up :)
Full logs on demand.
Cheers

**Comment by romainreuillon** [comment]
Hi @ScriBanana,

thank you for repporting all this.

1 - is fixed
2 and 3 - have been fixed
4 - Have you setup an authentication in the authentication panel (the lock on the top bar)?

cheers,
Romain

**Comment by ScriBanana** [comment]
Hi Romain,

Thanks for your responsiveness!

All the issues indeed seem to be fixed with the dev branch build. Regarding 4, it indeed was the prompt from the authentication panel. It now is functional, I don't know what caused it. A new problem seems to occur, though : there seems to not be possible to open a file in the webapp. Clicking or double-clicking a file leads to nothing.

_However_, this is not a thing when launching from a linux bash, so there is no trouble for me any more (as of now :) ) and I'm not really willing to investigate further on that windows version (that also takes way longer to load), to be honest...

I'll still provide with further infos if need be.

Thanks again
