### ISSUE TITLE
[plugin] Julia task problem 

### ISSUE THREAD

**Issue by maxcolomb** [openmole/openmole#516]
Hi ! 
I used JuliaTask for a calibration task, I extremely simplified my script till it's just a multiplication, script is validated and run, and fail. 
My OpenMole skills are not terrific but I suspect that the JuliaTask is to blame here.

Task :

```
// Input variables 
val alpha = Val[Double]
val beta = Val[Double]

// Output variables 
val Res = Val[Double]

// julia task 
 
//   val juliaTask = JuliaTask("val Res = workDirectory / \"script.jl\"") set(
val juliaTask = JuliaTask(workDirectory / "script.jl") set(
        inputs += (alpha,beta),
        outputs += (Res)  
    )

val evolution =
  NSGA2Evolution(
    genome = Seq(alpha in (0.01 to 0.99), beta in (0.01 to 0.99)),
    objective = Seq(Res),
    evaluation = juliaTask,
    parallelism = 1,
    termination = 10
  ) hook (workDirectory / "calibration")


//Definie the environment
val env = LocalEnvironment(5)

// Start a workflow with 1 task
evolution on env
```

script.jl : 

` Res = alpha*beta `

Error : 

```
Error in juliaTask@931062043 for context values {alpha=0.40969382623002293, beta=0.10199590175678871, openmole$seed=9043897359768584105}
org.openmole.core.exception.InternalProcessingError: Error in juliaTask@931062043 for context values {alpha=0.40969382623002293, beta=0.10199590175678871, openmole$seed=9043897359768584105}
	at org.openmole.core.workflow.tools.InputOutputCheck$$anonfun$perform$1.apply(InputOutputCheck.scala:126)
	at org.openmole.core.workflow.tools.InputOutputCheck$$anonfun$perform$1.apply(InputOutputCheck.scala:116)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:242)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:243)
	at org.openmole.core.workflow.task.Task.perform(Task.scala:245)
	at org.openmole.core.workflow.task.Task.perform$(Task.scala:243)
	at org.openmole.plugin.task.julia.JuliaTask.perform(JuliaTask.scala:72)
	at org.openmole.core.workflow.job.Job.perform(Job.scala:101)
	at org.openmole.core.workflow.execution.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:72)
	at org.openmole.core.workflow.execution.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:59)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at org.openmole.core.workflow.execution.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:59)
	at org.openmole.core.workflow.execution.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:55)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:123)
	at org.openmole.core.workflow.execution.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:131)
	at org.openmole.core.workflow.execution.LocalExecutor.run(LocalExecutor.scala:55)
	at java.base/java.lang.Thread.run(Thread.java:831)


Caused by: org.openmole.core.exception.UserBadDataError: Process exited a non 0 return code (1), you can chose ignore this by settings errorOnReturnValue = true
	at org.openmole.plugin.task.container.ContainerTask$$anonfun$process$1$$anonfun$apply$1.apply(ContainerTask.scala:327)
	at org.openmole.plugin.task.container.ContainerTask$$anonfun$process$1$$anonfun$apply$1.apply(ContainerTask.scala:300)
	at org.openmole.tool.cache.Pool.apply(Pool.scala:49)
	at org.openmole.plugin.task.container.ContainerTask$$anonfun$process$1.apply(ContainerTask.scala:300)
	at org.openmole.plugin.task.container.ContainerTask$$anonfun$process$1.apply(ContainerTask.scala:264)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:242)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:243)
	at org.openmole.plugin.task.julia.JuliaTask$$anonfun$process$1$$anonfun$1$$anonfun$apply$1.apply(JuliaTask.scala:165)
	at org.openmole.plugin.task.julia.JuliaTask$$anonfun$process$1$$anonfun$1$$anonfun$apply$1.apply(JuliaTask.scala:118)
	at org.openmole.core.workspace.TmpDirectory.withTmpFile(TmpDirectory.scala:24)
	at org.openmole.plugin.task.julia.JuliaTask$$anonfun$process$1$$anonfun$1.apply(JuliaTask.scala:118)
	at org.openmole.plugin.task.julia.JuliaTask$$anonfun$process$1$$anonfun$1.apply(JuliaTask.scala:117)
	at org.openmole.core.workspace.TmpDirectory.withTmpFile(TmpDirectory.scala:24)
	at org.openmole.plugin.task.julia.JuliaTask$$anonfun$process$1.apply(JuliaTask.scala:117)
	at org.openmole.plugin.task.julia.JuliaTask$$anonfun$process$1.apply(JuliaTask.scala:92)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:242)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:243)
	at org.openmole.core.workflow.tools.InputOutputCheck$$anonfun$perform$1.apply(InputOutputCheck.scala:123)
	... 16 more
```

**Comment by maxcolomb** [comment]
oops, should have checked my notification before submitting 

#509

**Comment by JusteRaimbault** [comment]
Hi Maxime! Thanks for further testing the `JuliaTask`. It was working on my side with an other dummy script with Int and String prototypes, so I suspect an issue with the conversion of doubles - checking that now with the script you provided.

**Comment by JusteRaimbault** [comment]
I get errors that variables are not defined:
```ERROR: LoadError: UndefVarError: alpha not defined
Stacktrace:
 [1] top-level scope
   @ //_generatescript_.jl:5
in expression starting at /_generatescript_.jl:5
```
it's because the inputs are not implicitly mapped - as in the Python or NetLogo tasks, you need to specify the mapping for each variable the following way:
```
val juliaTask = JuliaTask(workDirectory / "script.jl") set(
        inputs += alpha.mapped,
        inputs += beta.mapped,
        outputs += (alpha,beta),
        outputs += res.mapped
)
```
with this task your calibration script works fine.

I'm leaving the issue open as we may want to improve the user experience on this - do you think insisting on the mapping in the doc would be useful? And/or add some warning when unmapped inputs are detected? Or add some implicit conversion from any prototype to a mapped prototype in input of these tasks - this last suggestion suggests more changes, we would need to check this with @romainreuillon

**Comment by maxcolomb** [comment]
Hi !
Thanks for your answer. My task (and the more complex one) now running well : )
I was not familiar with the mapping notion,  but I check the explanation in the [NetLogo](https://next.openmole.org/NetLogo.html) doc and it is now clearer ! Maybe that could be moved into a 'variable scope' doc ? 

Also I was checking the wrong log output. I don't know if I would have figured that out by myself tho. Maybe the error can precise which between script/OM variable is not defined ? 

I don't know what your last suggestion implies, so I leave that to you !
Thanks again 
Max
