### ISSUE TITLE
Appender Logger 

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#58]
Hi,
when I start the openmole server (with no option), I get the following not blocking exception.
Thanks

14:03:35,748 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [org.openmole.core.logging.OpenMOLEAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.openmole.core.logging.OpenMOLEAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.openmole.core.logging.OpenMOLEAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:74)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:49)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:142)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:121)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:332)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
	at 	at org.openmole.core.logging.LoggerService$.init(LoggerService.scala:58)
	at 	at org.openmole.core.logging.internal.Activator.start(Activator.scala:34)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at 	at java.security.AccessController.doPrivileged(Native Method)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at 	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at 	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.ClassNotFoundException: org.openmole.core.logging.OpenMOLEAppender
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at 	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
	at 	... 36 common frames omitted
14:03:35,748 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@16:82 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.openmole.core.logging.OpenMOLEAppender
	at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.openmole.core.logging.OpenMOLEAppender
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:82)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:142)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:121)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:332)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
	at 	at org.openmole.core.logging.LoggerService$.init(LoggerService.scala:58)
	at 	at org.openmole.core.logging.internal.Activator.start(Activator.scala:34)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at 	at java.security.AccessController.doPrivileged(Native Method)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at 	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at 	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.openmole.core.logging.OpenMOLEAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:74)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:49)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
	at 	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.openmole.core.logging.OpenMOLEAppender
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at 	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
	at 	... 36 common frames omitted
14:03:35,749 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [net.schmizz.concurrent.Promise] to false
14:03:35,749 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [CatchSSH]. Did you define it below instead of above in the configuration file?
14:03:35,749 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
14:03:35,749 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
14:03:35,749 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:03:35,749 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:03:35,750 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1e6ef2b7 - Registering current configuration as safe fallback point

**Comment by romainreuillon** [comment]
Same thing happends when launching the console.

**Comment by jopasserat** [comment]
Not reproducible on a fresh build

**Comment by mathieuleclaire** [comment]
A clean in the root project does not fix it.

**Comment by romainreuillon** [comment]
Reinstalling the libs + clean, fixes it.
