### ISSUE TITLE
Sampling filter code fails to compile

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#60]
After an update of OpenMOLE master, I get the following error:

```scala
val imageSampling = (tgtIdSampling x srcIdSampling) filter ("tgtId != srcId")

val forEachImPair =
      ExplorationTask(imageSampling) set (
        name    := s"${reg.id}-ForEachImPair",
        inputs  += regId,
        outputs += regId
      )
```

```
OpenMOLE><console>:16: error: not found: value oMSeed
                  implicit lazy val oMRNG: util.Random = newRNG(oMSeed).toScala;
                                                                ^
May 18, 2015 5:06:02 PM org.openmole.core.workflow.mole.SubMoleExecution finalState
SEVERE: Error in user job execution for capsule ireg-ffd-ForEachImPair, job state is FAILED.
org.openmole.core.exception.InternalProcessingError: Error for context values in ireg-ffd-ForEachImPair {oMSeed=-8656112628508577470, regId=ireg-ffd}
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
        at org.openmole.core.workflow.task.ExplorationTask.perform(ExplorationTask.scala:55)
        at org.openmole.core.workflow.task.Task$class.perform(Task.scala:46)
        at org.openmole.core.workflow.task.ExplorationTask.perform(ExplorationTask.scala:55)
        at org.openmole.core.workflow.mole.StrainerTaskDecorator.process(Capsule.scala:139)
        at org.openmole.core.workflow.mole.StrainerTaskDecorator.perform(Capsule.scala:138)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:99)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:71)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:63)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:63)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:60)
        at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:114)
        at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.InternalProcessingError: Error compiling import org.openmole.core.workflow.tools.CodeTool._

(_input_value_context: org.openmole.core.workflow.data.Context) => {
    object input {
      var srcId = _input_value_context("srcId").asInstanceOf[Int]; var tgtId = _input_value_context("tgtId").asInstanceOf[Int]
    }
    import input._
    implicit lazy val oMRNG: util.Random = newRNG(oMSeed).toScala;
    tgtId != srcId
    
}

        at org.openmole.core.workflow.tools.ScalaCompilation$$anonfun$compile$1.apply(ScalaCompilation.scala:41)
        at scala.util.Try$.apply(Try.scala:191)
        at org.openmole.core.workflow.tools.ScalaCompilation$class.compile(ScalaCompilation.scala:37)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.compile(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.function(ScalaCompilation.scala:127)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.function(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anonfun$5.apply(ScalaCompilation.scala:170)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anonfun$5.apply(ScalaCompilation.scala:170)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.compiled(ScalaCompilation.scala:170)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.compiled(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.compiled(ScalaCompilation.scala:182)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.compiled(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.run(ScalaCompilation.scala:185)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.run(ScalaCompilation.scala:60)
        at org.openmole.plugin.sampling.combine.ScalaSamplingFilter.apply(FilteredSampling.scala:54)
        at org.openmole.plugin.sampling.combine.FilteredSampling$$anonfun$build$1$$anonfun$apply$1.apply(FilteredSampling.scala:39)
        at org.openmole.plugin.sampling.combine.FilteredSampling$$anonfun$build$1$$anonfun$apply$1.apply(FilteredSampling.scala:39)
        at scala.collection.IndexedSeqOptimized$class.prefixLengthImpl(IndexedSeqOptimized.scala:38)
        at scala.collection.IndexedSeqOptimized$class.exists(IndexedSeqOptimized.scala:46)
        at scala.collection.mutable.WrappedArray.exists(WrappedArray.scala:35)
        at org.openmole.plugin.sampling.combine.FilteredSampling$$anonfun$build$1.apply(FilteredSampling.scala:39)
        at org.openmole.plugin.sampling.combine.FilteredSampling$$anonfun$build$1.apply(FilteredSampling.scala:39)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:415)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at org.openmole.core.workflow.task.ExplorationTask.process(ExplorationTask.scala:63)
        at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
        at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:46)
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
        ... 14 more
Caused by: org.openmole.core.exception.UserBadDataError: Error while compiling:
not found: value oMSeed
                  implicit lazy val oMRNG: util.Random = newRNG(oMSeed).toScala;
                                                                ^
on line 16
        at org.openmole.core.console.ScalaREPL.eval(ScalaREPL.scala:70)
        ... 45 more
```

**Comment by romainreuillon** [comment]
It should be fixed now.

**Comment by schuhschuh** [comment]
Thanks! I'll remove my temporary fix of commenting the line and try again.

**Comment by schuhschuh** [comment]
Can confirm this is fixed.
