### ISSUE TITLE
Conditional aggregation transition should receive aggregated arrays as input

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#62]
Commit b6d6fe420c22f33f0b38644195f7efaaeac8d3eb added support for a condition on an aggregation transition. In my condition, I assumed that the variables would be arrays after the aggregation also in the script that evaluates the condition. But it seems that is not the case.

```scala
def writeMeanOverlap = evaluateOverlapEnd >- (writeMean when "!dscGrpAvgValid.contains(false)")
```

```
Caused by: org.openmole.core.exception.UserBadDataError: Error while compiling:
value contains is not a member of Boolean
                  !dscGrpAvgValid.contains(false)
```

It seems at the moment the following would work instead:
```scala
def writeMeanOverlap = evaluateOverlapEnd >- (writeMean when "dscGrpAvgValid")
```
This doesn't give me a boolean indicator for each individual "evaluateOverlap" result, that I can use to either average only the valid values or not compute an average from the incomplete results at all.

```scala
val evaluateOverlapEnd =
  Capsule(
    EmptyTask() set (
      name    := s"${reg.id}-EvaluateOverlapEnd",
      inputs  += (dscValues, dscGrpAvg, dscGrpStd, jsiValues, jsiGrpAvg, jsiGrpStd),
      inputs  += (dscValuesValid, dscGrpAvgValid, dscGrpStdValid, jsiValuesValid, jsiGrpAvgValid, jsiGrpStdValid),
      outputs += (dscValues, dscGrpAvg, dscGrpStd, jsiValues, jsiGrpAvg, jsiGrpStd),
      outputs += (dscValuesValid, dscGrpAvgValid, dscGrpStdValid, jsiValuesValid, jsiGrpAvgValid, jsiGrpStdValid)
    ),
    strainer = true
  )
```

**Comment by schuhschuh** [comment]
This issue still could be valid, but in my particular use case I figured it's probably best not to apply the condition on the aggregation, which might work different from what I expected:

```scala
    // Calculate mean of values over all registration results computed with a fixed set of parameters
    def calcMean(value: Prototype[Array[Double]], valueValid: Prototype[Boolean],
                 mean:  Prototype[Array[Double]], meanValid:  Prototype[Boolean]) =
      ScalaTask(
        s"""
           | val regId = input.regId.head
           | val parId = input.parId.head
           | val ${meanValid.name} = !${valueValid.name}.contains(false)
           | val ${mean.name} = if (!${meanValid.name}) Double.NaN else
           |   ${value.name}.transpose.map(_.sum / ${value.name}.head.size)
        """.stripMargin
      ) set (
        name    := s"${reg.id}-Calc${mean.name.capitalize}",
        inputs  += (regId.toArray, parId.toArray, value.toArray, valueValid.toArray),
        outputs += (regId, parId, mean, meanValid)
      )

    // Write mean values calculated over all registration results computed with a fixed set of parameters to CSV table
    def writeMean(path: String, mean: Prototype[Array[Double]], header: String) =
      EmptyTask() set (
        name    := s"${reg.id}-Write${mean.name.capitalize}",
        inputs  += (regId, parId, mean),
        outputs += (regId, parId, mean)
      ) hook (
        AppendToCSVFileHook(path, regId, parId, mean) set (
          csvHeader := "Registration,Parameters," + header,
          singleRow := true
        )
      )

def writeMeanOverlap =
  evaluateOverlapEnd >- (
    calcMean(dscGrpAvg, dscGrpAvgValid, dscRegAvg, dscRegAvgValid) --
      writeMean(dscRegAvgCsvPath, dscRegAvg, header = groups) when "dscRegAvgValid",
    calcMean(jsiGrpAvg, jsiGrpAvgValid, jsiRegAvg, jsiRegAvgValid) --
      writeMean(jsiRegAvgCsvPath, jsiRegAvg, header = groups) when "jsiRegAvgValid"
  )
```

**Comment by schuhschuh** [comment]
But actually I still cannot use the above "workaround". I don't see why the boolean variables in the when condition script are not available. I added them even as input and output of the EmptyTask created by the writeMean function.

```
May 18, 2015 6:57:58 PM org.openmole.core.workflow.mole.SubMoleExecution jobFinished
SEVERE: Error in submole execution
org.openmole.core.exception.InternalProcessingError: Error compiling import org.openmole.core.workflow.tools.CodeTool._

(_input_value_context: org.openmole.core.workflow.data.Context) => {
    object input {
      var dscGrpAvg = _input_value_context("dscGrpAvg").asInstanceOf[Array[Double]]; var dscGrpAvgValid = _input_value_context("dscGrpAvgValid").asInstanceOf[Boolean]; var dscGrpStd = _input_value_context("dscGrpStd").asInstanceOf[Array[Double]]; var dscGrpStdValid = _input_value_context("dscGrpStdValid").asInstanceOf[Boolean]; var dscValues = _input_value_context("dscValues").asInstanceOf[Array[Double]]; var dscValuesValid = _input_value_context("dscValuesValid").asInstanceOf[Boolean]; var jsiGrpAvg = _input_value_context("jsiGrpAvg").asInstanceOf[Array[Double]]; var jsiGrpAvgValid = _input_value_context("jsiGrpAvgValid").asInstanceOf[Boolean]; var jsiGrpStd = _input_value_context("jsiGrpStd").asInstanceOf[Array[Double]]; var jsiGrpStdValid = _input_value_context("jsiGrpStdValid").asInstanceOf[Boolean]; var jsiValues = _input_value_context("jsiValues").asInstanceOf[Array[Double]]; var jsiValuesValid = _input_value_context("jsiValuesValid").asInstanceOf[Boolean]; var oMSeed = _input_value_context("oMSeed").asInstanceOf[Long]; var outDof = _input_value_context("outDof").asInstanceOf[java.nio.file.Path]; var outSeg = _input_value_context("outSeg").asInstanceOf[java.nio.file.Path]; var outSegModified = _input_value_context("outSegModified").asInstanceOf[Boolean]; var parId = _input_value_context("parId").asInstanceOf[java.lang.String]; var regId = _input_value_context("regId").asInstanceOf[java.lang.String]; var srcId = _input_value_context("srcId").asInstanceOf[Int]; var srcSeg = _input_value_context("srcSeg").asInstanceOf[java.nio.file.Path]; var tgtId = _input_value_context("tgtId").asInstanceOf[Int]; var tgtSeg = _input_value_context("tgtSeg").asInstanceOf[java.nio.file.Path]
    }
    import input._
    //implicit lazy val oMRNG: util.Random = newRNG(oMSeed).toScala;
    jsiRegAvgValid
    
}

        at org.openmole.core.workflow.tools.ScalaCompilation$$anonfun$compile$1.apply(ScalaCompilation.scala:41)
        at scala.util.Try$.apply(Try.scala:191)
        at org.openmole.core.workflow.tools.ScalaCompilation$class.compile(ScalaCompilation.scala:37)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.compile(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.function(ScalaCompilation.scala:127)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.function(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anonfun$5.apply(ScalaCompilation.scala:170)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anonfun$5.apply(ScalaCompilation.scala:170)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.compiled(ScalaCompilation.scala:170)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.compiled(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.compiled(ScalaCompilation.scala:182)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.compiled(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.run(ScalaCompilation.scala:185)
        at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anon$1.run(ScalaCompilation.scala:60)
        at org.openmole.core.workflow.transition.Condition$$anon$1.evaluate(Condition.scala:39)
        at org.openmole.core.workflow.transition.Transition.isConditionTrue(Transition.scala:90)
        at org.openmole.core.workflow.transition.Transition.perform(Transition.scala:82)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:145)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1$$anonfun$apply$mcV$sp$3.apply(SubMoleExecution.scala:145)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply$mcV$sp(SubMoleExecution.scala:145)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:145)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$jobFinished$1.apply(SubMoleExecution.scala:145)
        at org.openmole.tool.lock.package$LockDecorator.apply(package.scala:28)
        at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:144)
        at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:257)
        at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$stateChanged$2(SubMoleExecution.scala:217)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:220)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:220)
        at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:89)
        at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:93)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:100)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:71)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:63)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:63)
        at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:60)
        at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:114)
        at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmole.core.exception.UserBadDataError: Error while compiling:
not found: value jsiRegAvgValid
                  jsiRegAvgValid
                  ^
on line 17
        at org.openmole.core.console.ScalaREPL.eval(ScalaREPL.scala:70)
        ... 42 more

```

**Comment by schuhschuh** [comment]
I think I've found the issue with the last posted error. I forget parenthesis to apply the "when" condition to the last task/capsule only, not the previously assembled puzzle, i.e., instead of
```scala
evaluateOverlapEnd >- (
  calcMean(dscGrpAvg, dscGrpAvgValid, dscRegAvg, dscRegAvgValid) --
    writeMean(dscRegAvgCsvPath, dscRegAvg, header = groups) when "dscRegAvgValid"
)
```
it should be
```scala
evaluateOverlapEnd >- (
  calcMean(dscGrpAvg, dscGrpAvgValid, dscRegAvg, dscRegAvgValid) --
    (writeMean(dscRegAvgCsvPath, dscRegAvg, header = groups) when "dscRegAvgValid")
)
```

**Comment by romainreuillon** [comment]
I agree with the orginal pb, it has been fixed in 63fc395130099667d13f323ccbbe70170777492a.

**Comment by schuhschuh** [comment]
I tested it and the original code compiles and runs without errors. The conditional task is yet not executed, though, which also happens with my second attempt which separates the mean calculation from appending it to the result CSV file. I had this issue before and couldn't find an explanation/solution for it. For some reason, only some of the final aggregation tasks are executed. This happens kind of at "random". Apparently only the first of all aggregations I have to write summary results is executed.

**Comment by schuhschuh** [comment]
Will try to find a test script for the issue of tasks following an aggregation not being executed and post a separate issue for it as it is unlikely related to this. Then I can get back to this and test the change related to the "when" condition on an aggregation transition.

**Comment by schuhschuh** [comment]
I was able to reproduce the issue with a simple test script, see #63.

**Comment by romainreuillon** [comment]
It was caused by a bad refactoring I did in the the event dispatcher of OpenMOLE, it is fixed now

**Comment by schuhschuh** [comment]
I confirmed that my original code with "when" condition on task directly following the aggregation now works as I had intended/expected.
