### ISSUE TITLE
Number of "failed" jobs reported by LocalEnvironment incorrect

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#66]
Even though the execution of my workflow aborts with an exception stating that the external command returned a non-zero exit code (because it indeed failed), the number of failed jobs reported by the LocalEnvironment remains 0:

```
[REPEAT 21/05/15 16:07.40] Jobs:     39 submitted,      1 running,      1 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     38 submitted,      1 running,      2 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     37 submitted,      1 running,      3 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     36 submitted,      1 running,      4 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     35 submitted,      1 running,      5 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     34 submitted,      1 running,      6 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     33 submitted,      1 running,      7 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     32 submitted,      1 running,      8 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     31 submitted,      1 running,      9 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     30 submitted,      1 running,     10 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     29 submitted,      1 running,     11 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     28 submitted,      1 running,     12 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     27 submitted,      1 running,     13 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     26 submitted,      1 running,     14 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     25 submitted,      1 running,     15 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     24 submitted,      1 running,     16 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     23 submitted,      1 running,     17 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     22 submitted,      1 running,     18 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     21 submitted,      1 running,     19 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     20 submitted,      1 running,     20 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     19 submitted,      1 running,     21 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     18 submitted,      1 running,     22 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     17 submitted,      1 running,     23 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     16 submitted,      1 running,     24 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     15 submitted,      1 running,     25 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     14 submitted,      1 running,     26 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     13 submitted,      1 running,     27 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     12 submitted,      1 running,     28 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     11 submitted,      1 running,     29 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:     10 submitted,      1 running,     30 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      9 submitted,      1 running,     31 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      8 submitted,      1 running,     32 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      7 submitted,      1 running,     33 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      6 submitted,      1 running,     34 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      5 submitted,      1 running,     35 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      4 submitted,      1 running,     36 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      3 submitted,      1 running,     37 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      2 submitted,      1 running,     38 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      1 submitted,      1 running,     39 done,      0 failed for {env=local, queue=long}
[REPEAT 21/05/15 16:07.40] Jobs:      0 submitted,      1 running,     40 done,      0 failed for {env=local, queue=long}
```

Here's the error message printed to the console (my command's error messages are written by itself to a log file instead):
```
org.openmole.core.exception.InternalProcessingError: Error for context values in nreg-RegisterImages {affDof=/Users/as12312/Data/Registrations/Workspace/MAC2012/dofs/affine/1004,1003.dof.gz, oMSeed=8795272912314764040, outDof=/Users/as12312/Data/Registrations/Workspace/MAC2012/dofs/nreg-02/1004,1003.dof.gz, outLog=/Users/as12312/Data/Registrations/Workspace/MAC2012/logs/nreg-02/1004,1003.log, parId=02, parVal=Map(NoOfBins -> 64, ControlPointSpacing -> 2.5, InterpolationMode -> Linear, NoOfResolutionLevels -> 3, SimilarityMeasure -> NMI, Lambda1 -> 0.0, Epsilon -> 1.0E-4, OptimizationMethod -> GradientDescent), phi2dof=[], regId=nreg, srcId=1003, srcIm=/Users/as12312/Data/Registrations/Dataset/MAC2012/Images/1003_3.nii.gz, template=[/Users/as12312/Data/Registrations/Bin/IRTK/nreg, ${target}, ${source}, -parin, ${config}, -dofin, ${aff}, -dofout, ${phi}], tgtId=1004, tgtIm=/Users/as12312/Data/Registrations/Dataset/MAC2012/Images/1004_3.nii.gz}
  at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
  at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:33)
  at org.openmole.core.workflow.task.Task$class.perform(Task.scala:47)
  at org.openmole.plugin.task.scala.ScalaTask.perform(ScalaTask.scala:33)
  at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:99)
  at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:70)
  at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:62)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:62)
  at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:59)
  at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:113)
  at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:59)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: java.lang.Exception: Registration returned non-zero exit code: REPEAT> "/usr/bin/time" "-p" "/Users/as12312/Data/Registrations/Bin/IRTK/nreg" "/Users/as12312/Data/Registrations/Dataset/MAC2012/Images/1004_3.nii.gz" "/Users/as12312/Data/Registrations/Dataset/MAC2012/Images/1003_3.nii.gz" "-parin" "/Users/as12312/.openmole/cotopaxi/.tmp/bddb92b2-dc88-43fa-b139-1204db22b716/dir23c45d88-5e8d-490e-990c-47adbfa77833/reg.cfg" "-dofin" "/Users/as12312/Data/Registrations/Workspace/MAC2012/dofs/affine/1004,1003.dof.gz" "-dofout" "/Users/as12312/Data/Registrations/Workspace/MAC2012/dofs/nreg-02/1004,1003.dof.gz"

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anonfun$compiled$1$$anonfun$6.apply(ScalaCompilation.scala:183)
  at org.openmole.core.workflow.tools.ScalaWrappedCompilation$$anonfun$compiled$1$$anonfun$6.apply(ScalaCompilation.scala:183)
  at org.openmole.core.workflow.tools.ScalaWrappedOutput$WrappedScala.run(ScalaCompilation.scala:92)
  at org.openmole.core.workflow.tools.ScalaWrappedOutput$WrappedScala.run(ScalaCompilation.scala:89)
  at org.openmole.core.workflow.tools.ScalaWrappedCompilation$class.run(ScalaCompilation.scala:195)
  at org.openmole.plugin.task.scala.ScalaTask.run(ScalaTask.scala:33)
  at org.openmole.plugin.task.scala.ScalaTask.processCode(ScalaTask.scala:34)
  at org.openmole.plugin.task.jvm.JVMLanguageTask$class.process(JVMLanguageTask.scala:41)
  at org.openmole.plugin.task.scala.ScalaTask.process(ScalaTask.scala:33)
  at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:47)
  at org.openmole.core.workflow.task.Task$$anonfun$perform$1.apply(Task.scala:47)
  at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
  ... 12 more
Caused by: java.lang.Exception: Registration returned non-zero exit code: REPEAT> "/usr/bin/time" "-p" "/Users/as12312/Data/Registrations/Bin/IRTK/nreg" "/Users/as12312/Data/Registrations/Dataset/MAC2012/Images/1004_3.nii.gz" "/Users/as12312/Data/Registrations/Dataset/MAC2012/Images/1003_3.nii.gz" "-parin" "/Users/as12312/.openmole/cotopaxi/.tmp/bddb92b2-dc88-43fa-b139-1204db22b716/dir23c45d88-5e8d-490e-990c-47adbfa77833/reg.cfg" "-dofin" "/Users/as12312/Data/Registrations/Workspace/MAC2012/dofs/affine/1004,1003.dof.gz" "-dofout" "/Users/as12312/Data/Registrations/Workspace/MAC2012/dofs/nreg-02/1004,1003.dof.gz"

  at $anonfun$1.apply(<console>:141)
  ... 28 more
```

**Comment by romainreuillon** [comment]
I am unsure what the failed state means for a local execution jobs. Would it mean that one of the mole-jobs of the group it is executing has thrown an exception? (Remember that jobs could be grouped event on the local env). To get this info it is possible to either listen to the moleexecution or to the molejobs.

For the remote jobs the failed status is used when the remote execution environment has failed to execute the job, not when the mole-jobs throw exceptions.

**Comment by schuhschuh** [comment]
Ok, I thought "failed" refers to when the job itself failed.
