### ISSUE TITLE
EGI: "No authentification has been initialized error message"

### ISSUE THREAD

**Issue by HKervadec** [openmole/openmole#79]
When trying to run a task on EGI:
```
Jun 30, 2015 2:05:27 PM org.openmole.core.batch.refresh.JobManager $bang
SEVERE: Error in job refresh
org.openmole.core.exception.UserBadDataError: No authentication has been initialized for EGI.
	at org.openmole.plugin.environment.egi.EGIEnvironment.authentication$lzycompute(EGIEnvironment.scala:244)
```

After checking the .openmole files:
```
[hk3315@romeo ~/<2>persistent/authentications/org.openmole.plugin.environment.egi.EGIAuthentication]
14:06 > >>> cat 0.key 
<org.openmole.plugin.environment.egi.P12Certificate>
  <cypheredPassword>super_password</cypheredPassword>
  <certificate>/homes/hk3315/.globus/grid_certificate_uk_LeSC.p12</certificate>
</org.openmole.plugin.environment.egi.P12Certificate>
```

The bug is not present if I rollback ~ 20 commits.

**Comment by romainreuillon** [comment]
The authentication has been recently refactored, you need to reset it.

**Comment by romainreuillon** [comment]
Actually I think there is a bug, I am investigating it.

**Comment by jopasserat** [comment]
works for me with the same workflow and a compiled version with head 
commit = ca12fb70a6f6c44c916b0a8e93efdac043e476ca
problem might come from 2ad41e4facdad8c8a1047b652ccd6069b2a653e6 and onwards

**Comment by romainreuillon** [comment]
I just fixed it in 32b6704272bfee4852b9a15ace32f18da4a43c7e

**Comment by romainreuillon** [comment]
There is still a bug... working on it...

**Comment by romainreuillon** [comment]
I made it working in 1e3c3abd8334f80173bcc01a32e8d893751923a0

**Comment by HKervadec** [comment]
Now EGI is working. 

On the other hand, adding a new SSHAuthentication does not seem to work anymore:
```
OpenMOLE>SSHAuthentication += LoginPassword("hk3315", encrypted, "localhost")
password             :********
password confirmation:********
java.lang.NullPointerException
  at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
  at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
  at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
  at org.openmole.core.workspace.Authentication$class.inCategory(Authentication.scala:54)
  at org.openmole.core.workspace.Workspace$$anon$1.inCategory(Workspace.scala:283)
  at org.openmole.core.workspace.Authentication$class.save(Authentication.scala:40)
  at org.openmole.core.workspace.Workspace$$anon$1.save(Workspace.scala:283)
  at org.openmole.plugin.environment.ssh.SSHAuthentication$.$plus$eq(SSHAuthentication.scala:41)
  ... 43 elided
```
