### ISSUE TITLE
Ending a script with a commentary cause NPE

### ISSUE THREAD

**Issue by HKervadec** [openmole/openmole#83]
The following script (Getting started example) runs fine:
```scala
val i = Val[Double]
val res = Val[Double]

val exploration = ExplorationTask(i in (0.0 to 100.0 by 1.0))

val model =
  ScalaTask("val res = i * 2") set (
    inputs += i,
    outputs += (i, res)
  )

val env = LocalEnvironment(4)

exploration -< (model on env hook ToStringHook())
```

But ending it with a commentary:
```scala
...
exploration -< (model on env hook ToStringHook())
// Faut mettre du beurre dans le fond du plat pour pas que le gratin colle
```

will cause the following:
```
16:30 $ >>> ~/app/openmole/openmole -c -s test
  ___                   __  __  ___  _     _____   ____
 / _ \ _ __   ___ _ __ |  \/  |/ _ \| |   | ____| | ___|
| | | | '_ \ / _ \ '_ \| |\/| | | | | |   |  _|   |___ \
| |_| | |_) |  __/ | | | |  | | |_| | |___| |___   ___) |
 \___/| .__/ \___|_| |_|_|  |_|\___/|_____|_____| |____/
      |_|
(Type :q to quit)
!SESSION 2015-07-15 16:31:19.788 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Framework arguments:  -cp /homes/hk3315/app/openmole/openmole-plugins -gp /homes/hk3315/app/openmole/openmole-plugins-gui -c -s test
Command-line arguments:  -consoleLog -cp /homes/hk3315/app/openmole/openmole-plugins -gp /homes/hk3315/app/openmole/openmole-plugins-gui -c -s test

!ENTRY org.eclipse.osgi 4 0 2015-07-15 16:31:36.947
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
	at org.openmole.console.Console.run(Console.scala:168)
	at org.openmole.ui.Application.start(Application.scala:184)
	at org.openmole.ui.Application.start(Application.scala:45)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
An error has occurred. See the log file
/homes/hk3315/.openmole/.tmp/1436974279_4012/1436974279951.log.

```

**Comment by romainreuillon** [comment]
bec1bfe5a67d48c65ede188e7fdd1bb411b2d427 fixes it.
