### ISSUE TITLE
File name extension not preserved when files are copied to remote

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#9]
I have an input File for a ScalaTask which runs an external program. This program uses the NIfTI-1 I/O library to read the NIfTI-1 image. It fails because apparently OpenMOLE copies the input image file to the remote with a cryptic random file name and “.bin” extension. Thus, the NIfTI-1 I/O library fails to find the image header file as it relies on specific file name extensions for the image header and raw image data (similar for other image processing libraries).

> "/homes/as12312/opt/bin/ireg" "/homes/as12312/.openmole/.tmp/ssh/5255b992-aae3-4fa6-8dce-a56079207f3d/tmp/1428599294970/f7aa5de4-88dd-420f-a74c-3711eb46bc1c/0d7f915e-6284-47ef-b3cd-32947d74f3
c3/.tmp/6039562a-31d2-465b-9029-bf5be624e9e0/filef357ba84-536c-465d-949c-bbc00cf05855.bin" "/homes/as12312/.openmole/.tmp/ssh/5255b992-aae3-4fa6-8dce-a56079207f3d/tmp/1428599294970/f7aa5de4-88d
d-420f-a74c-3711eb46bc1c/0d7f915e-6284-47ef-b3cd-32947d74f3c3/.tmp/6039562a-31d2-465b-9029-bf5be624e9e0/file66427b49-2517-4197-9347-6a807b55f887.bin" "-dofout" "/homes/as12312/.openmole/.tmp/ss
h/5255b992-aae3-4fa6-8dce-a56079207f3d/tmp/1428599294970/f7aa5de4-88dd-420f-a74c-3711eb46bc1c/0d7f915e-6284-47ef-b3cd-32947d74f3c3/.tmp/6039562a-31d2-465b-9029-bf5be624e9e0/fileb565ef71-5505-41
37-bce6-49de4dd2cdd0.bin" "-threads" "8" "-par" "Transformation model = Rigid" "-par" "Background value = 0"
ireg 3.2 (rev 01ff3acc, built on Apr  9 2015)
** ERROR (nifti_image_read): failed to find header file for '/homes/as12312/.openmole/.tmp/ssh/5255b992-aae3-4fa6-8dce-a56079207f3d/tmp/1428599294970/f7aa5de4-88dd-420f-a74c-3711eb46bc1c/0d7f91
5e-6284-47ef-b3cd-32947d74f3c3/.tmp/6039562a-31d2-465b-9029-bf5be624e9e0/filef357ba84-536c-465d-949c-bbc00cf05855.bin’

**Comment by schuhschuh** [comment]
I suggest that OpenMOLE only generates the file name without extension, but leaves the extension as it is in the input file. For output files, I suggest adding a parameter to the ```newFile``` function to allow users to specify an extension they need for their application. Some programs rely on the output file extension to decide in which format to store the output.

**Comment by schuhschuh** [comment]
Also, these very cryptic file names which do not allow to make a connection to the actual input file that was copied are rather complicated and hinder knowing which files were actually processed. I would prefer if the input file names would mostly be preserved. To avoid name conflicts, I would just add an incremental number or fixed length random string to the file name (before the extension), e.g.,

"1000.nii.gz" => "1000_66427b49-2517-4197-9347-6a807b55f887.nii.gz"
"target.nii.gz" => "target_f357ba84-536c-465d-949c-bbc00cf05855.nii.gz"

**Comment by romainreuillon** [comment]
You can achive that by doing: ScalaTask(....) set (inputFiles += (f, "blabla.nii.gz")) 
Then you can get that the file blabla.nii.gz with new File(workDir, "blabla.nii.gz") in you scala task.

Another way would be that you copy/rename you file with the correct extension in your task. 

To preserve the original file name you may use the zipWithName operation in your sampling:
http://www.openmole.org/current/documentation_console_sampling.html

Then you can use the "name" variable for naming your file in the hook.

**Comment by schuhschuh** [comment]
Hm, that's interesting. So the difference between ```inputs``` and ```inputFiles``` is that for the latter I provide tuples of File variables and desired file name, whereas in the first case I only specify the input variable which I could use to manually rename the file within the ScalaTask script.

**Comment by romainreuillon** [comment]
Exactly, in your case you can even use:
.... set ( inputFiles += (f, "file.ext", true) )

so that OpenMOLE will create a symlink instead and spare one copy by execution since you don't modify the file.

(I've always wonder whether symlink should be the default, but for now it is not)

**Comment by schuhschuh** [comment]
Ha! That sounds good.

On a related note, you mentioned the ```newFile``` function before. Is it only provided for convenience or does it do some more magic besides ensuring to return an unused file name ? I.e., is the following valid?

```scala
val f = Val[File]
val t = ScalaTask("""
     | val outputFile = new File(workDir, "output.nii.gz")
     | // some Scala code that writes to outputFile
  """.stripMargins) set (
  outputFiles += ("output.nii.gz", f)
)
```

And is this equivalent to the following which uses ```outputs``` instead of ```outputFiles``` (which is used in case of a SystemExecTask, but I think not needed when using a ScalaTask):

```scala
val f = Val[File]
val t = ScalaTask("""
     | val f = new File(workDir, "output.nii.gz")
     | // some Scala code that writes to outputFile
  """.stripMargins) set (
  outputs += f
)
```

This has the variable ```f``` point to the output file on the remote machine in the workflow. To copy it to my machine (from where it might be copied to another compute node if used in the following task), I then need to use the CopyFileHook with the desired output file name on my machine.

**Comment by romainreuillon** [comment]
Both codes are pretty equivalents. In any case you'll need a CopyFileHook to copy this file on your local machine. If the name of your output file is based on the name of the input file you should transmit the name variable (obtained by the zipWithName) all the way to the hook. You could either add it an input and output of your task or use the strainer mode of the capsules but it is not very documented yet.

For the ```newFile``` function it will provide a unique file location in a writeable space.

**Comment by schuhschuh** [comment]
> For the newFile function it will provide a unique file location in a writeable space.

Is it save to assume that the working directory (also stored in ```workDir```) is always a writable space ?

**Comment by romainreuillon** [comment]
Yes.

**Comment by romainreuillon** [comment]
... and dedicated to one single job execution.

**Comment by schuhschuh** [comment]
Yes, I noticed the per task subdirectories inside ```.openmole/```. Perfect then! Thanks for all your help. I hope I can use all this knowledge now to create a proper (and working!) workflow.

**Comment by schuhschuh** [comment]
How can I add multiple ```outputFiles``` tuples ?

```
<console>:171: error: type mismatch;
 found   : (String, org.openmole.core.workflow.data.Prototype[org.openmole.core.dsl.File])
    (which expands to)  (String, org.openmole.core.workflow.data.Prototype[java.io.File])
 required: String
    outputFiles += (("transformation" + dofSuf, dof6), ("output" + logSuf, dof6Log))
```

This works for ```inputFiles``` (with reverse order) but not for ```outputFiles```.

**Comment by romainreuillon** [comment]
You should write:
outputFiles += ("transformation" + dofSuf, dof6),
outputFiles += ("output" + logSuf, dof6Log)

**Comment by schuhschuh** [comment]
Correction, it also doesn't work for ```inputFiles```:

```
<console>:172: error: type mismatch;
 found   : (org.openmole.core.workflow.data.Prototype[org.openmole.core.dsl.File], String, Boolean)
    (which expands to)  (org.openmole.core.workflow.data.Prototype[java.io.File], String, Boolean)
 required: String
    inputFiles  += ((srcIm, imgPre + "${srcId}" + imgSuf, symLnk), (dof6, "initial_guess" + dofSuf, symLnk)),
```

Do I have to use these as follows:
```scala
val affineReg = ScalaTask(
  """
    | val src = new File(workDir, imgPre + "${srcId}" + imgSuf)
    | val ini = new File(workDir, "initial_guess"  + dofSuf)
    | val dof = new File(workDir, "transformation" + dofSuf)
    | val log = new File(workDir, "output" + logSuf)
    |
    | IRTK.ireg(refIm, src, Some(ini), dof, Some(log),
    |   "Transformation model" -> "Affine",
    |   "Background value"     -> 0,
    |   "Padding value"        -> 0
    | )
    |
  """.stripMargin) set(
    imports     += ("com.andreasschuh.repeat._", "com.andreasschuh.repeat.Workflow._"),
    usedClasses += (Workflow.getClass(), IRTK.getClass()),
    inputs      += srcId,
    inputFiles  += (srcIm, imgPre + "${srcId}" + imgSuf, symLnk),
    inputFiles  += (dof6, "initial_guess"      + dofSuf, symLnk),
    outputs     += (srcId, srcIm),
    outputFiles += ("transformation" + dofSuf, dof12),
    outputFiles += ("output" + logSuf, dof12Log)
  ) hook (
    CopyFileHook(dof12,    dof12Template),
    CopyFileHook(dof12Log, dof12LogTemplate)
  ) on parEnv
```

Got it !

**Comment by schuhschuh** [comment]
The previous code snippet gives me another error
```
Errors while compiling:

not found: value dof6
              mapAsJavaMap(Map[String, Any](  "dof6" -> dof6, "dof6Log" -> dof6Log, "srcId" -> srcId, "srcIm" -> srcIm ))
                                                        ^
on line 34


not found: value dof6Log
              mapAsJavaMap(Map[String, Any](  "dof6" -> dof6, "dof6Log" -> dof6Log, "srcId" -> srcId, "srcIm" -> srcIm ))
                                                                           ^
on line 34

```

**Comment by romainreuillon** [comment]
If you have dof6 and dof6Log as output of the task they should either be taken as input or be created by the task (val dof6 = ....).

**Comment by schuhschuh** [comment]
But this felt a bit redundant because in the ```outputFiles``` tuple I specify the name of the remote file within the ```workDir``` which should be associated with the ```dof6``` output variable. When I do ```val dof6 = new java.io.File("transformation" + dofSuf)``` in the ScalaTask, then why would I still use ```outputFiles``` ?

Is the answer actually hidden in what I said before with the two (maybe not so equivalent examples) that ```outputFiles``` is only used in conjunction with a SystemExecTask ?

**Comment by schuhschuh** [comment]
:( Looks like I cannot use input variables in the file name given to ```inputFiles``` (i.e., it's not an ExpandedString I suppose):

```
Caused by: java.lang.Exception: Source image does not exist: /Users/as12312/.openmole/cotopaxi/.tmp/2580120b-c8ee-4845-a42f-aa88e42ce961/category8081ac72-ad4b-4b49-b4d8-30e6903742e2/${srcId}_3.nii.gz
        at com.andreasschuh.repeat.IRTK$.ireg(IRTK.scala:90)
        at $line3.$read$$iw$$iw$$anonfun$1.apply(<console>:26)
        ... 23 more
```

The reason I wanted to do so is that the program output should contain meaningful file names, not just a generic "input.nii.gz".

**Comment by schuhschuh** [comment]
Forget my previous post. My fault, I didn't refer to the variable in the ScalaTask code correctly.

**Comment by schuhschuh** [comment]
Making slow progress. Still having trouble with the output files. The CopyFileHook which is supposed to copy the output generated by my program (ireg) to the local machine (I used LocalEnvironment(1), however) throws an error that the file doesn't exist. I added an output to my program which clearly states that it would have written the file to the location where the CopyFileHook wants to pick it up.

Also, why is the error message displayed twice ?

```
> "/Users/as12312/Data/Registrations/MAC2012/bin/ireg" "/Users/as12312/Data/Registrations/MAC2012/etc/mni305.nii.gz" "/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/1001_3.nii.gz" "-threads" "1" "-dofin" "/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/initial_guess.dof.gz" "-dofout" "/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/transformation.dof.gz" "-par" "Transformation model = Affine" "-par" "Background value = 0" "-par" "Padding value = 0"
ireg 3.2 (rev 09a07839, built on Apr  9 2015)

Resolution level 4

          Energy            Image dissimilarity    
   1      1.00000     =  1.00000 (     1.12068    )
   2      0.99627     =  0.99627 (     1.12397    )
   3      0.99610     =  0.99610 (     1.12411    )
   4      0.98779     =  0.98779 (     1.13142    )
   5      0.98555     =  0.98555 (     1.13339    )
   6      0.98115     =  0.98115 (     1.13726    )
   7      0.98080     =  0.98080 (     1.13757    )
   8      0.96909     =  0.96909 (     1.14787    )
   9      0.96548     =  0.96548 (     1.15103    )
  10      0.96385     =  0.96385 (     1.15247    )
  11      0.96370     =  0.96370 (     1.15260    )
  12      0.96291     =  0.96291 (     1.15330    )
  13      0.95858     =  0.95858 (     1.15710    )
  14      0.95744     =  0.95744 (     1.15810    )
  15      0.95680     =  0.95680 (     1.15867    )
  16      0.95656     =  0.95656 (     1.15888    )
  17      0.95518     =  0.95518 (     1.16010    )
  18      0.95506     =  0.95506 (     1.16020    )
  19      0.95387     =  0.95387 (     1.16124    )
  20      0.95339     =  0.95339 (     1.16167    )

Resolution level 3

          Energy            Image dissimilarity    
   1      1.00000     =  1.00000 (     1.09975    )
   2      0.99793     =  0.99793 (     1.10161    )
   3      0.99769     =  0.99769 (     1.10182    )
   4      0.99732     =  0.99732 (     1.10216    )
   5      0.99713     =  0.99713 (     1.10233    )
   6      0.99692     =  0.99692 (     1.10252    )

Resolution level 2

          Energy            Image dissimilarity    
   1      1.00000     =  1.00000 (     1.08938    )
   2      0.99968     =  0.99968 (     1.08968    )

Resolution level 1

          Energy            Image dissimilarity    
   1      1.00000     =  1.00000 (     1.08235    )
   2      0.99910     =  0.99910 (     1.08317    )


Final affine transformation:

    tx  = -108.8131  ty  = -121.8505  tz  = -121.6374
    rx  =  -5.8662  ry  =   1.5613  rz  =   2.6996
    sx  =  91.1136  sy  =  99.3629  sz  =  88.5183  
    sxy =  -0.7956  syz =  -3.0425  sxz =   0.9129  


Finished in 0 min 20 sec

Wrote transformation to file /Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/transformation.dof.gz

Apr 09, 2015 10:48:43 PM org.openmole.core.workflow.mole.SubMoleExecution org$openmole$core$workflow$mole$SubMoleExecution$$executeHook$1
SEVERE: Error in execution of misc org.openmole.plugin.hook.file.CopyFileHook$$anon$1$$anon$2@256a1f2cat the end of task scalaTask4
org.openmole.core.exception.InternalProcessingError: Error for context values in org.openmole.plugin.hook.file.CopyFileHook$$anon$1$$anon$2@256a1f2c {dof12=/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/transformation.dof.gz, dof12Log=/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/output.log, srcId=1001, srcIm=/Users/as12312/Data/Registrations/MAC2012/data/images/1001_3.nii.gz}
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:97)
        at org.openmole.plugin.hook.file.CopyFileHook.perform(CopyFileHook.scala:65)
        at org.openmole.core.workflow.mole.Hook$class.perform(Hook.scala:31)
        at org.openmole.plugin.hook.file.CopyFileHook.perform(CopyFileHook.scala:65)
        at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$executeHook$1(SubMoleExecution.scala:132)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$5.apply(SubMoleExecution.scala:140)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$5.apply(SubMoleExecution.scala:140)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:140)
        at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:256)
        at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$stateChanged$2(SubMoleExecution.scala:216)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
        at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:89)
        at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:93)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:100)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/transformation.dof.gz
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.openmole.core.tools.io.FileUtil$FileDecorator.copy(FileUtil.scala:145)
        at org.openmole.plugin.hook.file.CopyFileHook.org$openmole$plugin$hook$file$CopyFileHook$$copy(CopyFileHook.scala:86)
        at org.openmole.plugin.hook.file.CopyFileHook$$anonfun$process$2.apply(CopyFileHook.scala:70)
        at org.openmole.plugin.hook.file.CopyFileHook$$anonfun$process$2.apply(CopyFileHook.scala:70)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at org.openmole.plugin.hook.file.CopyFileHook.process(CopyFileHook.scala:70)
        at org.openmole.core.workflow.mole.Hook$$anonfun$perform$1.apply(Hook.scala:31)
        at org.openmole.core.workflow.mole.Hook$$anonfun$perform$1.apply(Hook.scala:31)
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
        ... 24 more

Apr 09, 2015 10:48:43 PM org.openmole.core.workflow.mole.SubMoleExecution jobFinished
SEVERE: Error in submole execution
org.openmole.core.exception.InternalProcessingError: Error for context values in org.openmole.plugin.hook.file.CopyFileHook$$anon$1$$anon$2@256a1f2c {dof12=/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/transformation.dof.gz, dof12Log=/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/output.log, srcId=1001, srcIm=/Users/as12312/Data/Registrations/MAC2012/data/images/1001_3.nii.gz}
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:97)
        at org.openmole.plugin.hook.file.CopyFileHook.perform(CopyFileHook.scala:65)
        at org.openmole.core.workflow.mole.Hook$class.perform(Hook.scala:31)
        at org.openmole.plugin.hook.file.CopyFileHook.perform(CopyFileHook.scala:65)
        at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$executeHook$1(SubMoleExecution.scala:132)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$5.apply(SubMoleExecution.scala:140)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$5.apply(SubMoleExecution.scala:140)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:140)
        at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:256)
        at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$stateChanged$2(SubMoleExecution.scala:216)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
        at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$10.apply(SubMoleExecution.scala:219)
        at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:89)
        at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:93)
        at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:100)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:65)
        at org.openmole.core.workflow.execution.local.LocalExecuter$$anonfun$run$1.apply(LocalExecuter.scala:57)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.openmole.core.workflow.execution.local.LocalExecuter.run(LocalExecuter.scala:57)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/transformation.dof.gz
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.openmole.core.tools.io.FileUtil$FileDecorator.copy(FileUtil.scala:145)
        at org.openmole.plugin.hook.file.CopyFileHook.org$openmole$plugin$hook$file$CopyFileHook$$copy(CopyFileHook.scala:86)
        at org.openmole.plugin.hook.file.CopyFileHook$$anonfun$process$2.apply(CopyFileHook.scala:70)
        at org.openmole.plugin.hook.file.CopyFileHook$$anonfun$process$2.apply(CopyFileHook.scala:70)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at org.openmole.plugin.hook.file.CopyFileHook.process(CopyFileHook.scala:70)
        at org.openmole.core.workflow.mole.Hook$$anonfun$perform$1.apply(Hook.scala:31)
        at org.openmole.core.workflow.mole.Hook$$anonfun$perform$1.apply(Hook.scala:31)
        at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
        ... 24 more
```

And here's the snippet from the OpenMOLE script:
```scala
// Affine registration mole
val dof12Template    = Path.join(dofDir, "affine", refId + ",${srcId}" + dofSuf)
val dof12LogTemplate = Path.join(logDir, "affine", refId + ",${srcId}" + logSuf)

val affineBegin = EmptyTask() set(
    inputs  += (srcId, srcIm, dof6),
    outputs += (srcId, srcIm, dof6, dof12)
  ) source FileSource(dof12Template, dof12)

val affineReg = ScalaTask(
  """
    | val src      = new java.io.File(workDir, imgPre + srcId + imgSuf)
    | val ini      = new java.io.File(workDir, "initial_guess"  + dofSuf)
    | val dof12    = new java.io.File(workDir, "transformation" + dofSuf)
    | val dof12Log = new java.io.File(workDir, "output" + logSuf)
    |
    | IRTK.ireg(refIm, src, Some(ini), dof12, Some(dof12Log),
    |   "Transformation model" -> "Affine",
    |   "Background value"     -> 0,
    |   "Padding value"        -> 0
    | )
    |
  """.stripMargin) set(
    imports     += ("com.andreasschuh.repeat._", "com.andreasschuh.repeat.Workflow._"),
    usedClasses += (Workflow.getClass(), IRTK.getClass()),
    inputs      += srcId,
    inputFiles  += (srcIm, imgPre + "${srcId}" + imgSuf, symLnk),
    inputFiles  += (dof6, "initial_guess"      + dofSuf, symLnk),
    outputs     += (srcId, srcIm, dof12, dof12Log)
  ) hook (
    CopyFileHook(dof12,    dof12Template),
    CopyFileHook(dof12Log, dof12LogTemplate)
  ) on parEnv

val affineEnd = Capsule(EmptyTask() set (
    inputs  += (srcId, srcIm, dof12),
    outputs += (srcId, srcIm, dof12)
  ))

val affineCond = "dof12.lastModified() < dof6.lastModified()"
val affineMole = affineBegin -- ((affineReg -- affineEnd) when affineCond, affineEnd when s"!($affineCond)")
```

**Comment by schuhschuh** [comment]
I added a sanity check to my program to read the output file right after it wrote it to disk from 
```/Users/as12312/.openmole/cotopaxi/.tmp/d2bf5f78-1fe0-4908-8fb2-94bdb71207e7/category7eb7e425-ca68-40c3-8bf4-6d42f15759eb/transformation.dof.gz```. As this succeeds, I can be sure that the file was produced and existed when my program exited. May it be that OpenMOLE is cleaning up the working directory before the CopyFileHook had a chance to copy it ?

**Comment by romainreuillon** [comment]
Indeed, that's a bug.... I am correcting it.

**Comment by schuhschuh** [comment]
It seems to work fine when I also add
```scala
    outputFiles += ("transformation.dof.gz", dof12),
    outputFiles += ("output.log", dof12Log)
```
to my ScalaTask. But should this really be necessary ? Using both, ```outputFiles``` and ```CopyFileHook``` ?

**Comment by romainreuillon** [comment]
I just pushed a patch, but I guess you will have to wait until the compilation is fixed to use it. (It should be done tomorrow, the compilation pb is in the GUI which is developed by Mathieu a college of mine)

**Comment by schuhschuh** [comment]
Ok, what is the downside when I use both ```outputFiles``` and the ```CopyFileHook``` ? Are the output files then copied twice ? Or is it a valid workaround for the moment ?

**Comment by romainreuillon** [comment]
If it is a bottleneck we can easily implement a MoveFileHook.

**Comment by schuhschuh** [comment]
But given that my home directory and the destination for the files are two separate network drives, this wouldn't actually help.

**Comment by romainreuillon** [comment]
Sorry, I've misread your question. The outputFiles stuff doesn't copy anything, it just prevent the deletion.

**Comment by schuhschuh** [comment]
Great, well then I can just use both ```outputFiles``` and ```CopyFileHook```.

**Comment by schuhschuh** [comment]
> I just pushed a patch, but I guess you will have to wait until the compilation is fixed to use it. (It should be done tomorrow, the compilation pb is in the GUI which is developed by Mathieu a college of mine)

Can you briefly explain what the difference in usage is after this patch (4af00010) ?

Does it mean the following will now work, i.e., no need for ```outputFiles``` when using a ScalaTask ?
```scala
val f = Val[File]
val t = ScalaTask("val f = newFile") set(outputs += f) hook CopyFileHook(f, "output.txt")
t.start
```

**Comment by romainreuillon** [comment]
Yes is should.
