### ISSUE TITLE
Silent error for missing resource in the WebUI

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#90]
A silent error is not reported when a resource cannot be found due to a wrong path (typical example: me forgetting to prefix a script location with `workDirectory /`).

It seems that something runs pretty intensively in the background though according to process list and fan noise.

The same mistake generates this stacktrace in the console:

```scala

Aug 04, 2015 4:56:15 PM org.openmole.core.batch.refresh.JobManager $bang

FINE: Error in job refresh

java.io.FileNotFoundException: msm.sh (No such file or directory)

at java.io.FileInputStream.open0(Native Method)

at java.io.FileInputStream.open(FileInputStream.java:195)

at java.io.FileInputStream.<init>(FileInputStream.java:138)

at org.openmole.tool.hash.package$.computeHash(package.scala:39)

at org.openmole.core.fileservice.FileService$$anonfun$hash$1.apply(FileService.scala:51)

at org.openmole.core.fileservice.FileService$$anonfun$hash$1.apply(FileService.scala:51)

at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)

at org.openmole.core.tools.cache.AssociativeCache$$anonfun$cacheMap$1$$anon$2.scala$collection$mutable$SynchronizedMap$$super$getOrElseUpdate(AssociativeCache.scala:46)

at scala.collection.mutable.SynchronizedMap$class.getOrElseUpdate(SynchronizedMap.scala:40)

at org.openmole.core.tools.cache.AssociativeCache$$anonfun$cacheMap$1$$anon$2.getOrElseUpdate(AssociativeCache.scala:46)

at org.openmole.core.tools.cache.AssociativeCache.cache(AssociativeCache.scala:42)

at org.openmole.core.fileservice.FileService$.hash(FileService.scala:48)

at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1$$anonfun$1.apply(UploadActor.scala:72)

at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1$$anonfun$1.apply(UploadActor.scala:72)

at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)

at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)

at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)

at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)

at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)

at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)

at scala.collection.immutable.TreeSet.scala$collection$SetLike$$super$map(TreeSet.scala:53)

at scala.collection.SetLike$class.map(SetLike.scala:92)

at scala.collection.immutable.TreeSet.map(TreeSet.scala:53)

at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:72)

at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:62)

at org.openmole.core.workspace.Workspace.withTmpFile(Workspace.scala:213)

at org.openmole.core.batch.refresh.UploadActor.org$openmole$core$batch$refresh$UploadActor$$initCommunication(UploadActor.scala:62)

at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply$mcV$sp(UploadActor.scala:51)

at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply(UploadActor.scala:47)

at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply(UploadActor.scala:47)

at org.openmole.core.batch.refresh.package$.withRunFinalization(package.scala:23)

at org.openmole.core.batch.refresh.UploadActor.receive(UploadActor.scala:47)

at org.openmole.core.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:82)

at org.openmole.core.batch.refresh.JobManager$$anonfun$1$$anon$1.run(JobManager.scala:64)
```

**Comment by jopasserat** [comment]
An invalid authentication produces the same behaviour and I guess it's linked to being able to report errors in the WebUI so no need to create yet another issue.

**Comment by romainreuillon** [comment]
The errors FileNotFound appears in debug mode and authentication error are now in severe mode. It might be good to better distinguish transient network errors from fatal errors, but I would consider that as an improvement for version 6.

**Comment by romainreuillon** [comment]
Fixed
