### ISSUE TITLE
Error during job refresh on SSHEnvironment

### ISSUE THREAD

**Issue by HKervadec** [openmole/openmole#93]
At the moment, jobs sent on SSHEnvironment fails continuously during job refresh : (logger FINE)
```
Aug 13, 2015 2:22:57 PM org.openmole.core.batch.refresh.JobManager $bang
FINE: Error in job refresh
org.openmole.core.batch.refresh.JobRemoteExecutionException: Fatal exception thrown during the execution of the job execution on the execution node
	at org.openmole.core.batch.refresh.GetResultActor.getResult(GetResultActor.scala:70)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1$$anonfun$apply$mcV$sp$1.apply(GetResultActor.scala:50)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1$$anonfun$apply$mcV$sp$1.apply(GetResultActor.scala:48)
	at org.openmole.core.batch.control.UsageControl$class.tryWithToken(UsageControl.scala:28)
	at org.openmole.plugin.environment.ssh.SSHPersistentStorage$$anon$1.tryWithToken(SSHPersistentStorage.scala:54)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1.apply$mcV$sp(GetResultActor.scala:48)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1.apply(GetResultActor.scala:46)
	at org.openmole.core.batch.refresh.GetResultActor$$anonfun$receive$1.apply(GetResultActor.scala:46)
	at org.openmole.core.batch.refresh.package$.withRunFinalization(package.scala:23)
	at org.openmole.core.batch.refresh.GetResultActor.receive(GetResultActor.scala:46)
	at org.openmole.core.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:85)
	at org.openmole.core.batch.refresh.JobManager$$anonfun$1$$anon$1.run(JobManager.scala:64)
Caused by: java.io.FileNotFoundException: /home/zomzom/.openmole/.tmp/ssh/b7f6d8b3-eee6-42a4-b392-dd2521aa8092/tmp/1439471967494/658002c3-1ae4-4306-b79f-dddf1504f081/71b63688-8ca2-4707-bf7b-a269073ffadd/.tmp/8644c8c8-28de-418c-8ca6-6da35e65e5b9/fileddbc9114-5529-4c4c-add8-9fdae1767f93.bin (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.openmole.tool.hash.package$.computeHash(package.scala:39)
	at org.openmole.tool.hash.package$FileHashServiceDecorator.hash(package.scala:31)
	at org.openmole.runtime.runtime.Runtime$$anonfun$uploadIndividualFiles$1$1.apply(Runtime.scala:172)
	at org.openmole.runtime.runtime.Runtime$$anonfun$uploadIndividualFiles$1$1.apply(Runtime.scala:157)
	at org.openmole.core.workspace.Workspace.withTmpFile(Workspace.scala:219)
	at org.openmole.runtime.runtime.Runtime.uploadIndividualFiles$1(Runtime.scala:157)
	at org.openmole.runtime.runtime.Runtime.apply(Runtime.scala:179)
	at org.openmole.runtime.runtime.SimExplorer$$anonfun$start$1.apply(SimExplorer.scala:87)
	at org.openmole.runtime.runtime.SimExplorer$$anonfun$start$1.apply(SimExplorer.scala:77)
	at scala.Option.foreach(Option.scala:257)
	at org.openmole.runtime.runtime.SimExplorer.start(SimExplorer.scala:77)
	at org.openmole.runtime.runtime.SimExplorer.start(SimExplorer.scala:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

The same goes with Condor and SLURM.
LocalEnvironment does not seem affected.

Tried with both snapshot and compiled version of openmole.

**Comment by romainreuillon** [comment]
203f36f0bd5849f650e67629cf22fa4a305bd962 fixes it.

**Comment by romainreuillon** [comment]
Can you test?

**Comment by jopasserat** [comment]
all good for me
