### ISSUE TITLE
When an error occurs in a hook it is not displayed by the editor

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#98]
This error of the workflow was displayed nowhere in the editor:

```
sept. 04, 2015 6:05:52 PM org.openmole.core.workflow.mole.SubMoleExecution jobFinished
GRAVE: Error in submole execution
org.openmole.core.exception.InternalProcessingError: Error for context values in CopyFileHook@511667020 {output=/home/reuillon/.openmole/simplet/.tmp/9fc6673f-14fc-4ebc-8819-2de3122a40ed/externalTask47f7bcf0-fbfd-43df-9cb3-8b7fc151e431/fsl/rootfs/home/reuillon/Documents/Recherche/Work/OpenMOLE/fsl/res, smoothness=0.3}
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:94)
	at org.openmole.plugin.hook.file.CopyFileHook.perform(CopyFileHook.scala:70)
	at org.openmole.core.workflow.mole.Hook$class.perform(Hook.scala:32)
	at org.openmole.plugin.hook.file.CopyFileHook.perform(CopyFileHook.scala:70)
	at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$executeHook$1(SubMoleExecution.scala:134)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$5.apply(SubMoleExecution.scala:142)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$5.apply(SubMoleExecution.scala:142)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.openmole.core.workflow.mole.SubMoleExecution.jobFinished(SubMoleExecution.scala:142)
	at org.openmole.core.workflow.mole.SubMoleExecution.finalState(SubMoleExecution.scala:260)
	at org.openmole.core.workflow.mole.SubMoleExecution.org$openmole$core$workflow$mole$SubMoleExecution$$stateChanged$2(SubMoleExecution.scala:219)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$11.apply(SubMoleExecution.scala:222)
	at org.openmole.core.workflow.mole.SubMoleExecution$$anonfun$11.apply(SubMoleExecution.scala:222)
	at org.openmole.core.workflow.job.MoleJob.signalChanged(MoleJob.scala:89)
	at org.openmole.core.workflow.job.MoleJob.state_$eq(MoleJob.scala:93)
	at org.openmole.core.workflow.job.MoleJob.perform(MoleJob.scala:100)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:71)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1$$anonfun$apply$1.apply(LocalExecutor.scala:63)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:63)
	at org.openmole.core.workflow.execution.local.LocalExecutor$$anonfun$1.apply(LocalExecutor.scala:60)
	at org.openmole.core.workflow.execution.local.LocalExecutor.withRedirectedOutput(LocalExecutor.scala:112)
	at org.openmole.core.workflow.execution.local.LocalExecutor.run(LocalExecutor.scala:60)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/reuillon/.openmole/simplet/.tmp/9fc6673f-14fc-4ebc-8819-2de3122a40ed/externalTask47f7bcf0-fbfd-43df-9cb3-8b7fc151e431/fsl/rootfs/home/reuillon/Documents/Recherche/Work/OpenMOLE/fsl/res (est un dossier)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.openmole.tool.file.FilePackage$FileDecorator.copyContent(package.scala:149)
	at org.openmole.plugin.hook.file.CopyFileHook.org$openmole$plugin$hook$file$CopyFileHook$$copy(CopyFileHook.scala:99)
	at org.openmole.plugin.hook.file.CopyFileHook$$anonfun$2.apply(CopyFileHook.scala:75)
	at org.openmole.plugin.hook.file.CopyFileHook$$anonfun$2.apply(CopyFileHook.scala:75)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at org.openmole.plugin.hook.file.CopyFileHook.process(CopyFileHook.scala:75)
	at org.openmole.core.workflow.mole.Hook$$anonfun$perform$1.apply(Hook.scala:32)
	at org.openmole.core.workflow.mole.Hook$$anonfun$perform$1.apply(Hook.scala:32)
	at org.openmole.core.workflow.tools.InputOutputCheck$class.perform(InputOutputCheck.scala:91)
	... 27 more
```

**Comment by romainreuillon** [comment]
fixed in ba3a23c6df044418b7a5af6c4648bd7bf37a0f1e
